// Inline everything under public/ into a single Worker module at dist/worker.js.
import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pub = join(root, 'public');
const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml', '.txt': 'text/plain; charset=utf-8',
  '.webmanifest': 'application/manifest+json', '.xml': 'application/xml; charset=utf-8',
};

const assets = {};
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) { walk(full); continue; }
    const ext = extname(name);
    if (!TYPES[ext]) throw new Error(`No text content-type for ${full}; binary assets aren't supported by this inliner.`);
    const body = readFileSync(full, 'utf8');
    const path = '/' + relative(pub, full).split('\\').join('/');
    assets[path] = { body, type: TYPES[ext], hash: createHash('sha256').update(body).digest('hex').slice(0, 16) };
  }
})(pub);

const worker = readFileSync(join(root, 'src', 'worker.js'), 'utf8');
const out = `// Generated by scripts/build.mjs — do not edit. ${new Date().toISOString()}\nconst ASSETS = ${JSON.stringify(assets)};\n${worker}`;
mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist', 'worker.js'), out);
const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
console.log(`dist/worker.js: ${Object.keys(assets).length} assets, ${kb} KB\n  ${Object.keys(assets).join('\n  ')}`);
