from common import Section
s=Section('8-exercises')
s.p('intro-exercises','Exercises on generalized eigenvectors and trace',r'''These optional exercises explore stabilization, nilpotent chains, characteristic polynomials, and trace. Except in the final infinite-dimensional example, every space is finite-dimensional over $\F$; statements involving the characteristic polynomial here use $\F=\C$.''')
s.r('ex-stable-range','The stable range carries an invertible restriction',r'''For $T\in\Lin(V)$ and $n=\dim V$, prove that $R=\Range T^n$ is invariant under $T$ and that $T|_R$ is invertible.''',r'''For $y=T^nx$ we have $Ty=T^n(Tx)\in R$, proving invariance. If $y\in R$ and $Ty=0$, write $y=T^nx$. Then $T^{n+1}x=0$. Stabilization gives $x\in\Null T^n$, so $y=0$. Thus the restriction has zero kernel, is injective, and is invertible as an operator on a finite-dimensional space. This includes $n=0$, when $R=\{0\}$ and its unique operator is invertible.''',2,20,[r'Apply kernel stabilization to a preimage of a vector in the kernel of the restriction.'],['thm-stabilization-dimension','c5-lem-operator-power-laws','c3-thm-equal-dimension-invertibility','c3-thm-injective-null'],kind='exercise',optional=True)
s.r('ex-nilpotent-geometric-inverse','A finite geometric formula for an inverse',r'''If $N^m=0$ with $m\ge1$, prove that $I-N$ is invertible and
\[(I-N)^{-1}=I+N+\cdots+N^{m-1}.\]''',r'''Put $A=\sum_{j=0}^{m-1}N^j$. Distributivity and the power laws give $(I-N)A=\sum_{j=0}^{m-1}N^j-\sum_{j=1}^mN^j=I-N^m=I$. Each power commutes with $N$, so multiplying in the other order gives the same telescoping expression, and $A(I-N)=I$. Thus $A$ is a two-sided inverse, as required. Empty intermediate cancellations when $m=1$ cause no exception.''',1,10,[r'Multiply the proposed inverse by $I-N$ on both sides.'],['def-nilpotent','c5-lem-operator-power-laws','c3-thm-composition-laws','c3-def-map-inverse'],kind='exercise',optional=True)
s.r('ex-nilpotent-power-index','Nilpotency index of a power',r'''On a nonzero space suppose $N$ has nilpotency index $m$. For $k\ge1$, prove that $N^k$ has index $\lceil m/k\rceil$, where this is the least integer $r$ with $kr\ge m$.''',r'''Every exponent $a\ge m$ has $N^a=N^{a-m}N^m=0$, whereas every integer $0\le a<m$ has $N^a\ne0$: for positive $a$ this is minimality of $m$, and at $a=0$ the identity is nonzero because the space is nonzero. Let $r$ be the stated least integer. Then $(N^k)^r=N^{kr}=0$. For every positive $j<r$ we have $kj<m$, so $(N^k)^j\ne0$. Hence $r$ is precisely the index.''',2,20,[r'Compare $kj$ with the first vanishing exponent of $N$.'],['def-nilpotent','c5-lem-operator-power-laws','c3-def-zero-identity-maps'],kind='exercise',optional=True)
s.r('ex-commuting-nilpotent-sum','A sum of commuting nilpotent operators',r'''Suppose $AB=BA$, $A^p=0$, and $B^q=0$, where $p,q\ge1$. Prove $(A+B)^{p+q-1}=0$.''',r'''Let $r=p+q-1$. Repeated distributivity expands $(A+B)^r$ as the sum of all products of length $r$ in which each factor is $A$ or $B$. This description follows by induction: multiplying the expansion for length $j$ by $A+B$ appends either $A$ or $B$ to each word and produces every length-$j+1$ word once. Since $A$ and $B$ commute, exchanging adjacent unlike factors does not change a product; finitely many such exchanges put each word in the form $A^aB^b$ with $a+b=r$. If both $a<p$ and $b<q$, their sum would be at most $p+q-2<r$. Thus either $a\ge p$ or $b\ge q$. In the first case $A^a=0$ and in the second $B^b=0$, so each word is zero. The whole sum is zero.''',3,30,[r'Expand into words in $A,B$ and use commutation to gather equal factors.'],['def-nilpotent','c5-def-commute','c5-lem-operator-power-laws','c3-thm-composition-laws'],kind='exercise',optional=True)
s.r('ex-nilpotent-noncommuting-sum','Commutation matters for a sum of nilpotents',r'''Give two nilpotent operators on $\F^2$ whose sum is invertible and therefore not nilpotent.''',r'''Set $A(x,y)=(y,0)$ and $B(x,y)=(0,x)$. Their coordinate expressions are linear, and each has square zero. Their sum $S(x,y)=(y,x)$ satisfies $S^2=I$, so $S$ is invertible with inverse itself. Every power of an invertible operator is invertible, as repeated composition of its inverse verifies. The zero map on the nonzero space $\F^2$ is not invertible. Consequently no positive power of $S$ can be zero, so $S$ is not nilpotent.''',2,20,[r'Use the two shifts in opposite directions on a two-dimensional space.'],['def-nilpotent','c3-thm-coordinate-linear-maps','c3-def-map-inverse','c5-lem-operator-power-laws'],kind='exercise',optional=True)
s.r('ex-commuting-generalized-space','Commuting operators preserve generalized eigenspaces',r'''If $AT=TA$, prove that $A$ maps $G(\lambda,T)$ into itself for every scalar $\lambda$.''',r'''Commutation gives $A(T-\lambda I)=(T-\lambda I)A$ by distributivity. Induction on $j$ then gives $A(T-\lambda I)^j=(T-\lambda I)^jA$: the case zero is the identity, and multiplying the case $j$ by $T-\lambda I$ proves the case $j+1$. If $n=\dim V$ and $v\in G(\lambda,T)$, the generalized-eigenspace formula gives $(T-\lambda I)^nv=0$. Hence $(T-\lambda I)^nAv=A(T-\lambda I)^nv=0$. The same formula now gives $Av\in G(\lambda,T)$, including when $Av=0$ and when the whole space is zero.''',2,20,[r'Commute $A$ past the power in the kernel description of $G(\lambda,T)$.'],['def-generalized-eigenspace','thm-generalized-eigenspace-kernel','c5-def-commute','c3-thm-composition-laws'],kind='exercise',optional=True)
s.r('ex-polynomial-generalized-vector','Polynomial images of generalized eigenvectors',r'''If $v$ is a generalized eigenvector of $T$ for $\lambda$ and $p$ is a polynomial, prove that $v$ is a generalized eigenvector of $p(T)$ for $p(\lambda)$.''',r'''The polynomial $p(z)-p(\lambda)$ vanishes at $\lambda$, so the factor theorem gives $p(z)-p(\lambda)=(z-\lambda)q(z)$ for a polynomial $q$; when the difference is zero, take $q=0$. Evaluation gives $p(T)-p(\lambda)I=(T-\lambda I)q(T)$. The factors commute because both are polynomials in $T$. By induction on $k$, the $k$th power of this product is $(T-\lambda I)^kq(T)^k=q(T)^k(T-\lambda I)^k$. Choose a positive $k$ with $(T-\lambda I)^kv=0$. The displayed product kills $v$. Since $v\ne0$, the generalized-vector power test applied to $p(T)$ shows that $p(\lambda)$ is an eigenvalue and that $v$ has the asserted property. This includes constant polynomials.''',3,30,[r'Factor $p(z)-p(\lambda)$ by $z-\lambda$.'],['def-generalized-eigenvector','thm-generalized-vector-power','c4-thm-factor-root','c5-thm-polynomial-evaluation-product','c5-def-polynomial-operator'],kind='exercise',optional=True)
s.r('ex-characteristic-affine','Characteristic polynomial after an affine change',r'''Let $V$ be complex of dimension $n$, $a\ne0$, and $b\in\C$. If $\chi_T$ is the characteristic polynomial of $T$, prove
\[\chi_{aT+bI}(z)=a^n\chi_T((z-b)/a).\]''',r'''For each scalar $\lambda$, the identity $(aT+bI)-(a\lambda+b)I=a(T-\lambda I)$ gives equality of the kernels of their $n$th powers, since $a^n\ne0$. Thus the corresponding generalized eigenspaces are equal and have equal dimensions. Ordinary eigenvector equations also show in both directions that the eigenvalues of $aT+bI$ are exactly $a\lambda+b$ for eigenvalues $\lambda$ of $T$; the inverse correspondence divides by $a$. If the distinct eigenvalues of $T$ are $\lambda_j$ with multiplicities $d_j$, the definition therefore gives
\[\chi_{aT+bI}(z)=\prod_j(z-b-a\lambda_j)^{d_j}=a^{\sum_jd_j}\prod_j((z-b)/a-\lambda_j)^{d_j}.\]
The multiplicity sum is $n$, yielding the formula. In dimension zero both polynomials are the empty product one, and $a^0=1$.''',3,30,[r'Compare the kernels defining the corresponding generalized eigenspaces.'],['def-characteristic-polynomial','thm-multiplicity-sum','thm-generalized-eigenspace-kernel','def-eigenvalue-multiplicity','c5-def-eigenvalue','c5-lem-operator-power-laws'],kind='exercise',optional=True)
s.r('ex-characteristic-inverse','Multiplicities under inversion',r'''Let $T$ be invertible on a complex space, with distinct eigenvalues $\lambda_j$ of multiplicities $d_j$. Prove that $T^{-1}$ has eigenvalues $\lambda_j^{-1}$ with the same multiplicities and characteristic polynomial $\prod_j(z-\lambda_j^{-1})^{d_j}$.''',r'''No eigenvalue $\lambda_j$ is zero. For any nonzero scalar $\lambda$,
\[T^{-1}-\lambda^{-1}I=-\lambda^{-1}T^{-1}(T-\lambda I).\]
The two factors on the right commute, because $T^{-1}T=TT^{-1}=I$. Raising to power $n=\dim V$ gives a nonzero scalar times the invertible operator $T^{-n}$ composed with $(T-\lambda I)^n$. Composing with an invertible operator does not change a kernel: its output is zero exactly when its input is zero. Thus $G(\lambda^{-1},T^{-1})=G(\lambda,T)$. Ordinary eigenvector equations, multiplied by $T$ or $T^{-1}$, show that inversion is also a bijection between the sets of eigenvalues. The equality of generalized eigenspaces proves preservation of multiplicity, and the characteristic-polynomial definition gives the product. With no eigenvalues in dimension zero the claimed product is one.''',3,35,[r'Factor $T^{-1}-\lambda^{-1}I$ using $T-\lambda I$.'],['thm-generalized-eigenspace-kernel','def-eigenvalue-multiplicity','def-characteristic-polynomial','c5-thm-eigenvalue-tests','c3-def-map-inverse','c5-lem-operator-power-laws'],kind='exercise',optional=True)
s.r('ex-jordan-kernel-count','Kernel dimensions count nilpotent Jordan blocks',r'''Suppose the Jordan blocks of a nilpotent $N$ have sizes $m_1,\ldots,m_r$. Put $d_k=\dim\Null N^k$ for $k\ge0$. Prove
\[d_k=\sum_{j=1}^r\min\{k,m_j\}.\]
Deduce that $d_k-d_{k-1}$ counts the blocks of size at least $k$ for $k\ge1$, and that $2d_k-d_{k-1}-d_{k+1}$ counts those of size exactly $k$.''',r'''Within a Jordan block of size $m$, label its basis $e_1,\ldots,e_m$ so that $Ne_1=0$ and $Ne_j=e_{j-1}$ for $j>1$. Induction gives $N^ke_j=0$ for $j\le k$ and $N^ke_j=e_{j-k}$ for $j>k$. The latter output vectors are distinct basis vectors, so a vector in this block is killed by $N^k$ exactly when its coefficients at indices greater than $k$ vanish. Its kernel dimension is therefore $\min\{k,m\}$. Distinct block spaces form a direct sum and their images remain in their respective block spaces. A sum of their images is zero exactly when every component image is zero. Hence the full kernel is the direct sum of the block kernels, and dimensions add, proving the formula. Subtracting the formulas at $k$ and $k-1$, each block contributes one if its size is at least $k$ and zero otherwise. Subtracting that count at $k+1$ leaves exactly the blocks of size $k$, giving the second difference. Empty lists give all dimensions zero.''',4,60,[r'Compute the kernel of a power on a single Jordan chain.',r'The first differences count surviving chains; subtract successive first differences.'],['def-jordan-basis','thm-nilpotent-jordan','c2-thm-dimension-sum','c1-thm-direct-zero'],kind='exercise',optional=True)
s.r('ex-jordan-reconstruct','Recovering a Jordan form from nullities',r'''Suppose $N$ is nilpotent on a six-dimensional space and
\[\dim\Null N=2,\quad\dim\Null N^2=4,\quad\dim\Null N^3=5,\quad\dim\Null N^4=6.\]
Determine its Jordan block sizes and minimal polynomial.''',r'''Choose a nilpotent Jordan basis. On a block of size $m$, the $k$th power kills its first $\min\{k,m\}$ vectors and maps the remaining vectors to distinct basis vectors. Thus the increment in kernel dimension from exponent $k-1$ to $k$ is the number of blocks of size at least $k$. The given increments are $2,2,1,1$, starting with $\dim\Null N^0=0$. The fourth kernel is the whole space, so $N^4=0$ and no block can have size greater than four. Exactly two blocks have size at least one and two, exactly one has size at least three and four, and none is larger. Hence their sizes are four and two. Also $N^3\ne0$ because its kernel has dimension five rather than six. The minimal polynomial of a nilpotent is $z^m$; its degree $m$ is the first vanishing exponent. Therefore the minimal polynomial is $z^4$.''',3,45,[r'First differences of successive nullities record how many chains are still growing.'],['thm-nilpotent-jordan','def-jordan-basis','thm-nilpotent-triangular','c2-thm-full-dimension-equality','c5-def-minimal-polynomial'],kind='exercise',optional=True)
s.r('ex-nilpotent-similarity','Nullities characterize nilpotent similarity',r'''For nilpotent operators $N\in\Lin(V)$ and $M\in\Lin(W)$, prove that there exists an isomorphism $A:V\to W$ satisfying $AN=MA$ if and only if $\dim\Null N^k=\dim\Null M^k$ for every positive integer $k$.''',r'''If such $A$ exists, induction gives $AN^k=M^kA$. Thus $A$ sends $\Null N^k$ into $\Null M^k$, and its inverse gives the reverse inclusion and a bijection. The null spaces have equal dimensions.
Conversely assume all these dimensions agree. At sufficiently large exponents both nilpotent powers are zero, so the dimensions of $V$ and $W$ agree. Choose Jordan bases for both operators. For a block of size $m$, the kernel dimension at exponent $k$ is $\min\{k,m\}$, because the first $\min\{k,m\}$ basis vectors are killed and the rest have independent images. Summing over the blocks gives the full nullity. Consequently the difference between the nullities at $k$ and $k-1$ counts blocks of size at least $k$, and subtracting the next such difference counts blocks of size exactly $k$. The assumed equality of nullities, with both zeroth nullities zero, proves equality of all block counts. Pair blocks of equal size and send the successive basis vectors in each block of $N$ to those in its paired block of $M$. This prescription sends a basis to a basis, hence defines an isomorphism $A$. On each basis vector both $AN$ and $MA$ give either zero or the preceding paired vector, so they agree everywhere. Empty bases provide the isomorphism when both spaces are zero.''',4,75,[r'For the reverse implication, recover the number of blocks of every size from the nullities.',r'Pair equal-sized chains and map their vectors in order.'],['thm-nilpotent-jordan','def-jordan-basis','c3-thm-linear-map-basis','c3-lem-isomorphism-basis','c3-thm-isomorphism-dimension','c5-lem-operator-power-laws'],kind='exercise',optional=True)
s.r('ex-trace-idempotent','The trace of an idempotent is its rank',r'''If $P^2=P$, prove $\tr P=\dim\Range P$ without assuming an inner product or self-adjointness.''',r'''Every vector decomposes as $v=Pv+(v-Pv)$, with $Pv\in\Range P$ and $P(v-Pv)=Pv-P^2v=0$. If $w\in\Range P\cap\Null P$, write $w=Px$; then $Pw=P^2x=Px=w$, while $Pw=0$, so $w=0$. Therefore $V=\Range P\oplus\Null P$. Choose bases of the two summands and concatenate them to obtain a basis of $V$. The map $P$ is identity on its range, because $P(Px)=Px$, and zero on its kernel. Its matrix in this basis is diagonal with $\dim\Range P$ ones followed by zeros. Summing the diagonal proves the trace formula, including the empty basis.''',2,20,[r'Decompose each vector into its image and its residual.'],['def-operator-trace','def-matrix-trace','c1-thm-direct-intersection','c2-thm-basis-existence','c3-def-map-matrix'],kind='exercise',optional=True)
s.r('ex-trace-pairing','Trace detects every matrix entry',r'''If $A\in\Lin(V)$ satisfies $\tr(AB)=0$ for every $B\in\Lin(V)$, prove $A=0$.''',r'''Choose a basis $e_1,\ldots,e_n$ and write $Ae_j=\sum_i a_{ij}e_i$. For fixed $j,k$ let $B$ send $e_k$ to $e_j$ and every other basis vector to zero. Then $AB$ has zero columns except column $k$, which is the $j$th column of $A$. Its only potentially nonzero diagonal entry is consequently the entry $a_{kj}$ in position $(k,k)$. Thus $0=\tr(AB)=a_{kj}$. Since $j,k$ were arbitrary, all entries of $A$ vanish and $A=0$. If $n=0$, there are no entries and the unique operator already is zero.''',3,30,[r'Test against maps with exactly one nonzero matrix entry.'],['def-operator-trace','def-matrix-trace','c3-thm-linear-map-basis','c3-def-map-matrix'],kind='exercise',optional=True)
s.r('ex-single-chain-no-root','A nontrivial single nilpotent chain has no square root',r'''Let $n\ge2$ and suppose $N$ on an $n$-dimensional space has a single nilpotent Jordan block of size $n$. Prove that no operator $R$ satisfies $R^2=N$.''',r'''In its Jordan basis, $N^n=0$ and $N^{n-1}$ sends the last basis vector to the first, so $N^{n-1}\ne0$. If $R^2=N$, then $R^{2n}=N^n=0$, making $R$ nilpotent. The dimension bound forces $R^n=0$. Because $2n-2\ge n$ for $n\ge2$, this implies $N^{n-1}=R^{2n-2}=0$, contradicting the nonzero value just found. Therefore no square root exists over either field.''',3,35,[r'Any proposed square root would itself be nilpotent; compare its dimension-bound exponent with that of the given chain.'],['def-jordan-basis','thm-nilpotent-index-bound','def-nilpotent','c5-lem-operator-power-laws'],kind='exercise',optional=True)
s.r('ex-infinite-identity-commutator','An identity commutator on the full polynomial space',r'''On the infinite-dimensional space $\Poly(\F)$, define $Dp=p'$ and $(Mp)(x)=xp(x)$. Prove $DM-MD=I$. Explain precisely why the finite-dimensional trace obstruction does not apply.''',r'''Differentiation is linear and multiplication by $x$ distributes over sums and commutes with scalar multiplication, so both maps are linear operators on the full polynomial space. For a polynomial $p(x)=\sum_{j=0}^m a_jx^j$, the differentiation formula gives
\[(DMp)(x)=\sum_{j=0}^m(j+1)a_jx^j,\qquad(MDp)(x)=\sum_{j=1}^m ja_jx^j.\]
Subtracting leaves $\sum_{j=0}^m a_jx^j=p(x)$, proving the operator identity. This space is infinite-dimensional, so the theorem excluding an identity commutator on a nonzero finite-dimensional space has an unmet hypothesis. Trace in this module is defined by a finite basis and is not defined here. Restricting to polynomials of a fixed degree bound does not fix the issue, because $M$ does not preserve that subspace: it sends its highest-degree monomial to one of larger degree.''',2,20,[r'Compute on a general polynomial coefficient by coefficient.'],['c2-thm-polynomial-differentiation','c2-ex-polynomial-dimension','c2-thm-polynomials-infinite','thm-no-identity-commutator','def-operator-trace','c2-def-polynomial'],kind='exercise',optional=True)
s.card('ex-stable-range','ex-stable-range',r'What does $T$ do on the range of its dimension power?',r'It restricts to an invertible operator on that invariant range.')
s.card('ex-geometric-inverse','ex-nilpotent-geometric-inverse',r'If $N^m=0$, what is $(I-N)^{-1}$?',r'$I+N+\cdots+N^{m-1}$.')
s.card('ex-index-power','ex-nilpotent-power-index',r'How does taking the $k$th power change nilpotency index $m$ on a nonzero space?',r'The new index is $\lceil m/k\rceil$.')
s.card('ex-nullity-count','ex-jordan-kernel-count',r'What does $\dim\Null N^k-\dim\Null N^{k-1}$ count for nilpotent $N$?',r'The number of Jordan blocks of size at least $k$.')
s.card('ex-nilpotent-similar','ex-nilpotent-similarity',r'Which nullity data determine a nilpotent operator up to similarity?',r'The dimensions of the kernels of all positive powers.')
s.card('ex-idempotent-trace','ex-trace-idempotent',r'What is the trace of an idempotent?',r'The dimension of its range, even without self-adjointness.')
s.card('ex-no-root','ex-single-chain-no-root',r'Can a nilpotent operator with one block of size at least two have a square root?',r'No. The proposed root would be nilpotent with an incompatible dimension bound.')
s.card('ex-infinite-commutator','ex-infinite-identity-commutator',r'Which two operators on the full polynomial space have commutator equal to the identity?',r'Differentiation $D$ and multiplication by $x$, denoted $M$, satisfy $DM-MD=I$.')
s.write()
