from common import Section
s=Section('5a')
s.p('intro-eigenvalues','Studying an operator on smaller subspaces',r'''A linear map from a space to itself can be composed with itself repeatedly. We first look for subspaces that it preserves, especially lines, and then use powers and polynomials to construct more operators. Throughout, $\F$ is $\R$ or $\C$ and every space uses that scalar field.''',133)
s.d('def-operator','Operators',r'''An operator on $V$ is a linear map $T:V\to V$. The notation $\Lin(V)$ denotes the vector space of all such maps.''','5.1',133)
s.d('def-invariant','Invariant subspaces',r'''For $T\in\Lin(V)$, a subspace $U\subseteq V$ is invariant under $T$ if $Tu\in U$ for every $u\in U$. In that case the restriction $T|_U:U\to U$, defined by the same formula on the smaller domain, is an operator: its linearity identities are those of $T$ with inputs in $U$.''','5.2',133)
s.r('ex-differentiation-invariant','Bounded-degree polynomials are preserved by differentiation',r'''For differentiation $D\in\Lin(\Poly(\R))$, every $\Poly_m(\R)$ with $m\ge0$ is invariant. In particular this holds for $\Poly_4(\R)$.''',r'''The bounded-degree polynomial space is a subspace. If $p(x)=\sum_{j=0}^m a_jx^j$, its derivative is $\sum_{j=1}^m ja_jx^{j-1}$. For $m\ge1$ all exponents here are at most $m-1$, and hence at most $m$. If $m=0$, the derivative is zero, also in $\Poly_0(\R)$. Thus every member is sent back into the same subspace, proving invariance.''',1,10,[r'Compare the degrees before and after differentiation, including constants.'],['def-invariant','c3-ex-polynomial-differentiation','c2-thm-bounded-polynomials','c2-thm-polynomial-differentiation'],'5.3',133,'example')
s.r('thm-basic-invariant-subspaces','Four subspaces preserved by every operator',r'''For $T\in\Lin(V)$, each of $\{0\}$, $V$, $\Null T$, and $\Range T$ is invariant under $T$. These subspaces need not be distinct.''',r'''All four are subspaces: the zero space and whole space satisfy the subspace test, and the kernel and range are subspaces by the corresponding map theorems. Preservation of zero gives $T0=0$, so the zero space is invariant. The target of $T$ is $V$, so $V$ is invariant. If $u\in\Null T$, then $Tu=0$, and $0$ belongs to the null space. Finally if $u\in\Range T$, its image $Tu$ belongs to $\Range T$ because $u\in V$ is an input producing that image. Thus each set satisfies the invariance condition.''',1,10,[r'Check the membership condition separately for each subspace.'],['def-operator','def-invariant','c3-thm-linear-zero','c3-thm-null-subspace','c3-thm-range-subspace','c3-def-null-space','c3-def-range','c1-thm-subspace-test'],'5.4',133)
s.r('lem-invariant-line','Invariant lines and scalar multiples',r'''For a nonzero $v\in V$, the line $\Span(v)$ is invariant under $T$ exactly when $Tv=\lambda v$ for some $\lambda\in\F$. Every one-dimensional invariant subspace arises this way.''',r'''If the span is invariant, then $v$ belongs to it and so does $Tv$, which therefore is some scalar multiple $\lambda v$. Conversely, if $Tv=\lambda v$, then for every $av$ in the line, $T(av)=aTv=a\lambda v$ also belongs to the line. This proves invariance. A nonzero one-vector list is independent and spans its line, so the line has dimension one. Conversely a basis of a one-dimensional subspace consists of a single nonzero vector; the subspace is its span, and the equivalence just proved applies.''',2,15,[r'An invariant one-dimensional space is spanned by any one of its nonzero vectors.'],['def-invariant','c2-def-span','c2-ex-single-independent','c2-def-basis','c2-def-dimension','c3-def-linear-map'],page=134,kind='lemma')
s.d('def-eigenvalue','Eigenvalues',r'''A scalar $\lambda\in\F$ is an eigenvalue of an operator $T$ if there is a vector $v\ne0$ with $Tv=\lambda v$. The requirement $v\ne0$ is part of this definition.''','5.5',134)
s.r('ex-coordinate-eigenvalue','Checking a proposed eigenvalue',r'''For $T:\F^3\to\F^3$ defined by $T(x,y,z)=(7x+3z,3x+6y+9z,-6y)$, prove that $T$ is an operator and that $6$ is an eigenvalue.''',r'''Every output coordinate is a scalar linear combination of the input coordinates, so the coordinate-map theorem proves linearity, and the equal domain and target make it an operator. The nonzero vector $(3,1,-1)$ satisfies
\[T(3,1,-1)=(21-3,9+6-9,-6)=(18,6,-6)=6(3,1,-1).\]
This is the defining eigenvalue equation.''',1,10,[r'Test the vector $(3,1,-1)$.'],['def-operator','def-eigenvalue','c3-thm-coordinate-linear-maps'],'5.6',134,'example')
s.r('thm-eigenvalue-tests','Equivalent tests for an eigenvalue',r'''If $V$ is finite-dimensional and $T\in\Lin(V)$, then for $\lambda\in\F$ the following are equivalent: $\lambda$ is an eigenvalue; $T-\lambda I$ is not injective; $T-\lambda I$ is not surjective; $T-\lambda I$ is not invertible. The equivalence of the first two conditions also holds without finite-dimensionality.''',r'''The map $T-\lambda I$ is linear by the vector-space operations on linear maps. For any $v$, $(T-\lambda I)v=0$ exactly when $Tv=\lambda v$. Thus there is a nonzero solution of this equation exactly when $\Null(T-\lambda I)\ne\{0\}$, which is equivalent to failure of injectivity by the kernel criterion. This argument does not require finite-dimensionality. In finite dimensions the domain and target of $T-\lambda I$ have equal dimension; the theorem equating injectivity, surjectivity, and invertibility therefore equates their negations. On the zero space all maps in question are invertible and no nonzero vector exists, so all four conditions are false, consistently with the equivalence.''',2,15,[r'Rewrite the eigenvalue equation as a kernel condition.'],['def-eigenvalue','c3-thm-linear-map-space','c3-thm-injective-null','c3-thm-equal-dimension-invertibility'],'5.7',135)
s.d('def-eigenvector','Eigenvectors',r'''A vector $v$ is an eigenvector of $T$ corresponding to $\lambda$ when $v\ne0$ and $Tv=\lambda v$. Thus the eigenvectors for $\lambda$ are precisely the nonzero members of $\Null(T-\lambda I)$.''','5.8',135)
s.r('ex-real-complex-eigenvalues','The scalar field changes the eigenvalues',r'''Let $T(w,z)=(-z,w)$ on $\F^2$. Over $\R$, this operator has no eigenvalues. Over $\C$, its eigenvalues are exactly $i$ and $-i$; the corresponding eigenvectors are respectively $(w,-iw)$ and $(w,iw)$ with $w\in\C\setminus\{0\}$.''',r'''The coordinate-map theorem gives linearity. A nonzero vector satisfying $T(w,z)=\lambda(w,z)$ must obey $-z=\lambda w$ and $w=\lambda z$. If $z=0$, the second equation forces $w=0$, which is excluded. Substitution therefore gives $(\lambda^2+1)z=0$ with $z\ne0$, so $\lambda^2=-1$. No real scalar satisfies this because real squares are nonnegative. Over $\C$, the equation is $(\lambda-i)(\lambda+i)=0$. A product of two scalars is zero only if a factor is zero, so its only possibilities are $\lambda=i,-i$. If $\lambda=i$, the first equation gives $z=-iw$, and direct substitution shows every vector of that form satisfies both equations. It is nonzero exactly when $w\ne0$. If $\lambda=-i$, the first equation gives $z=iw$, and direct substitution again proves both equations with nonzero vector exactly when $w\ne0$. This proves completeness of the stated lists.''',2,20,[r'Solve the two scalar equations and use that the vector cannot be zero.'],['def-eigenvalue','def-eigenvector','c3-thm-coordinate-linear-maps','c1-foundations','c1-def-complex','c1-lem-scalar-cancellation'],'5.9',135,'example')
s.r('thm-distinct-eigenvectors','Eigenvectors for distinct eigenvalues are independent',r'''For any operator, a finite list of eigenvectors corresponding to pairwise distinct eigenvalues is linearly independent.''',r'''Induct on the list length $m$. The empty list is independent by definition. For $m=1$, the eigenvector is nonzero, so its one-vector list is independent. Suppose $m\ge2$ and the assertion holds for $m-1$. Let $Tv_j=\lambda_jv_j$ with the $\lambda_j$ distinct, and suppose $\sum_{j=1}^m a_jv_j=0$. Apply the linear map $T-\lambda_m I$. It takes zero to zero and annihilates $v_m$, giving
\[\sum_{j=1}^{m-1}a_j(\lambda_j-\lambda_m)v_j=0.\]
The first $m-1$ eigenvectors are independent by induction. Hence $a_j(\lambda_j-\lambda_m)=0$ for $j<m$. The eigenvalue differences are nonzero, so each $a_j=0$ for $j<m$. The original relation reduces to $a_mv_m=0$; since $v_m\ne0$, its coefficient also vanishes. This proves the induction without a finite-dimensionality assumption on the space.''',3,30,[r'Use induction on the number of eigenvectors.',r'Apply $T-\lambda_m I$ to remove the last vector from a relation.'],['def-eigenvector','c3-thm-linear-map-space','c3-thm-linear-zero','c3-def-linear-map','c2-def-linear-independence','c2-ex-single-independent','c1-lem-scalar-cancellation'],'5.11',136)
s.r('cor-eigenvalue-bound','The dimension bounds the number of distinct eigenvalues',r'''An operator on a finite-dimensional space $V$ has at most $\dim V$ distinct eigenvalues.''',r'''Write $n=\dim V$. If there were more than $n$ distinct eigenvalues, choose $n+1$ of them and a corresponding eigenvector for each. The preceding theorem makes this list independent. Comparing it with a basis of $V$, which is a spanning list of length $n$, gives $n+1\le n$, a contradiction. This also treats $n=0$: the existence of even one eigenvalue would supply a nonzero eigenvector, an independent list longer than the empty basis.''',1,10,[r'Choose one eigenvector for each of a proposed collection of distinct eigenvalues.'],['def-eigenvalue','thm-distinct-eigenvectors','c2-thm-basis-existence','c2-thm-independent-length','c2-def-dimension'],'5.12',136,kind='corollary')
s.d('def-operator-powers','Integer powers of an operator',r'''For $T\in\Lin(V)$ define $T^0=I$ and $T^{m+1}=T^mT$ for nonnegative $m$. If $T$ is invertible, also define $T^{-m}=(T^{-1})^m$ for positive $m$. Compositions and the identity are linear, so these powers are operators.''','5.13',137)
s.r('lem-operator-power-laws','Laws of operator powers',r'''For nonnegative integers $m,n$, $T^mT^n=T^{m+n}$ and $(T^m)^n=T^{mn}$. If $T$ is invertible, both laws hold for all integers $m,n$.''',r'''For nonnegative exponents, induct on $n$ to obtain the product law. The case $n=0$ is the identity law. The induction step uses associativity:
\[T^mT^{n+1}=T^m(T^nT)=(T^mT^n)T=T^{m+n}T=T^{m+n+1}.\]
Now induction on $n$ gives $(T^m)^n=T^{mn}$: the zero case is identity, and multiplying the induction assertion by $T^m$ and applying the product law proves the next case.
Assume $T$ invertible. The factors $T$ and $T^{-1}$ commute because both products equal $I$. A finite product containing these two factors can therefore be reordered by successive adjacent interchanges; adjacent inverse pairs then cancel. For $T^mT^n$, if both exponents are nonnegative the earlier law applies, and if both are nonpositive apply that law to $T^{-1}$. If one exponent is positive and the other negative, cancellation removes the smaller of the two counts of factors and leaves exactly $T^{m+n}$, with identity if the counts coincide. This proves the product law for all integers.
In particular $T^mT^{-m}=T^{-m}T^m=I$, so $T^m$ is invertible with inverse $T^{-m}$. For any integer $m$ and nonnegative $n$, induction using the integer product law gives $(T^m)^n=T^{mn}$. If $n=-k$ with $k>0$, then
\[(T^m)^n=((T^m)^{-1})^k=(T^{-m})^k=T^{-mk}=T^{mn}.\]
All integer cases are thus covered.''',3,35,[r'First prove the nonnegative cases by induction.',r'For negative exponents, use the commuting factors $T$ and $T^{-1}$ and cancel inverse pairs.'],['def-operator-powers','c3-thm-composition-laws','c3-def-map-inverse','c3-def-invertible-map'],page=137,kind='lemma')
s.d('def-polynomial-operator','Evaluating a polynomial at an operator',r'''If $p(z)=\sum_{j=0}^m a_jz^j$, define $p(T)=\sum_{j=0}^m a_jT^j$. Its constant term is $a_0I$. Polynomial coefficient uniqueness makes this independent of the representation: appending zero coefficients changes the sum only by zero operators.''','5.14',137)
s.r('ex-polynomial-differential-operator','A polynomial in differentiation',r'''For differentiation $D$ on $\Poly(\R)$ and $p(z)=7-3z+5z^2$, prove that
\[(p(D))q=7q-3q'+5q''\qquad(q\in\Poly(\R)).\]''',r'''By definition, $p(D)=7I-3D+5D^2$. Applying this operator to $q$ gives $7Iq-3Dq+5D(Dq)$. The identity returns $q$, differentiation returns $q'$, and its second application returns $(q')'=q''$. Substituting gives the formula. These are all polynomials by closure of polynomial differentiation.''',1,10,[r'Replace each power by the corresponding repeated differentiation.'],['def-polynomial-operator','def-operator-powers','c3-ex-polynomial-differentiation','c3-def-map-operations'],'5.15',138,'example')
s.r('thm-polynomial-evaluation-linear','Polynomial evaluation is linear',r'''For a fixed operator $T$, the map $p\mapsto p(T)$ from $\Poly(\F)$ to $\Lin(V)$ is linear. It sends the constant polynomial $1$ to $I$ and the polynomial $z$ to $T$.''',r'''Each $p(T)$ is a finite sum of scalar multiples of operators and hence belongs to $\Lin(V)$. Pad the coefficient lists of $p$ and $q$ to the same length and write them $a_j,b_j$. Then the coefficient of $z^j$ in $p+q$ is $a_j+b_j$, so
\[(p+q)(T)=\sum_j(a_j+b_j)T^j=\sum_ja_jT^j+\sum_jb_jT^j=p(T)+q(T).\]
For a scalar $c$, the coefficients of $cp$ are $ca_j$, giving $(cp)(T)=\sum_jca_jT^j=cp(T)$. The displayed rearrangements use the vector-space identities in $\Lin(V)$. The constant polynomial $1$ evaluates to $T^0=I$, and $z$ evaluates to $T^1=T$ by the power definition and the identity law.''',1,10,[r'Use common-length coefficient lists for the two polynomials.'],['def-polynomial-operator','def-operator-powers','c2-def-polynomial','c3-thm-linear-map-space','c3-thm-composition-laws'],page=138)
s.d('def-polynomial-product','Pointwise polynomial products',r'''For polynomials $p,q$, their product is the polynomial $(pq)(z)=p(z)q(z)$. Products and their degree properties were established in the polynomial chapter. We now compare this product with composition after evaluation at an operator.''','5.16',138)
s.r('thm-polynomial-evaluation-product','Polynomial evaluation respects products',r'''For $p,q\in\Poly(\F)$ and $T\in\Lin(V)$,
\[(pq)(T)=p(T)q(T)=q(T)p(T).\]''',r'''Write $p(z)=\sum_{j=0}^m a_jz^j$ and $q(z)=\sum_{k=0}^n b_kz^k$. Scalar distributivity gives $(pq)(z)=\sum_{j,k}a_jb_kz^{j+k}$. Grouping equal exponents gives its polynomial coefficient representation. The definition of evaluation and vector-space distributivity then give
\[(pq)(T)=\sum_{j,k}a_jb_kT^{j+k}=\sum_{j,k}a_jb_kT^jT^k.\]
For operators $A,B$, scalars $a,b$, and input $v$, $((aA)(bB))v=aA(bBv)=abA(Bv)$ by linearity of $A$. Thus scalar factors in such compositions multiply as used in the double sum. Applying both distributive laws for composition finitely many times now identifies the last sum with $(\sum_ja_jT^j)(\sum_kb_kT^k)=p(T)q(T)$. Finally scalar multiplication in $\F$ is commutative, so $pq=qp$ as polynomials. The product identity already proved, applied in the opposite order, gives $q(T)p(T)=(qp)(T)=(pq)(T)$. Constant and zero polynomials are included by their coefficient representations.''',2,20,[r'Expand both sides into a finite double sum.',r'The power law combines $T^jT^k$ into $T^{j+k}$.'],['def-polynomial-product','def-polynomial-operator','lem-operator-power-laws','c3-thm-composition-laws','c3-def-linear-map','c4-lem-polynomial-product-degree','c2-lem-polynomial-coefficients'],'5.17',138)
s.r('lem-polynomial-eigenvector','Evaluating a polynomial on an eigenvector',r'''If $Tv=\lambda v$ with $v\ne0$, then $p(T)v=p(\lambda)v$ for every polynomial $p$.''',r'''Induction gives $T^jv=\lambda^jv$ for every $j\ge0$. At $j=0$ both sides equal $v$. If the assertion holds at $j$, associativity and the power law give $T^{j+1}v=T(T^jv)=T(\lambda^jv)=\lambda^jTv=\lambda^{j+1}v$. Therefore, writing $p(z)=\sum a_jz^j$, we have $p(T)v=\sum a_jT^jv=\sum a_j\lambda^jv=p(\lambda)v$ by distributivity.''',2,15,[r'First prove the formula for powers by induction.'],['def-polynomial-operator','def-eigenvector','lem-operator-power-laws','c3-def-linear-map','c1-def-vector-space'],page=139,kind='lemma')
s.r('thm-polynomial-invariant','Kernels and ranges of polynomial operators are invariant',r'''For any $T\in\Lin(V)$ and $p\in\Poly(\F)$, the subspaces $\Null p(T)$ and $\Range p(T)$ are invariant under $T$.''',r'''They are subspaces because $p(T)$ is a linear map. Apply the product-commutation theorem to $p$ and the polynomial $z$, whose evaluation is $T$, to obtain $p(T)T=Tp(T)$. If $u\in\Null p(T)$, then $p(T)(Tu)=T(p(T)u)=T0=0$, so $Tu$ belongs to the same kernel. If $u\in\Range p(T)$, choose $v$ with $u=p(T)v$. Then $Tu=Tp(T)v=p(T)(Tv)$ belongs to that range. These are precisely the two invariance requirements.''',2,15,[r'Use the fact that $T$ commutes with $p(T)$.'],['def-invariant','def-polynomial-operator','thm-polynomial-evaluation-linear','thm-polynomial-evaluation-product','c3-thm-null-subspace','c3-thm-range-subspace','c3-thm-linear-zero','c3-def-null-space','c3-def-range'],'5.18',139)
s.card('invariant','def-invariant',r'What does it mean for a subspace to be invariant under an operator?',r'The operator sends every vector of the subspace back into that subspace.')
s.card('eigenvalue-nonzero','def-eigenvalue',r'What nonzero requirement appears in the definition of an eigenvalue?',r'There must be a nonzero vector $v$ satisfying $Tv=\lambda v$. The scalar $\lambda$ itself may be zero.')
s.card('eigenvalue-invertibility','thm-eigenvalue-tests',r'How does invertibility detect eigenvalues in finite dimensions?',r'$\lambda$ is an eigenvalue exactly when $T-\lambda I$ is not invertible.')
s.card('real-rotation','ex-real-complex-eigenvalues',r'What are the eigenvalues of $(w,z)\mapsto(-z,w)$ over $\R$ and over $\C$?',r'None over $\R$; $i$ and $-i$ over $\C$.')
s.card('distinct-eigenvectors','thm-distinct-eigenvectors',r'What happens to eigenvectors for distinct eigenvalues?',r'Every finite such list is linearly independent.')
s.card('eigenvalue-count','cor-eigenvalue-bound',r'How many distinct eigenvalues can an operator on an $n$-dimensional space have?',r'At most $n$.')
s.card('polynomial-constant-term','def-polynomial-operator',r'What replaces the constant term $a_0$ in $p(T)$?',r'The operator $a_0I$.')
s.card('polynomial-commutation','thm-polynomial-evaluation-product',r'Why do $p(T)$ and $q(T)$ commute?',r'Both products equal $(pq)(T)$, and scalar polynomials satisfy $pq=qp$.')
s.card('polynomial-invariant','thm-polynomial-invariant',r'Which two subspaces associated to $p(T)$ are invariant under $T$?',r'$\Null p(T)$ and $\Range p(T)$.')
s.write()
