from common import Section
s=Section('3a')
s.p('intro-linear-maps','Maps that respect vector arithmetic',r'''A linear map transports sums and scalar multiples without changing their algebraic form. We examine concrete examples, construct maps by prescribing values on a basis, and then study addition and composition of maps. All vector spaces in this section use the same scalar field $\F$.''',52)
s.d('def-linear-map','Linear maps',r'''A function $T:V\to W$ between vector spaces over $\F$ is linear if $T(u+v)=Tu+Tv$ for all $u,v\in V$ and $T(av)=aTv$ for all $a\in\F$ and $v\in V$. We may write $Tv$ instead of $T(v)$.''','3.1',52)
s.d('def-linear-map-space','Notation for collections of linear maps',r'''The set of linear maps from $V$ to $W$ is denoted by $\Lin(V,W)$. Write $\Lin(V)=\Lin(V,V)$.''','3.2',52)
s.d('def-zero-identity-maps','Zero and identity maps',r'''The zero map $0:V\to W$ sends every vector to $0_W$. The identity map $I_V:V\to V$ sends each $v$ to itself. We omit the subscript on $I$ when its space is determined by the expression.''',page=52)
s.r('ex-zero-identity-linear','Zero and identity maps are linear',r'''The zero map belongs to $\Lin(V,W)$ and $I_V$ belongs to $\Lin(V)$.''',r'''For the zero map, $0(u+v)=0_W=0_W+0_W=0u+0v$, and $0(av)=0_W=a0_W=a(0v)$. For the identity map, $I_V(u+v)=u+v=I_Vu+I_Vv$ and $I_V(av)=av=aI_Vv$. These are the two required identities for each map.''',1,10,[r'Apply each map to the two kinds of expression appearing in the definition.'],['def-linear-map','def-zero-identity-maps','c1-def-vector-space','c1-thm-scalar-zero'],'3.3',52,'example')
s.r('lem-polynomial-products','Products and substitutions of polynomial functions',r'''If $p,q\in\Poly(\F)$, the pointwise product $pq$ and the composite function $p\circ q$ are polynomial functions.''',r'''Write $p(z)=\sum_{j=0}^m a_jz^j$ and $q(z)=\sum_{k=0}^n b_kz^k$. Finite distributivity and scalar power laws give
\[(pq)(z)=\sum_{j=0}^m\sum_{k=0}^n a_jb_kz^{j+k}.\]
Grouping terms with the same exponent expresses this as a finite scalar combination of powers, so it is polynomial. The constant function $1$ is polynomial; induction using product closure makes every power $q^j$ polynomial. Thus $p(q(z))=\sum_{j=0}^m a_jq(z)^j$ is polynomial by closure under addition and scalar multiplication. This argument includes zero and constant polynomials.''',2,15,[r'Expand a product using finite sums, and then treat substitution as a sum of powers.'],['c2-def-polynomial','c2-thm-polynomial-subspace','c1-thm-complex-laws','c1-lem-scalar-powers'],page=53,kind='lemma')
s.d('def-polynomial-integral','Integration notation for polynomial examples',r'''For a real polynomial $p(x)=\sum_{j=0}^m a_jx^j$, define
\[\int_0^1p(x)\,dx=\sum_{j=0}^m\frac{a_j}{j+1}.\]
Coefficient uniqueness ensures that this value does not depend on adding trailing zero coefficients. This specifies the integral functional on polynomials; no integration of more general functions is needed here.''',page=53)
s.r('ex-polynomial-differentiation','Differentiation is linear on polynomials',r'''The map $D:\Poly(\R)\to\Poly(\R)$ defined by $Dp=p'$ is linear.''',r'''By the polynomial differentiation rule, if $p(x)=\sum_{j=0}^m a_jx^j$, then $p'(x)=\sum_{j=1}^m ja_jx^{j-1}$, a polynomial. Thus the map has the asserted domain and target. Write $p$ and $q$ with coefficient lists $a_j,b_j$ padded to the same length. The derivative of $p+q$ has coefficients $j(a_j+b_j)=ja_j+jb_j$, so $D(p+q)=Dp+Dq$. The derivative of $cp$ has coefficients $jca_j=cja_j$, so $D(cp)=cDp$. When $m=0$, each displayed derivative is the empty sum, meaning zero, and the same identities hold.''',1,10,[r'Use the coefficient formula for the derivative.'],['def-linear-map','c2-def-polynomial','c2-lem-polynomial-coefficients','c2-thm-polynomial-differentiation'],'3.3',53,'example')
s.r('ex-polynomial-integration','Integration is a linear functional',r'''The map $J:\Poly(\R)\to\R$ given by $Jp=\int_0^1p(x)\,dx$ is linear.''',r'''After padding coefficient lists to the same length, the coefficient of $x^j$ in $p+q$ is $a_j+b_j$. Hence $J(p+q)=\sum_j(a_j+b_j)/(j+1)=Jp+Jq$. For $c\in\R$, the coefficients of $cp$ are $ca_j$, so $J(cp)=\sum_jca_j/(j+1)=cJp$. The finite sums are real numbers, so this also verifies the target of the map.''',1,10,[r'Use the defining finite sum for this integral.'],['def-linear-map','def-polynomial-integral','c2-def-polynomial'],'3.3',53,'example')
s.r('ex-polynomial-multiplication','Multiplication by a fixed polynomial is linear',r'''For fixed $q\in\Poly(\F)$, define $M_qp=qp$. Then $M_q\in\Lin(\Poly(\F))$. In particular, multiplication by $x^2$ is a linear map on $\Poly(\R)$.''',r'''Product closure shows $qp\in\Poly(\F)$. At any scalar $z$, $q(z)(p(z)+r(z))=q(z)p(z)+q(z)r(z)$ and $q(z)(ap(z))=a(q(z)p(z))$. These pointwise equalities give $M_q(p+r)=M_qp+M_qr$ and $M_q(ap)=aM_qp$. Taking $q(x)=x^2$ gives the special case.''',1,10,[r'Check the two identities by evaluating them at a scalar argument.'],['def-linear-map','lem-polynomial-products','c2-def-polynomial','c1-thm-complex-laws'],'3.3',53,'example')
s.r('ex-backward-shift','The backward shift is linear',r'''The map $B:\F^\infty\to\F^\infty$ defined by $(Bx)_k=x_{k+1}$ is linear.''',r'''It returns a scalar sequence. For every $k\in\N$, $[B(x+y)]_k=x_{k+1}+y_{k+1}=(Bx)_k+(By)_k$, and $[B(ax)]_k=ax_{k+1}=a(Bx)_k$. Equality at every index proves $B(x+y)=Bx+By$ and $B(ax)=aBx$.''',1,10,[r'Compare the $k$th entries.'],['def-linear-map','c1-def-sequences','c1-ex-sequence-space'],'3.3',53,'example')
s.r('ex-coordinate-linear-map','A map between different coordinate spaces',r'''The map $T:\R^3\to\R^2$ given by $T(x,y,z)=(2x-y+3z,7x+5y-6z)$ is linear.''',r'''For $u=(x,y,z)$ and $v=(r,s,t)$, distributing in each coordinate gives
\[T(u+v)=(2x-y+3z+2r-s+3t,7x+5y-6z+7r+5s-6t)=Tu+Tv.\]
For $a\in\R$, factoring $a$ from each coordinate gives $T(au)=(a(2x-y+3z),a(7x+5y-6z))=aTu$. Thus the two linearity conditions hold.''',1,10,[r'Expand the two output coordinates separately.'],['def-linear-map','c1-def-coordinate-addition','c1-def-coordinate-scaling'],'3.3',53,'example')
s.r('thm-coordinate-linear-maps','Coordinate description of every linear map',r'''Let $m,n\ge0$ and choose scalars $A_{jk}$ for $1\le j\le m$, $1\le k\le n$. The formula
\[(Tx)_j=\sum_{k=1}^n A_{jk}x_k\]
defines a linear map $T:\F^n\to\F^m$. Conversely, every such linear map has this form, with $A_{jk}$ the $j$th coordinate of $Te_k$, where $e_k$ are the standard coordinate vectors.''',r'''The formula gives a length-$m$ scalar list for every input. Scalar distributivity gives $[T(x+y)]_j=\sum_kA_{jk}x_k+\sum_kA_{jk}y_k=(Tx)_j+(Ty)_j$ and $[T(ax)]_j=a\sum_kA_{jk}x_k=a(Tx)_j$. Thus the map is linear. Conversely, for a linear $T$ and $n>0$, use $x=\sum_kx_ke_k$. Repeated additivity and homogeneity give $Tx=\sum_kx_kTe_k$, whose $j$th coordinate has the claimed form. If $n=0$, the domain contains only zero. Homogeneity gives $T0=T(0\cdot0)=0\cdot T0=0$, so the empty-sum formula also holds. If $m=0$, all outputs are the empty list and both assertions remain valid.''',2,20,[r'For the converse, write the input using standard coordinate vectors.'],['def-linear-map','c2-ex-standard-spanning','c1-def-coordinate-addition','c1-def-coordinate-scaling','c1-thm-zero-scalar'],'3.3',53)
s.r('ex-polynomial-composition','Substitution by a fixed polynomial is linear',r'''For fixed $q\in\Poly(\R)$, the map $C_q:\Poly(\R)\to\Poly(\R)$ given by $(C_qp)(x)=p(q(x))$ is linear.''',r'''Substitution closure proves that $C_qp$ is polynomial. For every $x\in\R$, $(C_q(p+r))(x)=p(q(x))+r(q(x))=(C_qp+C_qr)(x)$, and $(C_q(ap))(x)=ap(q(x))=(aC_qp)(x)$. These pointwise identities prove linearity.''',1,10,[r'Only the outer polynomial varies; the substituted polynomial stays fixed.'],['def-linear-map','lem-polynomial-products','c1-def-function-space'],'3.3',53,'example')
s.r('thm-linear-map-basis','Prescribing a linear map on a basis',r'''If $v_1,\ldots,v_n$ is a basis of $V$ and $w_1,\ldots,w_n$ are any vectors of $W$, there is exactly one $T\in\Lin(V,W)$ with $Tv_k=w_k$ for every $k$.''',r'''Every $v\in V$ has unique coefficients $a_k$ with $v=\sum_ka_kv_k$. Define $Tv=\sum_ka_kw_k$. Uniqueness of the coefficients makes this a well-defined function into $W$. The coefficients of $u+v$ are the sums of the respective coefficients, because the corresponding expansion follows from distributivity and is unique. Those of $cv$ are $ca_k$. Consequently $T(u+v)=Tu+Tv$ and $T(cv)=cTv$. Taking one coefficient equal to $1$ and all others zero proves $Tv_k=w_k$. Any other linear map $S$ with these basis values must satisfy $Sv=\sum_ka_kSv_k=\sum_ka_kw_k=Tv$ by repeated additivity and homogeneity. If $n=0$, $V=\{0\}$, the definition is $T0=0$, and every linear $S$ satisfies $S0=S(0\cdot0)=0\cdot S0=0$. Thus existence and uniqueness include the zero space.''',2,20,[r'Use the unique coefficient list of a vector to define its image.',r'Check well-definedness before checking linearity.'],['def-linear-map','c2-def-basis','c2-thm-basis-coordinates','c1-def-vector-space','c1-thm-zero-scalar'],'3.4',54)
s.d('def-map-operations','Addition and scalar multiplication of maps',r'''For $S,T\in\Lin(V,W)$ and $a\in\F$, define functions by $(S+T)v=Sv+Tv$ and $(aT)v=a(Tv)$.''','3.5',55)
s.r('thm-linear-map-space','Linear maps form a vector space',r'''With these operations, $\Lin(V,W)$ is a vector space over $\F$. Its zero vector is the zero map, and the map $v\mapsto-Tv$ is the additive inverse of $T$.''',r'''First verify closure. For $u,v\in V$, $(S+T)(u+v)=Su+Sv+Tu+Tv=(Su+Tu)+(Sv+Tv)$, using commutativity and associativity in $W$. For $b\in\F$, $(S+T)(bv)=bSv+bTv=b(S+T)v$. Also $(aT)(u+v)=aTu+aTv$ and $(aT)(bv)=a(bTv)=b(aTv)$, so $S+T$ and $aT$ are linear. The zero map is linear by the earlier example. Evaluating at any $v\in V$ gives
\[\begin{aligned}
(S+T)v&=(T+S)v,\\
((R+S)+T)v&=Rv+(Sv+Tv)=(R+(S+T))v,\\
((ab)T)v&=(ab)Tv=a(bTv)=(a(bT))v,\\
(1T)v&=Tv,\\
(a(S+T))v&=aSv+aTv=(aS+aT)v,\\
((a+b)T)v&=aTv+bTv=(aT+bT)v.
\end{aligned}\]
Each equality is a vector-space identity in $W$, so equality of functions proves all six corresponding axioms. Finally $(T+0)v=Tv$ and $(T+(-1)T)v=Tv+(-Tv)=0_W$. Closure already makes $(-1)T$ linear, and the negative-one identity in $W$ identifies it with the stated inverse map. Thus the identity and inverse axioms also hold.''',2,20,[r'First prove the pointwise operations preserve linearity.',r'Check the vector-space axioms by evaluating at an arbitrary input.'],['def-linear-map','def-linear-map-space','def-map-operations','ex-zero-identity-linear','c1-def-vector-space','c1-thm-negative-one'],'3.6',55)
s.d('def-map-composition','Products of linear maps',r'''For $T\in\Lin(U,V)$ and $S\in\Lin(V,W)$, the product $ST$ denotes the composite function $u\mapsto S(Tu)$. The rightmost map is applied first.''','3.7',55)
s.r('lem-composition-linear','Composition preserves linearity',r'''For $T\in\Lin(U,V)$ and $S\in\Lin(V,W)$, the composite $ST$ belongs to $\Lin(U,W)$.''',r'''The image $Tu$ lies in the domain of $S$, so composition is defined. For $u,v\in U$, $(ST)(u+v)=S(Tu+Tv)=S(Tu)+S(Tv)$. For $a\in\F$, $(ST)(au)=S(aTu)=aS(Tu)$. These are the linearity identities.''',1,10,[r'Apply linearity of the inner map and then the outer map.'],['def-linear-map','def-map-composition'],page=55,kind='lemma')
s.r('thm-composition-laws','Associativity, identities, and distributivity of composition',r'''Whenever the domains and targets match, composition of linear maps is associative and satisfies $TI_V=I_WT=T$ for $T:V\to W$. If $T,T_1,T_2:U\to V$ and $S,S_1,S_2:V\to W$ are linear, then $(S_1+S_2)T=S_1T+S_2T$ and $S(T_1+T_2)=ST_1+ST_2$.''',r'''At an input $u$, both $((AB)C)u$ and $(A(BC))u$ equal $A(B(Cu))$. Thus composition is associative as an equality of functions. For $v\in V$, $(TI_V)v=T(v)$ and $(I_WT)v=Tv$, proving both identity formulas. Finally, for $u\in U$, $((S_1+S_2)T)u=S_1(Tu)+S_2(Tu)=(S_1T+S_2T)u$ by pointwise addition. Also $(S(T_1+T_2))u=S(T_1u+T_2u)=S(T_1u)+S(T_2u)=(ST_1+ST_2)u$, this time using additivity of $S$. Agreement at every input proves the assertions.''',2,15,[r'Evaluate both sides at the same vector; distinguish which distributive identity uses linearity.'],['def-map-composition','lem-composition-linear','def-map-operations','def-zero-identity-maps','def-linear-map'],'3.8',56)
s.r('ex-noncommuting-maps','Differentiation and multiplication need not commute',r'''On $\Poly(\R)$, let $D$ be differentiation and let $M=M_{x^2}$. Then
\[(DM)p=x^2p'+2xp,\qquad (MD)p=x^2p',\]
and $DM\ne MD$.''',r'''For $p(x)=\sum_{j=0}^m a_jx^j$, multiplication gives $Mp=\sum_{j=0}^m a_jx^{j+2}$, and hence $DMp=\sum_{j=0}^m(j+2)a_jx^{j+1}$ by polynomial differentiation. Meanwhile $MDp=\sum_{j=1}^mja_jx^{j+1}$. Subtracting gives $DMp-MDp=2\sum_{j=0}^ma_jx^{j+1}=2xp$. The formula for $MDp$ is its definition. At $p=1$, the two outputs are $2x$ and zero, which differ at $x=1$. Therefore the maps are unequal.''',2,15,[r'Compute the two compositions on monomials or compare them first on a constant.'],['def-map-composition','ex-polynomial-differentiation','ex-polynomial-multiplication','c2-thm-polynomial-differentiation','c2-def-polynomial'],'3.9',56,'example')
s.r('thm-linear-zero','Linear maps preserve the zero vector',r'''Every linear map $T:V\to W$ satisfies $T0_V=0_W$.''',r'''Additivity gives $T0_V=T(0_V+0_V)=T0_V+T0_V$. Because also $T0_V=T0_V+0_W$, cancellation of $T0_V$ in $W$ gives $0_W=T0_V$.''',1,10,[r'Apply additivity to $0_V+0_V$.'],['def-linear-map','c1-lem-vector-cancellation'],'3.10',56)
s.r('ex-affine-not-linear','Affine formulas and linear maps',r'''For $m,b\in\R$, the function $f:\R\to\R$ given by $f(x)=mx+b$ is linear exactly when $b=0$.''',r'''If $f$ is linear, preservation of zero gives $b=f(0)=0$. Conversely, when $b=0$, $f(x+y)=m(x+y)=mx+my=f(x)+f(y)$ and $f(ax)=max=amx=af(x)$ for real $a,x,y$, so $f$ is linear.''',1,10,[r'Test the image of zero first.'],['def-linear-map','thm-linear-zero','c1-foundations'],page=56,kind='example')
s.card('linear-map','def-linear-map',r'What are the two linearity identities?',r'$T(u+v)=Tu+Tv$ and $T(av)=aTv$.')
s.card('basis-values','thm-linear-map-basis',r'What data determine a linear map from a finite-dimensional space?',r'Arbitrary images of the vectors in one basis determine exactly one linear map.')
s.card('map-vector-space','thm-linear-map-space',r'What are the zero vector and additive inverse in $\Lin(V,W)$?',r'The zero map and the map $v\mapsto-Tv$.')
s.card('composition-order','def-map-composition',r'Which map is applied first in $ST$?',r'$T$ is applied first, followed by $S$.')
s.card('composition-noncommuting','ex-noncommuting-maps',r'Give noncommuting maps on polynomial space.',r'Differentiation $D$ and multiplication $M$ by $x^2$: $DM(1)=2x$ but $MD(1)=0$.')
s.card('preserve-zero','thm-linear-zero',r'Why must a linear map take zero to zero?',r'Additivity gives $T0=T0+T0$; cancel one copy of $T0$.')
s.card('affine-test','ex-affine-not-linear',r'When is $x\mapsto mx+b$ linear?',r'Exactly when $b=0$.')
s.write()
