from common import Section
s=Section('7c')
s.p('intro-positive','Positivity and square roots',r'''Throughout this section, $V$ is a finite-dimensional inner product space over $\R$ or $\C$. Spectral theory lets us compare positive operators with nonnegative real numbers and construct their distinguished square roots.''',251)
s.d('def-positive','Positive operators',r'''An operator $T\in\Lin(V)$ is positive if it is self-adjoint and $\ip{Tv}{v}\ge0$ for every $v\in V$. This inequality requires the inner-product value to be real. The term positive includes the zero operator; another name is positive semidefinite.''','7.34',251)
s.r('thm-complex-positivity-test','Positivity from quadratic values over the complex field',r'''Over $\C$, the condition $\ip{Tv}{v}\ge0$ for every $v$ already implies that $T$ is positive.''',r'''All the stated quadratic values are real, so the complex quadratic-value criterion makes $T$ self-adjoint. Together with the assumed nonnegativity, this is exactly the definition of positivity.''',1,10,[r'Use the real-quadratic-value criterion for self-adjointness.'],['def-positive','thm-self-adjoint-quadratic'],page=251)
s.r('ex-positive-coordinate','A positive coordinate operator',r'''On $\F^2$ with the standard inner product, $T(x,y)=(2x-y,-x+y)$ is positive.''',r'''The coordinate formula defines a linear operator. Its standard matrix is real symmetric, hence equals its conjugate transpose. Because the standard basis is orthonormal, this proves self-adjointness. Direct expansion gives
\[\ip{T(x,y)}{(x,y)}=2|x|^2-x\overline y-y\overline x+|y|^2=|x-y|^2+|x|^2\ge0.\]
The last equality follows by multiplying $(x-y)(\overline x-\overline y)$. Thus both conditions for positivity hold.''',1,10,[r'Check self-adjointness and express the quadratic value as a sum of squared moduli.'],['def-positive','thm-self-adjoint-tests','c3-thm-coordinate-linear-maps','c6-thm-standard-inner-product','c4-thm-complex-properties'],'7.35(a)',251,'example')
s.r('ex-positive-projection','Orthogonal projections are positive',r'''For any subspace $U\subseteq V$, the orthogonal projection $P_U$ is positive.''',r'''Write $v=P_Uv+v_\perp$ and $w=P_Uw+w_\perp$, with the remainder vectors in $U^\perp$. Orthogonality gives
\[\ip{P_Uv}{w}=\ip{P_Uv}{P_Uw}=\ip{v}{P_Uw}.\]
The inner-product test therefore makes $P_U$ self-adjoint. Taking $w=v$ gives $\ip{P_Uv}{v}=\|P_Uv\|^2\ge0$, so it is positive. The decomposition theorem applies because $U$ is finite-dimensional as a subspace of $V$, including $U=\{0\}$.''',2,15,[r'Decompose both inputs into their $U$ and $U^\perp$ components.'],['def-positive','thm-self-adjoint-tests','c6-def-orthogonal-projection','c6-thm-orthogonal-direct-sum','c6-thm-inner-product-properties','c2-thm-subspaces-finite'],'7.35(b)',251,'example')
s.r('ex-positive-quadratic','Positive quadratics in a self-adjoint operator',r'''If $T$ is self-adjoint and $b,c\in\R$ satisfy $b^2<4c$, then $T^2+bT+cI$ is positive. Its quadratic value is strictly positive at every nonzero vector.''',r'''The adjoint rules show that $T^2+bT+cI$ is self-adjoint, because $T^*=T$ and the coefficients are real. Put $A=T+(b/2)I$, which is also self-adjoint. Completing the square gives
\[T^2+bT+cI=A^2+(c-b^2/4)I.\]
For any $v$, self-adjointness of $A$ gives $\ip{A^2v}{v}=\ip{Av}{Av}=\|Av\|^2$. Thus the quadratic value of the displayed operator is $\|Av\|^2+(c-b^2/4)\|v\|^2$. Both terms are nonnegative, and for $v\ne0$ the second is positive because $c-b^2/4>0$. This proves both conclusions.''',2,20,[r'Complete the square in the operator and move one self-adjoint factor across the inner product.'],['def-positive','thm-adjoint-properties','thm-self-adjoint-tests','c6-thm-norm-properties','c3-thm-composition-laws'],'7.35(c)',251,'example')
s.d('def-operator-square-root','Square roots of an operator',r'''A square root of $T\in\Lin(V)$ is an operator $R\in\Lin(V)$ with $R^2=T$. This definition alone imposes no positivity or self-adjointness condition.''','7.36',251)
s.r('ex-shift-square-root','A square root supplied by a coordinate shift',r'''The operator $R(x,y,z)=(y,z,0)$ is a square root of $T(x,y,z)=(z,0,0)$ on $\F^3$.''',r'''Both formulas are linear by the coordinate characterization. Applying $R$ twice gives $R^2(x,y,z)=R(y,z,0)=(z,0,0)=T(x,y,z)$ for every input. Therefore $R^2=T$, which is the square-root condition.''',1,10,[r'Compose the shift with itself.'],['def-operator-square-root','c3-thm-coordinate-linear-maps','c3-def-map-composition'],'7.37',251,'example')
s.r('thm-positive-characterizations','Equivalent descriptions of a positive operator',r'''For $T\in\Lin(V)$ the following are equivalent:
\begin{enumerate}
\item $T$ is positive.
\item $T$ is self-adjoint and all its eigenvalues are nonnegative.
\item Some orthonormal basis gives a diagonal matrix for $T$ with nonnegative diagonal entries.
\item $T$ has a positive square root.
\item $T$ has a self-adjoint square root.
\item $T=R^*R$ for some $R\in\Lin(V)$.
\end{enumerate}''',r'''We prove a cycle of implications. Suppose first $T$ is positive. It is self-adjoint by definition. For an eigenvector $v$ with eigenvalue $\lambda$, $0\le\ip{Tv}{v}=\lambda\|v\|^2$, and $\|v\|^2>0$. Thus $\lambda$ is nonnegative, proving the second condition.
A self-adjoint operator has an orthonormal eigenbasis: use the real spectral theorem over $\R$, and self-adjointness implies normality so the complex spectral theorem applies over $\C$. Under the second condition its eigenvalues are nonnegative, so this basis gives the third condition.
Assume the third condition, with $Te_j=\lambda_je_j$ and $\lambda_j\ge0$. Prescribe $Re_j=\sqrt{\lambda_j}e_j$ on this basis. The basis prescription theorem gives a linear operator. Its matrix is real diagonal in an orthonormal basis, so $R$ is self-adjoint. If $v=\sum_ja_je_j$, expansion yields $\ip{Rv}{v}=\sum_j\sqrt{\lambda_j}|a_j|^2\ge0$. Hence $R$ is positive. Furthermore $R^2e_j=\lambda_je_j=Te_j$ on every basis vector, so $R^2=T$. This proves the fourth condition.
Every positive operator is self-adjoint, so the fourth implies the fifth. If $R$ is a self-adjoint square root, then $T=R^2=R^*R$, proving the sixth. Finally suppose $T=R^*R$. The adjoint rules give $T^*=(R^*R)^*=R^*(R^*)^*=R^*R=T$. The adjoint identity gives $\ip{Tv}{v}=\ip{R^*Rv}{v}=\ip{Rv}{Rv}=\|Rv\|^2\ge0$, proving positivity and completing the cycle. If $V=\{0\}$, all bases and diagonal lists used here are empty and all operators coincide with zero, so every construction and implication still applies.''',3,45,[r'Use the spectral theorem to pass from eigenvalue information to an orthonormal diagonal matrix.',r'Take nonnegative scalar square roots on an eigenbasis.',r'For the last implication, calculate the quadratic value of $R^*R$.'],['def-positive','def-operator-square-root','thm-adjoint-properties','def-adjoint','thm-self-adjoint-tests','thm-self-adjoint-normal','thm-real-spectral','thm-complex-spectral','c3-thm-linear-map-basis','c6-thm-inner-product-properties','c6-thm-norm-properties','c1-foundations'],'7.38',252)
s.r('thm-positive-square-root-unique','Uniqueness of the positive square root',r'''Every positive operator has exactly one positive square root. If $Tv=\lambda v$, that square root satisfies $Rv=\sqrt\lambda v$ for every such eigenvector.''',r'''Existence is one of the equivalent positivity conditions. Let $R$ be any positive square root, and let $v\ne0$ satisfy $Tv=\lambda v$. Positivity gives $\lambda\ge0$. The characterization applied to $R$ supplies an orthonormal eigenbasis $e_1,\ldots,e_n$ with $Re_j=\mu_je_j$ and $\mu_j\ge0$. Write $v=\sum_ja_je_j$. The identity $R^2v=Tv=\lambda v$ and basis independence imply $a_j(\mu_j^2-\lambda)=0$ for every $j$. If $a_j\ne0$, then $\mu_j^2=\lambda$, and nonnegativity makes $\mu_j=\sqrt\lambda$. Therefore
\[Rv=\sum_ja_j\mu_je_j=\sqrt\lambda\sum_ja_je_j=\sqrt\lambda v.\]
This proves the stated action on every eigenvector of $T$, regardless of which positive square root was chosen. Since $T$ has an eigenvector basis by the positivity characterization, any two positive square roots agree on a basis and are equal. On the zero space there is only one operator, which is its own positive square root, so uniqueness holds there as well.''',3,35,[r'Expand an eigenvector of $T$ in an orthonormal eigenbasis of a proposed positive square root.',r'Nonnegative scalar square roots are unique.'],['thm-positive-characterizations','def-operator-square-root','c2-thm-basis-coordinates','c3-thm-linear-map-basis','c1-foundations'],'7.39',253)
s.r('ex-many-square-roots','The identity can have infinitely many square roots',r'''If $\dim V\ge2$, the identity operator has infinitely many square roots, although its unique positive square root is itself.''',r'''Choose a basis $v_1,\ldots,v_n$ with $n\ge2$. For each real $t$ prescribe $R_tv_1=v_1$, $R_tv_2=tv_1-v_2$, and $R_tv_j=v_j$ for $j\ge3$. These values define a linear operator. Applying it twice gives $R_t^2v_1=v_1$, $R_t^2v_2=tv_1-(tv_1-v_2)=v_2$, and $R_t^2v_j=v_j$ at all remaining indices. Thus $R_t^2=I$. Distinct $t$ give different values on $v_2$, hence different operators, and there are infinitely many real choices. The identity is self-adjoint and has quadratic values $\|v\|^2\ge0$, so it is positive and is its own square root. The positive-square-root uniqueness theorem therefore singles out $I$ among all these square roots.''',2,20,[r'Construct an involution on two basis vectors with a freely chosen scalar.'],['def-operator-square-root','def-positive','thm-adjoint-properties','thm-positive-square-root-unique','c2-thm-basis-existence','c3-thm-linear-map-basis'],page=253,kind='example')
s.d('def-positive-square-root','The positive square root notation',r'''For a positive operator $T$, write $\sqrt T$ for its unique positive square root.''','7.40',253)
s.r('ex-positive-square-root-matrices','Two explicit positive square roots',r'''On $\R^2$ let $S(x,y)=(x,2y)$ and $T(x,y)=(x+y,x+y)$. Both are positive, and
\[\sqrt S(x,y)=(x,\sqrt2y),\qquad\sqrt T(x,y)=\frac1{\sqrt2}(x+y,x+y).\]''',r'''Both standard matrices are real symmetric, hence the operators are self-adjoint. Their quadratic values are $x^2+2y^2$ and $(x+y)^2$, respectively, which are nonnegative. Thus both are positive. The proposed square root of $S$ is real diagonal, hence self-adjoint, with nonnegative quadratic value $x^2+\sqrt2y^2$. Its square is $S$ by direct substitution. For the second formula put $R=T/\sqrt2$. Its matrix is real symmetric and its quadratic value is $(x+y)^2/\sqrt2\ge0$, so it is positive. Direct composition gives $T^2(x,y)=2(x+y,x+y)=2T(x,y)$, hence $R^2=T$. Uniqueness of positive square roots identifies both displayed operators as the designated square roots.''',2,20,[r'Check both the square and positivity of each proposed answer.'],['def-positive','def-positive-square-root','thm-positive-square-root-unique','thm-self-adjoint-tests','c6-thm-standard-inner-product','c3-thm-coordinate-linear-maps'],'7.41',254,'example')
s.r('thm-positive-zero','A zero quadratic value detects the kernel of a positive operator',r'''For a positive operator $T$ and any $v$,
\[\ip{Tv}{v}=0\quad\Longleftrightarrow\quad Tv=0.\]''',r'''Write $R=\sqrt T$, so $R^*=R$ and $R^2=T$. Then
\[\ip{Tv}{v}=\ip{R^2v}{v}=\ip{Rv}{Rv}=\|Rv\|^2.\]
If this is zero, norm definiteness gives $Rv=0$, hence $Tv=R(Rv)=R0=0$ by linearity. Conversely if $Tv=0$, its inner product with $v$ is zero by the zero inner-product identity. This proves both directions, including the zero vector.''',2,15,[r'Express the quadratic value as a squared norm involving the positive square root.'],['def-positive-square-root','thm-positive-square-root-unique','def-positive','thm-self-adjoint-tests','c6-thm-norm-properties','c6-thm-inner-product-properties','c3-thm-linear-zero'],'7.43',254)
s.card('positive','def-positive',r'What are the two requirements for positivity?',r'Self-adjointness and $\ip{Tv}{v}\ge0$ for every vector.')
s.card('positive-eigenvalues','thm-positive-characterizations',r'How do eigenvalues characterize positivity for a self-adjoint operator?',r'All eigenvalues must be nonnegative.')
s.card('positive-factorization','thm-positive-characterizations',r'What adjoint factorization characterizes positivity?',r'$T=R^*R$ for some operator $R$.')
s.card('square-root-positive','thm-positive-square-root-unique',r'Which square root of a positive operator is unique?',r'Its positive square root; arbitrary square roots need not be unique.')
s.card('square-root-eigenvectors','thm-positive-square-root-unique',r'How does $\sqrt T$ act on an eigenvector of positive $T$ with eigenvalue $\lambda$?',r'It multiplies the vector by the nonnegative scalar $\sqrt\lambda$.')
s.card('positive-zero','thm-positive-zero',r'For positive $T$, what does $\ip{Tv}{v}=0$ imply?',r'$Tv=0$.')
s.write()
