from common import Section
s=Section('1a')
s.p('intro-coordinates','Scalars and coordinates',r'''We begin with numbers and finite ordered lists. Coordinate calculations will supply the model for the abstract vector-space axioms in the next section.''',2)
s.note('foundations','Foundational conventions',r'''We assume elementary set and function notation, equality, finite sums and products, induction on nonnegative integers, and the ordered-field laws of $\R$. In particular, real addition and multiplication are associative and commutative, multiplication distributes over addition, $0\ne1$, additive inverses exist, and every nonzero real number has an inverse; squares are nonnegative and the square of a nonzero real number is positive. We use $\N=\{1,2,\ldots\}$, the usual real order, and the existence of a nonnegative square root of each nonnegative real number. These are foundational assumptions, taken on faith rather than proof tasks in this linear algebra module.''',2)
s.d('def-complex','Complex numbers and their operations',r'''A complex number is a pair $(a,b)$ of real numbers, written $a+bi$. Equality means equality of both coordinates. Define
\[(a+bi)+(c+di)=(a+c)+(b+d)i,\qquad (a+bi)(c+di)=(ac-bd)+(ad+bc)i.\]
The set of such pairs is $\C$; identify $a+0i$ with $a\in\R$ and write $i=0+1i$.''','1.1',2)
s.r('ex-complex-product','Computing a complex product',r'''Using the defining operations, prove $i^2=-1$ and $(2+3i)(4+5i)=-7+22i$.''',r'''For $i^2$, the real coordinate is $0\cdot0-1\cdot1=-1$ and the imaginary coordinate is $0\cdot1+1\cdot0=0$. For the second product the real coordinate is $2\cdot4-3\cdot5=-7$, and the imaginary coordinate is $2\cdot5+3\cdot4=22$. Equality of pairs gives both assertions.''',1,10,[r'Use the formula defining multiplication, without assuming distributivity on $\C$.'],['foundations','def-complex'],'1.2',2,'example')
s.r('thm-complex-laws','Associativity, commutativity, identities, and distributivity',r'''Complex addition and multiplication are commutative and associative, $z+0=z$ and $z1=z$, and $z(w+u)=zw+zu$ for all $z,w,u\in\C$.''',r'''Write $z=a+bi$, $w=c+di$, and $u=e+fi$, with real coordinates. The coordinates of $z+w$ are $(a+c,b+d)$, unchanged when the two pairs are exchanged. Those of $zw$ are $(ac-bd,ad+bc)$, which equal $(ca-db,cb+da)$ by the real field laws. Addition of three pairs gives $(a+c+e,b+d+f)$ under either grouping.
For multiplication, the coordinates of $(zw)u$ are
\[((ac-bd)e-(ad+bc)f,\ (ac-bd)f+(ad+bc)e).\]
After real distributivity these are
\[(ace-bde-adf-bcf,\ acf-bdf+ade+bce).\]
The coordinates of $z(wu)$ are $(a(ce-df)-b(cf+de),a(cf+de)+b(ce-df))$, whose expansions have exactly the same real terms. Thus multiplication is associative. Substituting $(0,0)$ in the addition formula and $(1,0)$ in the multiplication formula gives the identity laws. Finally, the coordinates of $z(w+u)$ are $(a(c+e)-b(d+f),a(d+f)+b(c+e))$; real distributivity rewrites this pair as $(ac-bd,ad+bc)+(ae-bf,af+be)$, the pair for $zw+zu$.''',2,20,[r'Compare the two real coordinates of each expression.',r'For multiplication of three numbers, expand both groupings using real arithmetic.'],['foundations','def-complex'],'1.3',3)
s.r('thm-complex-inverses','Existence and uniqueness of scalar inverses',r'''Every $z=a+bi\in\C$ has a unique additive inverse. Every nonzero $z$ has a unique multiplicative inverse; the respective pairs are $(-a)+(-b)i$ and
\[\frac{a}{a^2+b^2}+\frac{-b}{a^2+b^2}i.\]''',r'''Adding $(-a)+(-b)i$ to $a+bi$ gives the zero pair. If $z+(c+di)=0$, coordinate equality gives $a+c=0$ and $b+d=0$, so $c=-a$ and $d=-b$. This proves existence and uniqueness of the additive inverse.
If $z\ne0$, at least one of $a,b$ is nonzero, so $D=a^2+b^2>0$. The displayed candidate $t=a/D-(b/D)i$ is defined, and the multiplication formula gives $zt=(a^2+b^2)/D+0i=1$. If $zw=1$ also, associativity and commutativity give $w=1w=(tz)w=t(zw)=t1=t$. Thus the multiplicative inverse is unique.''',2,20,[r'Solve the two coordinate equations for an additive inverse.',r'For a multiplicative inverse, use the positive real denominator $a^2+b^2$.'],['foundations','def-complex','thm-complex-laws'],'1.3',3)
s.note('remark-commutative-product','How to check a scalar identity',r'''The comparison of coordinates in the arithmetic-laws proof also supplies the book's worked verification of commutativity of multiplication (Example 1.4). Equal complex numbers need not have separate real and imaginary parts equal to zero; what matters is that the corresponding parts agree.''',3)
s.d('def-scalar-inverses','Subtraction and division',r'''Write $-z$ for the additive inverse of $z$, and define $w-z=w+(-z)$. For $z\ne0$, write $z^{-1}=1/z$ for its multiplicative inverse and define $w/z=wz^{-1}$.''','1.5',4)
s.d('def-scalars','The scalar field and powers',r'''Throughout the module $\F$ is either $\R$ or $\C$; its elements are called scalars. For a scalar $a$, put $a^0=1$ and define $a^{m+1}=a^ma$ for every nonnegative integer $m$.''','1.6',4)
s.r('lem-scalar-cancellation','Scalar cancellation and zero products',r'''For $a,b,c\in\F$, $a+b=a+c$ implies $b=c$. If $a\ne0$, then $ab=ac$ implies $b=c$. Moreover $a0=0$ and $ab=0$ implies $a=0$ or $b=0$.''',r'''Add the additive inverse of $a$ to the first equation and use associativity to obtain $b=c$. Since $a0=a(0+0)=a0+a0$, additive cancellation in $a0+0=a0+a0$ gives $a0=0$. If $a\ne0$, multiply $ab=ac$ by $a^{-1}$ and use associativity and $a^{-1}a=1$ to obtain $b=c$. In particular, if $ab=0$ and $a\ne0$, then $ab=a0$, so $b=0$. When $a=0$ the stated alternative already holds.''',2,15,[r'Use additive and multiplicative inverses; handle a zero factor separately.'],['foundations','thm-complex-laws','thm-complex-inverses','def-scalar-inverses','def-scalars'])
s.r('lem-scalar-powers','Laws of nonnegative integer powers',r'''For $a,b\in\F$ and nonnegative integers $m,n$, one has $a^{m+n}=a^ma^n$, $(a^m)^n=a^{mn}$, and $(ab)^m=a^mb^m$.''',r'''For fixed $m$, induction on $n$ gives the first formula: at $n=0$ both sides equal $a^m$, and the induction step is $a^{m+n+1}=a^{m+n}a=(a^ma^n)a=a^ma^{n+1}$. For the second formula, the case $n=0$ is $1=1$, and the step is $(a^m)^{n+1}=(a^m)^na^m=a^{mn}a^m=a^{m(n+1)}$, using the first formula. For the third, the case $m=0$ is $1=1$. Commutativity and associativity give $(ab)^{m+1}=a^mb^mab=a^{m+1}b^{m+1}$ from the induction hypothesis.''',2,15,[r'Prove the addition rule for exponents first; then use induction for the other two.'],['foundations','thm-complex-laws','def-scalars'])
s.add('prose','ex-plane-space','Pairs and triples',r'''The plane is modeled by real ordered pairs, and ordinary coordinate space by real ordered triples. Their coordinate sets are denoted by $\R^2$ and $\R^3$.''','1.7',5)
s.d('def-list','Finite ordered lists',r'''A list of length $n\ge0$ has $n$ entries in a specified order. Two lists agree precisely when their lengths agree and each corresponding entry agrees. Repetition is allowed, and the length-zero list is the empty list $()$.''','1.8',5)
s.r('ex-list-set','Order and repetition distinguish lists',r'''The lists $(2,7)$ and $(7,2)$ are different although their sets of entries agree. The lists $(2)$ and $(2,2)$ are different although their sets of entries agree.''',r'''The first two lists have unequal first entries, since $2\ne7$, so they are unequal. Each corresponding set consists of the same two elements, $2$ and $7$. The last two lists have different lengths, so they are unequal; both sets of entries consist only of $2$.''',1,10,[r'List equality checks positions and length; set equality checks membership.'],['foundations','def-list'],'1.9',5,'example')
s.d('def-coordinate-space','Coordinate spaces',r'''For a positive integer $n$, define $\F^n$ to be the set of length-$n$ lists of scalars. If $x=(x_1,\ldots,x_n)$, then $x_j$ is its $j$th coordinate. We also allow $n=0$ when explicitly stated; $\F^0$ then consists of the single empty list.''','1.11',6)
s.r('ex-complex-four','Four complex coordinates',r'''An element of $\C^4$ is a list $(z_1,z_2,z_3,z_4)$ with each $z_j\in\C$; in particular $(i,2,1-i,0)$ belongs to this set.''',r'''The definition of a coordinate space makes its members precisely the length-four lists of complex numbers. The displayed entries are the complex pairs $0+1i$, $2+0i$, $1+(-1)i$, and $0+0i$, respectively. Each pair has real coordinates, so each is complex. Their ordered list has four entries and therefore belongs to $\C^4$.''',1,10,[r'Check the type of each entry and the length of the list.'],['def-coordinate-space','def-complex'],'1.12',6,'example')
s.d('def-coordinate-addition','Coordinate addition',r'''For $x,y\in\F^n$, define $x+y=(x_1+y_1,\ldots,x_n+y_n)$.''','1.13',6)
s.r('thm-coordinate-commutativity','Commutativity of coordinate addition',r'''For $x,y\in\F^n$, $x+y=y+x$.''',r'''For each index $j$ from $1$ to $n$, the $j$th coordinates are $x_j+y_j$ and $y_j+x_j$, which agree by scalar commutativity. Equality of lists proves the result. If $n=0$, both sides are the empty list.''',1,10,[r'Compare coordinates.'],['thm-complex-laws','def-scalars','def-list','def-coordinate-addition'],'1.14',7)
s.d('def-coordinate-zero','Zero vector',r'''The symbol $0\in\F^n$ denotes the list with every coordinate equal to the scalar zero.''','1.15',7)
s.r('ex-coordinate-identity','The zero list is an additive identity',r'''Every $x\in\F^n$ satisfies $x+0=x$.''',r'''The $j$th coordinate of $x+0$ is $x_j+0=x_j$ by the scalar identity law. Hence the lists agree, with the empty-list case automatic from the definition.''',1,10,[r'The scalar zero and zero list have different types; use the coordinate definition.'],['thm-complex-laws','def-coordinate-addition','def-coordinate-zero'],'1.16',7,'example')
s.d('def-coordinate-negative','Coordinate negatives',r'''For $x=(x_1,\ldots,x_n)$, put $-x=(-x_1,\ldots,-x_n)$ and $y-x=y+(-x)$.''','1.17',9)
s.r('lem-coordinate-inverse','Uniqueness of the negative list',r'''For $x\in\F^n$, the only $y\in\F^n$ satisfying $x+y=0$ is $y=-x$.''',r'''The equation is equivalent to $x_j+y_j=0$ for every coordinate $j$. Uniqueness of scalar additive inverses gives $y_j=-x_j$ for each $j$; these choices also satisfy the equations. If $n=0$ there is only one list to choose.''',1,10,[r'Reduce the equation to one scalar equation at a time.'],['thm-complex-inverses','def-coordinate-addition','def-coordinate-zero','def-coordinate-negative'])
s.d('def-coordinate-scaling','Scalar multiplication of a list',r'''For $a\in\F$ and $x\in\F^n$, define $ax=(ax_1,\ldots,ax_n)$.''','1.18',9)
s.r('lem-coordinate-laws','The remaining coordinate identities',r'''For $x,y,z\in\F^n$ and $a,b\in\F$,
\[(x+y)+z=x+(y+z),\quad (ab)x=a(bx),\quad 1x=x,\]
\[a(x+y)=ax+ay,\qquad (a+b)x=ax+bx.\]''',r'''For each coordinate $j$, scalar arithmetic gives $(x_j+y_j)+z_j=x_j+(y_j+z_j)$, $(ab)x_j=a(bx_j)$, $1x_j=x_j$, $a(x_j+y_j)=ax_j+ay_j$, and $(a+b)x_j=ax_j+bx_j$. The last equality follows from scalar distributivity and commutativity. By the definitions, these are exactly the coordinate equalities for the five asserted list equalities. When $n=0$ all expressions are the empty list.''',2,15,[r'Each vector identity is a scalar identity at every coordinate.'],['thm-complex-laws','def-scalars','def-coordinate-addition','def-coordinate-scaling'])
s.d('def-field','Fields',r'''A field is a set with distinct elements $0$ and $1$, addition and multiplication that are associative and commutative, identities $0$ and $1$, additive inverses for all elements, multiplicative inverses for nonzero elements, and distributivity of multiplication over addition. The preceding results show that $\C$ is a field; $\R$ is a field by our foundational assumptions. In this module $\F$ continues to mean only $\R$ or $\C$.''',page=10)
s.card('complex','def-complex',r'How is multiplication of complex pairs defined?',r'$(a+bi)(c+di)=(ac-bd)+(ad+bc)i$.')
s.card('scalar-inverse','thm-complex-inverses',r'What is the reciprocal of $a+bi\ne0$?',r'$a/(a^2+b^2)-[b/(a^2+b^2)]i$; the denominator is positive.')
s.card('list','def-list',r'What two features distinguish a finite list from a set?',r'Order and repetitions matter for lists; equality also requires equal lengths.')
s.card('coordinate-space','def-coordinate-space',r'What is $\F^n$?',r'The set of length-$n$ lists of elements of $\F$, where $\F$ is $\R$ or $\C$.')
s.card('coordinate-proof','lem-coordinate-laws',r'How do you prove an identity of coordinate vectors?',r'Check that the two scalar expressions in each coordinate agree.')
s.card('field','def-field',r'Which elements of a field must have multiplicative inverses?',r'Every element except $0$.')
s.write()
