from common import Section

s = Section('3c')

s.p(
    'intro-matrices',
    'Recording a linear map in coordinates',
    r'''Once bases have been chosen, a linear map can be recorded by
    a rectangular array of scalars. We develop the arithmetic of these
    arrays from the corresponding operations on maps, then compare
    the dimensions generated by their rows and columns. All matrix
    dimensions in this section may be zero; empty sums mean zero.''',
    69,
)

s.d(
    'def-matrix',
    'Matrices and their entries',
    r'''For nonnegative integers $m,n$, an $m$-by-$n$ matrix over
    $\F$ consists of a shape $(m,n)$ and entries $A_{j,k}\in\F$,
    indexed by $1\le j\le m$ and $1\le k\le n$. The first index
    specifies a row and the second specifies a column.
    Matrices are equal when their shapes agree and all corresponding
    entries agree. For a fixed shape with $m=0$ or $n=0$, there is
    exactly one matrix, because there are no entries to choose.''',
    '3.29',
    69,
)

s.r(
    'ex-matrix-entry',
    'Reading an entry',
    r'''For
    \[
    A=\begin{pmatrix}8&4&5-3i\\1&9&7\end{pmatrix},
    \]
    determine $A_{2,3}$ and the shape of $A$.''',
    r'''There are two rows and three columns, so the shape is
    $2$-by-$3$. In the second row, the third entry is $7$.
    Therefore $A_{2,3}=7$.''',
    1,
    10,
    [r'''Read the row index before the column index.'''],
    ['def-matrix'],
    '3.30',
    69,
    'example',
)

s.d(
    'def-map-matrix',
    'The matrix of a linear map',
    r'''Let $v_1,\ldots,v_n$ be an ordered basis of $V$ and
    $w_1,\ldots,w_m$ an ordered basis of $W$. For $T\in\Lin(V,W)$,
    its matrix relative to these bases is the $m$-by-$n$ matrix
    $\Mat(T)$ determined by
    \[
    Tv_k=\sum_{j=1}^m\Mat(T)_{j,k}w_j
    \qquad(1\le k\le n).
    \]
    The coefficients exist and are unique because the $w_j$ form
    a basis. When needed, write
    $\Mat(T,(v_1,\ldots,v_n),(w_1,\ldots,w_m))$ to specify both
    bases. Coordinate spaces use their standard bases unless other
    bases are stated, and $\Poly_d(\F)$ uses $1,x,\ldots,x^d$.
    All formulas comparing matrices of maps use the same chosen
    basis for each space involved.''',
    '3.31',
    69,
)

s.r(
    'ex-coordinate-map-matrix',
    'A matrix with two columns and three rows',
    r'''For
    \[
    T:\F^2\to\F^3,\qquad
    T(x,y)=(x+3y,2x+5y,7x+9y),
    \]
    prove that $T$ is linear and that, in the standard bases,
    \[
    \Mat(T)=\begin{pmatrix}1&3\\2&5\\7&9\end{pmatrix}.
    \]''',
    r'''Each output coordinate is a fixed linear combination of
    the input coordinates, so the coordinate description theorem
    proves that $T$ is linear. Applying $T$ to the two standard
    domain basis vectors gives
    \[
    T(1,0)=(1,2,7),\qquad T(0,1)=(3,5,9).
    \]
    In the standard basis of $\F^3$, the coefficients of these
    vectors are their respective coordinates. They form the first
    and second columns of $\Mat(T)$, giving the displayed matrix.''',
    1,
    10,
    [r'''Apply the map to each domain basis vector, keeping the resulting coefficient lists as columns.'''],
    ['thm-coordinate-linear-maps', 'def-map-matrix', 'c2-ex-coordinate-dimension'],
    '3.32',
    70,
    'example',
)

s.r(
    'ex-differentiation-matrix',
    'The matrix of polynomial differentiation',
    r'''Let $D:\Poly_3(\R)\to\Poly_2(\R)$ be defined by $Dp=p'$.
    This map is linear, and its matrix in the standard polynomial
    bases is
    \[
    \Mat(D)=
    \begin{pmatrix}
    0&1&0&0\\
    0&0&2&0\\
    0&0&0&3
    \end{pmatrix}.
    \]''',
    r'''The polynomial differentiation rule shows that the
    derivative of a polynomial of degree at most $3$ has degree
    at most $2$, or is zero, so the specified target is valid.
    The same rule gives linearity. On the domain basis,
    \[
    D1=0,\qquad Dx=1,\qquad D(x^2)=2x,\qquad D(x^3)=3x^2.
    \]
    Their coefficient lists relative to $1,x,x^2$ are respectively
    $(0,0,0)$, $(1,0,0)$, $(0,2,0)$, and $(0,0,3)$.
    Placing those lists in order as columns gives the asserted matrix.''',
    1,
    10,
    [r'''Differentiate the four domain basis polynomials and express the answers in the target basis.'''],
    [
        'def-map-matrix',
        'def-linear-map',
        'c2-def-polynomial-space',
        'c2-ex-polynomial-dimension',
        'c2-thm-polynomial-differentiation',
    ],
    '3.33',
    70,
    'example',
)

s.d(
    'def-matrix-addition',
    'Addition of matrices',
    r'''For two matrices $A,B$ of the same shape, define their sum
    to have that shape and entries
    \[
    (A+B)_{j,k}=A_{j,k}+B_{j,k}.
    \]
    This addition is defined only for matrices of the same shape.''',
    '3.34',
    71,
)

s.r(
    'thm-matrix-addition',
    'The matrix of a sum of maps',
    r'''For $S,T\in\Lin(V,W)$, with fixed bases of the finite-dimensional
    spaces $V,W$,
    \[
    \Mat(S+T)=\Mat(S)+\Mat(T).
    \]''',
    r'''Write the chosen bases as $v_1,\ldots,v_n$ and
    $w_1,\ldots,w_m$, and put $A=\Mat(S)$, $B=\Mat(T)$.
    For every domain basis vector,
    \[
    (S+T)v_k
    =\sum_{j=1}^m A_{j,k}w_j+\sum_{j=1}^m B_{j,k}w_j
    =\sum_{j=1}^m(A_{j,k}+B_{j,k})w_j.
    \]
    Uniqueness of coefficients in the target basis shows that
    column $k$ of $\Mat(S+T)$ has these entries. Hence the
    corresponding entries of both matrices agree.
    If $n=0$ or $m=0$, both matrices have the same shape with
    no entries, and equality follows from matrix equality.''',
    1,
    10,
    [r'''Expand the image of one domain basis vector under $S+T$.'''],
    [
        'def-map-operations',
        'def-map-matrix',
        'def-matrix-addition',
        'c2-thm-basis-coordinates',
        'c1-def-vector-space',
    ],
    '3.35',
    71,
)

s.d(
    'def-matrix-scaling',
    'Scalar multiplication of matrices',
    r'''For $a\in\F$ and an $m$-by-$n$ matrix $A$, define $aA$
    to have the same shape and entries
    \[
    (aA)_{j,k}=aA_{j,k}.
    \]''',
    '3.36',
    71,
)

s.r(
    'ex-matrix-linear-combination',
    'Computing a linear combination of matrices',
    r'''Compute
    \[
    2\begin{pmatrix}3&1\\-1&5\end{pmatrix}
    +\begin{pmatrix}4&2\\1&6\end{pmatrix}.
    \]''',
    r'''Entrywise multiplication and addition give
    \[
    \begin{pmatrix}
    2\cdot3+4&2\cdot1+2\\
    2(-1)+1&2\cdot5+6
    \end{pmatrix}
    =
    \begin{pmatrix}10&4\\-1&16\end{pmatrix}.
    \]''',
    1,
    10,
    [r'''Perform the scalar operation and addition separately in each position.'''],
    ['def-matrix-addition', 'def-matrix-scaling'],
    '3.37',
    72,
    'example',
)

s.r(
    'thm-matrix-scaling',
    'The matrix of a scalar multiple of a map',
    r'''For $a\in\F$ and $T\in\Lin(V,W)$, using fixed bases,
    \[
    \Mat(aT)=a\Mat(T).
    \]''',
    r'''Put $A=\Mat(T)$ and use bases $v_1,\ldots,v_n$ of $V$
    and $w_1,\ldots,w_m$ of $W$. For each $k$,
    \[
    (aT)v_k=a\sum_{j=1}^m A_{j,k}w_j
    =\sum_{j=1}^m(aA_{j,k})w_j.
    \]
    Uniqueness of target coordinates identifies the entries in
    column $k$ of $\Mat(aT)$ with those of $aA$.
    If either basis is empty, the two matrices have the same
    entry-free shape and hence are equal.''',
    1,
    10,
    [r'''Multiply the basis expansion of $Tv_k$ by the scalar.'''],
    [
        'def-map-operations',
        'def-map-matrix',
        'def-matrix-scaling',
        'c2-thm-basis-coordinates',
        'c1-def-vector-space',
    ],
    '3.38',
    72,
)

s.d(
    'def-matrix-space',
    'The space of matrices of a fixed shape',
    r'''For nonnegative integers $m,n$, denote the set of all
    $m$-by-$n$ matrices over $\F$ by $\F^{m,n}$. Its addition and
    scalar multiplication are the entrywise operations just defined.
    The zero matrix of this shape is denoted by $0_{m,n}$, or simply
    by $0$ when the shape is specified. Its entries are all zero.
    This notation includes the entry-free shapes.''',
    '3.39',
    72,
)

s.r(
    'thm-matrix-space-dimension',
    'The matrix space has dimension equal to the number of entries',
    r'''For all nonnegative integers $m,n$, the space $\F^{m,n}$
    is a vector space over $\F$, and
    \[
    \dim\F^{m,n}=mn.
    \]''',
    r'''The entrywise operations produce matrices of the same shape,
    so they are closed operations. At each position $(j,k)$,
    the scalar field identities give
    \[
    \begin{aligned}
    A_{j,k}+B_{j,k}&=B_{j,k}+A_{j,k},\\
    (A_{j,k}+B_{j,k})+C_{j,k}
      &=A_{j,k}+(B_{j,k}+C_{j,k}),\\
    (ab)A_{j,k}&=a(bA_{j,k}),\\
    1A_{j,k}&=A_{j,k},\\
    a(A_{j,k}+B_{j,k})&=aA_{j,k}+aB_{j,k},\\
    (a+b)A_{j,k}&=aA_{j,k}+bA_{j,k}.
    \end{aligned}
    \]
    Matrix equality therefore gives the corresponding vector-space
    axioms. The zero matrix is an additive identity, and the matrix
    with entries $-A_{j,k}$ is an additive inverse of $A$.
    Hence all vector-space axioms hold.

    When $m,n>0$, let $E^{j,k}$ have entry $1$ in position $(j,k)$
    and zero in every other position. List these matrices with
    $j$ increasing first and, for each $j$, $k$ increasing.
    Every $A$ has the expression
    \[
    A=\sum_{j=1}^m\sum_{k=1}^n A_{j,k}E^{j,k},
    \]
    because the entry in position $(r,s)$ of the sum is $A_{r,s}$.
    A zero linear combination of these matrices has, in position
    $(j,k)$, exactly the coefficient of $E^{j,k}$, so every
    coefficient must vanish. They therefore form a basis with
    $mn$ entries.

    If $m=0$ or $n=0$, the set contains just one matrix, its zero
    matrix, and both operations return that matrix. It is the zero
    vector space and has dimension $0=mn$.''',
    2,
    20,
    [
        r'''Verify the axioms one entry at a time.''',
        r'''Use matrices with exactly one entry equal to $1$ as candidate basis vectors.''',
    ],
    [
        'def-matrix',
        'def-matrix-addition',
        'def-matrix-scaling',
        'def-matrix-space',
        'c1-thm-complex-laws',
        'c1-thm-complex-inverses',
        'c1-def-vector-space',
        'c2-def-basis',
        'c2-def-dimension',
        'c2-lem-zero-dimension',
    ],
    '3.40',
    72,
)

s.d(
    'def-matrix-product',
    'Matrix multiplication',
    r'''For $A\in\F^{m,n}$ and $B\in\F^{n,p}$, define
    $AB\in\F^{m,p}$ by
    \[
    (AB)_{j,k}=\sum_{r=1}^n A_{j,r}B_{r,k}.
    \]
    The number of columns of the first factor must equal the number
    of rows of the second. If this common number is zero, every
    entry of the product is the empty sum and hence is zero.''',
    '3.41',
    73,
)

s.r(
    'ex-rectangular-product',
    'Multiplying rectangular matrices',
    r'''Prove that
    \[
    \begin{pmatrix}1&2\\3&4\\5&6\end{pmatrix}
    \begin{pmatrix}6&5&4&3\\2&1&0&-1\end{pmatrix}
    =
    \begin{pmatrix}10&7&4&1\\26&19&12&5\\42&31&20&9\end{pmatrix}.
    \]''',
    r'''The factors have shapes $3$-by-$2$ and $2$-by-$4$, so the
    product has shape $3$-by-$4$. Row $j$ of the first factor is
    $(2j-1,2j)$ for $j=1,2,3$. The four entries of row $j$
    of the product are therefore
    \[
    \begin{aligned}
    6(2j-1)+2(2j)&=16j-6,\\
    5(2j-1)+2j&=12j-5,\\
    4(2j-1)+0(2j)&=8j-4,\\
    3(2j-1)-2j&=4j-3.
    \end{aligned}
    \]
    Substituting $j=1,2,3$ gives respectively
    $(10,7,4,1)$, $(26,19,12,5)$, and $(42,31,20,9)$.
    These are precisely the rows of the displayed answer.''',
    1,
    10,
    [r'''Each output entry combines one row of the first factor with one column of the second.'''],
    ['def-matrix-product'],
    '3.42',
    73,
    'example',
)

s.r(
    'ex-matrix-noncommutativity',
    'Matrix multiplication can depend on the order',
    r'''There are $2$-by-$2$ matrices $A,B$ such that $AB\ne BA$.''',
    r'''Take
    \[
    A=\begin{pmatrix}0&1\\0&0\end{pmatrix},
    \qquad
    B=\begin{pmatrix}0&0\\1&0\end{pmatrix}.
    \]
    The product formula gives
    \[
    AB=\begin{pmatrix}0\cdot0+1\cdot1&0\cdot0+1\cdot0\\
    0\cdot0+0\cdot1&0\cdot0+0\cdot0\end{pmatrix}
    =\begin{pmatrix}1&0\\0&0\end{pmatrix},
    \]
    whereas
    \[
    BA=\begin{pmatrix}0\cdot0+0\cdot0&0\cdot1+0\cdot0\\
    1\cdot0+0\cdot0&1\cdot1+0\cdot0\end{pmatrix}
    =\begin{pmatrix}0&0\\0&1\end{pmatrix}.
    \]
    Their first entries differ, so the products are unequal.''',
    1,
    10,
    [r'''Try matrices with just one nonzero entry.'''],
    ['def-matrix-product', 'def-matrix'],
    page=73,
    kind='example',
)

s.r(
    'lem-matrix-product-laws',
    'Associativity and distributive laws for matrix multiplication',
    r'''For $A\in\F^{m,n}$, $B\in\F^{n,p}$, and
    $C\in\F^{p,q}$, one has $(AB)C=A(BC)$.
    If $D\in\F^{n,p}$, $E\in\F^{m,n}$, and $a\in\F$, then
    \[
    A(B+D)=AB+AD,\qquad (A+E)B=AB+EB,
    \]
    \[
    (aA)B=a(AB)=A(aB).
    \]
    Products with a compatible zero matrix are zero matrices.''',
    r'''Both associations of the triple product have shape
    $m$-by-$q$. For each entry,
    \[
    \begin{aligned}
    ((AB)C)_{j,k}
      &=\sum_{s=1}^p\sum_{r=1}^n A_{j,r}B_{r,s}C_{s,k}\\
      &=\sum_{r=1}^n A_{j,r}
        \left(\sum_{s=1}^p B_{r,s}C_{s,k}\right)
       =(A(BC))_{j,k}.
    \end{aligned}
    \]
    The middle equality follows by distributivity and by rearranging
    a finite sum. For distributivity, the relevant entries are
    \[
    \sum_{r=1}^n A_{j,r}(B_{r,k}+D_{r,k})
    =\sum_{r=1}^n A_{j,r}B_{r,k}
     +\sum_{r=1}^n A_{j,r}D_{r,k}
    \]
    and
    \[
    \sum_{r=1}^n(A_{j,r}+E_{j,r})B_{r,k}
    =\sum_{r=1}^n A_{j,r}B_{r,k}
     +\sum_{r=1}^n E_{j,r}B_{r,k}.
    \]
    These are the entries asserted by the two distributive laws.
    Scalar associativity and commutativity give
    \[
    \sum_{r=1}^n(aA_{j,r})B_{r,k}
    =a\sum_{r=1}^n A_{j,r}B_{r,k}
    =\sum_{r=1}^n A_{j,r}(aB_{r,k}),
    \]
    which proves scalar compatibility. If either factor is zero,
    each summand in each product entry is zero, proving the last
    assertion.

    If an inner index set is empty, these identities are identities
    of empty sums, all equal to zero where appropriate.
    If an output shape has no entries, the two matrices being
    compared have the same shape and are equal by definition.
    Thus zero dimensions are included.''',
    2,
    20,
    [
        r'''Prove each formula by comparing an arbitrary entry.''',
        r'''For associativity, expand both inner products into the same finite double sum.''',
    ],
    [
        'def-matrix-product',
        'def-matrix-addition',
        'def-matrix-scaling',
        'c1-thm-complex-laws',
        'c1-lem-scalar-cancellation',
    ],
    page=73,
    kind='lemma',
)

s.r(
    'thm-matrix-composition',
    'The matrix of a composition',
    r'''Let $T:U\to V$ and $S:V\to W$ be linear maps between
    finite-dimensional spaces, with one fixed basis for each space.
    Then
    \[
    \Mat(ST)=\Mat(S)\Mat(T).
    \]''',
    r'''Write the bases as $u_1,\ldots,u_p$, $v_1,\ldots,v_n$,
    and $w_1,\ldots,w_m$. Put $A=\Mat(S)$ and $B=\Mat(T)$.
    For each $k$,
    \[
    \begin{aligned}
    (ST)u_k
      &=S\left(\sum_{r=1}^n B_{r,k}v_r\right)\\
      &=\sum_{r=1}^n B_{r,k}Sv_r\\
      &=\sum_{r=1}^n B_{r,k}\sum_{j=1}^m A_{j,r}w_j\\
      &=\sum_{j=1}^m
        \left(\sum_{r=1}^n A_{j,r}B_{r,k}\right)w_j.
    \end{aligned}
    \]
    The last step regroups finitely many terms and uses commutativity
    of scalar multiplication. Uniqueness of target coordinates
    identifies the coefficient of $w_j$ with the $(j,k)$ entry
    of $\Mat(ST)$, and the product definition identifies it with
    $(AB)_{j,k}$.

    If $n=0$, the expansion of $Tu_k$ is zero, and $S0=0$,
    so the same empty-sum calculation applies.
    If $m=0$ or $p=0$, both compared matrices have the same
    entry-free shape. Thus the formula holds in all cases.''',
    2,
    20,
    [
        r'''Expand $Tu_k$ in the intermediate basis before applying $S$.''',
        r'''Collect the coefficient of each target basis vector.''',
    ],
    [
        'def-linear-map',
        'def-map-composition',
        'lem-composition-linear',
        'thm-linear-zero',
        'def-map-matrix',
        'def-matrix-product',
        'c2-thm-basis-coordinates',
        'c1-def-vector-space',
    ],
    '3.43',
    74,
)

s.d(
    'def-rows-columns',
    'Individual rows and columns',
    r'''For $A\in\F^{m,n}$, write $A_{j,\cdot}\in\F^{1,n}$
    for row $j$, when $1\le j\le m$, and
    $A_{\cdot,k}\in\F^{m,1}$ for column $k$, when $1\le k\le n$.
    A row is regarded as a one-row matrix, and a column as a
    one-column matrix. We identify a $1$-by-$1$ matrix with its
    sole scalar entry when writing scalar formulas.''',
    '3.44',
    74,
)

s.r(
    'ex-row-column-notation',
    'Selecting a row and a column',
    r'''For
    \[
    A=\begin{pmatrix}8&4&5\\1&9&7\end{pmatrix},
    \]
    find $A_{2,\cdot}$ and $A_{\cdot,2}$.
    Also evaluate the product of the row $(3,4)$ and the column
    with entries $6,2$.''',
    r'''The second row contains the entries in positions
    $(2,1),(2,2),(2,3)$, and the second column contains those
    in positions $(1,2),(2,2)$. Therefore
    \[
    A_{2,\cdot}=\begin{pmatrix}1&9&7\end{pmatrix},
    \qquad
    A_{\cdot,2}=\begin{pmatrix}4\\9\end{pmatrix}.
    \]
    The row-column product is the $1$-by-$1$ matrix with entry
    $3\cdot6+4\cdot2=26$, which we identify with the scalar $26$.''',
    1,
    10,
    [r'''A row retains a fixed first index, whereas a column retains a fixed second index.'''],
    ['def-rows-columns', 'def-matrix-product'],
    '3.45',
    74,
    'example',
)

s.r(
    'thm-product-entry',
    'A product entry is a row-column product',
    r'''For $A\in\F^{m,n}$, $B\in\F^{n,p}$, and valid indices
    $j,k$,
    \[
    (AB)_{j,k}=A_{j,\cdot}B_{\cdot,k},
    \]
    with the $1$-by-$1$ product on the right identified with its entry.''',
    r'''The left side is $\sum_{r=1}^n A_{j,r}B_{r,k}$ by
    definition. The right side is the product of a $1$-by-$n$
    matrix and an $n$-by-$1$ matrix, whose sole entry is the same
    sum. If $n=0$, both scalar values are the empty sum, zero.
    If there are no valid $j,k$, the assertion has no instances
    to check.''',
    1,
    10,
    [r'''Expand both sides with the matrix product definition.'''],
    ['def-matrix-product', 'def-rows-columns'],
    '3.46',
    75,
)

s.r(
    'thm-product-column',
    'A column of a product',
    r'''For $A\in\F^{m,n}$, $B\in\F^{n,p}$, and $1\le k\le p$,
    \[
    (AB)_{\cdot,k}=AB_{\cdot,k}.
    \]''',
    r'''Both sides have shape $m$-by-$1$. For every $1\le j\le m$,
    the entry in row $j$ of the left side is
    $\sum_{r=1}^n A_{j,r}B_{r,k}$. The entry in row $j$ of the
    right side is the same sum, because row $r$ of $B_{\cdot,k}$
    has entry $B_{r,k}$. Thus the matrices are equal.
    Empty inner sums give zero on both sides, and if $m=0$
    the shared shape has no entries.''',
    1,
    10,
    [r'''Compare the entry in a fixed row of the two columns.'''],
    ['def-matrix-product', 'def-rows-columns'],
    '3.48',
    75,
)

s.r(
    'ex-product-as-column-combination',
    'A product as a combination of columns',
    r'''Verify
    \[
    \begin{pmatrix}1&2\\3&4\\5&6\end{pmatrix}
    \begin{pmatrix}5\\1\end{pmatrix}
    =
    \begin{pmatrix}7\\19\\31\end{pmatrix}
    =
    5\begin{pmatrix}1\\3\\5\end{pmatrix}
    +\begin{pmatrix}2\\4\\6\end{pmatrix}.
    \]''',
    r'''The three entries of the product are
    $1\cdot5+2\cdot1=7$, $3\cdot5+4\cdot1=19$, and
    $5\cdot5+6\cdot1=31$.
    Entrywise scalar multiplication and addition on the right
    give $5\cdot1+2=7$, $5\cdot3+4=19$, and
    $5\cdot5+6=31$. All three columns have the same shape and
    corresponding entries, proving the displayed identities.''',
    1,
    10,
    [r'''Calculate each of the three entries in both ways.'''],
    ['def-matrix-product', 'def-matrix-addition', 'def-matrix-scaling'],
    '3.49',
    75,
    'example',
)

s.r(
    'thm-column-combination',
    'Multiplication by a column forms a column combination',
    r'''For $A\in\F^{m,n}$ and $b\in\F^{n,1}$ with entries
    $b_1,\ldots,b_n$,
    \[
    Ab=\sum_{r=1}^n b_r A_{\cdot,r}.
    \]''',
    r'''For every row $j$, the entry of $Ab$ is
    $\sum_{r=1}^n A_{j,r}b_r$. The entry in that row of the
    displayed linear combination is
    $\sum_{r=1}^n b_r A_{j,r}$, which agrees by scalar
    commutativity. Equality of corresponding entries proves
    equality of the columns. For $n=0$, the right side is
    the zero column and every entry on the left is an empty
    sum. For $m=0$, both columns have the same entry-free shape.''',
    1,
    10,
    [r'''The coefficient of column $r$ should be the $r$th entry of $b$.'''],
    [
        'def-matrix-product',
        'def-rows-columns',
        'def-matrix-addition',
        'def-matrix-scaling',
        'c1-thm-complex-laws',
    ],
    '3.50',
    76,
)

s.r(
    'thm-product-row-columns',
    'Rows and columns of a product as linear combinations',
    r'''For $C\in\F^{m,c}$ and $R\in\F^{c,n}$,
    \[
    (CR)_{\cdot,k}=\sum_{r=1}^c R_{r,k}C_{\cdot,r}
    \qquad(1\le k\le n),
    \]
    and
    \[
    (CR)_{j,\cdot}=\sum_{r=1}^c C_{j,r}R_{r,\cdot}
    \qquad(1\le j\le m).
    \]''',
    r'''The product-column theorem gives
    $(CR)_{\cdot,k}=CR_{\cdot,k}$. Applying the column-combination
    theorem to this product gives the first formula.

    For the second formula, fix a row $j$. The entry in column
    $k$ of the proposed row combination is
    $\sum_{r=1}^c C_{j,r}R_{r,k}$, by entrywise addition and
    scalar multiplication. This is $(CR)_{j,k}$ by the product
    definition, so every entry in the two rows agrees.
    When $c=0$, these combinations are zero vectors and the
    product entries are empty sums. If a relevant output row
    or column has no entries, equality follows from its shape.''',
    1,
    10,
    [r'''Use the two preceding column formulas for the first identity, and compare entries directly for the row identity.'''],
    [
        'thm-product-column',
        'thm-column-combination',
        'def-matrix-product',
        'def-rows-columns',
        'def-matrix-addition',
        'def-matrix-scaling',
    ],
    '3.51',
    76,
)

s.d(
    'def-row-column-rank',
    'Column rank and row rank',
    r'''For $A\in\F^{m,n}$, its \emph{column space} is the span
    of its columns in $\F^{m,1}$, and its \emph{column rank} is
    the dimension of that span. Its \emph{row space} is the
    span of its rows in $\F^{1,n}$, and its \emph{row rank} is
    the dimension of that span. Each span is finite-dimensional
    because it has a finite spanning list. An empty list of rows
    or columns spans the zero subspace.''',
    '3.52',
    77,
)

s.r(
    'lem-rank-bounds',
    'Bounds on row rank and column rank',
    r'''For $A\in\F^{m,n}$, both its row rank and its column rank
    lie between $0$ and $\min\{m,n\}$.''',
    r'''Dimensions are nonnegative. The column space is a subspace
    of $\F^{m,1}$, whose dimension is $m$, so its dimension is
    at most $m$. Its $n$ columns form a spanning list; comparing
    a basis of that span with this list bounds the dimension
    by $n$ as well.

    The row space is a subspace of $\F^{1,n}$, of dimension $n$,
    so its dimension is at most $n$. Its $m$ rows span it, so
    comparison with a basis bounds its dimension by $m$.
    These arguments include an empty spanning list; in particular
    a zero shape dimension forces both ranks to be zero.''',
    1,
    10,
    [r'''Use both the dimension of the ambient row or column space and the length of the given spanning list.'''],
    [
        'def-row-column-rank',
        'thm-matrix-space-dimension',
        'c2-thm-span-smallest',
        'c2-thm-basis-existence',
        'c2-thm-subspace-dimension',
        'c2-thm-independent-length',
        'c2-def-dimension',
    ],
    page=77,
    kind='lemma',
)

s.r(
    'ex-equal-ranks',
    'Computing both ranks directly',
    r'''For
    \[
    A=\begin{pmatrix}4&7&1&8\\3&5&2&9\end{pmatrix},
    \]
    the column rank and row rank are both $2$.''',
    r'''A relation between the first two columns has equations
    $4a+7b=0$ and $3a+5b=0$. Three times the first equation
    minus four times the second gives $b=0$, and then
    $3a=0$ gives $a=0$. These two columns are independent.
    Since $\F^{2,1}$ has dimension $2$, they are a basis of
    that space by the full-length independence theorem.
    Thus all columns together span $\F^{2,1}$, and the
    column rank is $2$.

    For a relation between the two rows, the first two entries
    give $4a+3b=0$ and $7a+5b=0$. Seven times the first
    equation minus four times the second gives $b=0$, and
    then $4a=0$ gives $a=0$. The two rows are independent.
    They also span the row space by its definition, so they
    are a basis of that space, proving that the row rank is $2$.''',
    2,
    20,
    [
        r'''Check independence of the first two columns.''',
        r'''For the rows, it is enough to use two coordinates of a hypothetical zero relation.''',
    ],
    [
        'def-row-column-rank',
        'thm-matrix-space-dimension',
        'def-matrix-addition',
        'def-matrix-scaling',
        'c1-lem-scalar-cancellation',
        'c2-def-basis',
        'c2-def-dimension',
        'c2-thm-full-length-independent',
    ],
    '3.53',
    77,
    'example',
)

s.d(
    'def-transpose',
    'Transpose',
    r'''For $A\in\F^{m,n}$, its transpose
    $A^{\mathsf t}\in\F^{n,m}$ is defined by
    \[
    (A^{\mathsf t})_{k,j}=A_{j,k}.
    \]
    Thus transposition exchanges the two entry indices and
    exchanges the matrix dimensions. It does not conjugate
    complex entries.''',
    '3.54',
    77,
)

s.r(
    'ex-transpose',
    'Computing a transpose',
    r'''For
    \[
    A=\begin{pmatrix}5&-7\\3&8\\-4&2\end{pmatrix},
    \]
    prove that
    \[
    A^{\mathsf t}=\begin{pmatrix}5&3&-4\\-7&8&2\end{pmatrix}.
    \]''',
    r'''The original shape is $3$-by-$2$, so the transpose has
    shape $2$-by-$3$. Its first row consists of
    $A_{1,1},A_{2,1},A_{3,1}$, which are $5,3,-4$.
    Its second row consists of $A_{1,2},A_{2,2},A_{3,2}$,
    which are $-7,8,2$. These determine all its entries.''',
    1,
    10,
    [r'''The columns of the original matrix become the rows of its transpose.'''],
    ['def-transpose'],
    '3.55',
    78,
    'example',
)

s.r(
    'thm-transpose-laws',
    'Algebraic rules for transposition',
    r'''For $A,B\in\F^{m,n}$, $a\in\F$, and $C\in\F^{n,p}$,
    \[
    (A^{\mathsf t})^{\mathsf t}=A,\qquad
    (A+B)^{\mathsf t}=A^{\mathsf t}+B^{\mathsf t},
    \qquad
    (aA)^{\mathsf t}=aA^{\mathsf t},
    \]
    \[
    (AC)^{\mathsf t}=C^{\mathsf t}A^{\mathsf t}.
    \]
    The transpose of a zero matrix is the zero matrix of the
    transposed shape.''',
    r'''Transposing twice exchanges the two indices twice, so
    the entry in position $(j,k)$ of
    $(A^{\mathsf t})^{\mathsf t}$ is $A_{j,k}$.
    For the next two formulas, compare position $(k,j)$:
    \[
    (A+B)_{j,k}=A_{j,k}+B_{j,k},\qquad
    (aA)_{j,k}=aA_{j,k}.
    \]
    These are exactly the entries obtained after adding or
    scaling the transposed matrices.

    Both sides of the product formula have shape $p$-by-$m$.
    Their entries satisfy
    \[
    \begin{aligned}
    ((AC)^{\mathsf t})_{k,j}
      &=\sum_{r=1}^n A_{j,r}C_{r,k}\\
      &=\sum_{r=1}^n
        (C^{\mathsf t})_{k,r}(A^{\mathsf t})_{r,j}
       =(C^{\mathsf t}A^{\mathsf t})_{k,j},
    \end{aligned}
    \]
    where the second equality uses scalar commutativity.
    Transposing a zero matrix leaves every existing entry
    zero, proving the final assertion.
    Empty sums and entry-free shapes satisfy the same
    formulas by their definitions.''',
    2,
    20,
    [
        r'''Follow what happens to a pair of indices.''',
        r'''In the product formula, compare entry $(k,j)$ on both sides.''',
    ],
    [
        'def-transpose',
        'def-matrix-addition',
        'def-matrix-scaling',
        'def-matrix-product',
        'def-matrix-space',
        'c1-thm-complex-laws',
    ],
    page=78,
)

s.r(
    'lem-transpose-rank-swap',
    'Transposition exchanges the two kinds of rank',
    r'''For every matrix $A$, the column rank of $A^{\mathsf t}$
    equals the row rank of $A$, and the row rank of
    $A^{\mathsf t}$ equals the column rank of $A$.''',
    r'''Let $r_1,\ldots,r_d$ be a basis of the row space of $A$.
    A column of $A^{\mathsf t}$ is the transpose of a row of $A$.
    Expanding that row in the $r_i$ and using linearity of
    transposition expresses the column as a combination of
    $r_1^{\mathsf t},\ldots,r_d^{\mathsf t}$. Conversely, each
    $r_i$ is a combination of rows of $A$, so its transpose
    is a combination of columns of $A^{\mathsf t}$.
    Thus the transposed list spans precisely the column
    space of $A^{\mathsf t}$.

    If $\sum_i a_i r_i^{\mathsf t}=0$, transpose this relation.
    Linearity, preservation of zero, and transposing twice
    give $\sum_i a_i r_i=0$. Independence of the original
    basis gives every $a_i=0$. Hence the transposed list
    is a basis of the column space of $A^{\mathsf t}$ and
    has length $d$, proving the first equality.
    This reasoning includes $d=0$, with empty basis lists.

    Apply the first equality to $A^{\mathsf t}$ and use
    $(A^{\mathsf t})^{\mathsf t}=A$. It says that the column
    rank of $A$ is the row rank of $A^{\mathsf t}$,
    which is the second equality.''',
    2,
    20,
    [
        r'''Transpose a basis of the row space, not just the original list of rows.''',
        r'''Apply transpose again to test independence of the new list.''',
    ],
    [
        'def-row-column-rank',
        'def-transpose',
        'thm-transpose-laws',
        'c2-thm-basis-existence',
        'c2-def-basis',
        'c2-def-dimension',
    ],
    page=78,
    kind='lemma',
)

s.r(
    'thm-column-row-factorization',
    'Factoring a matrix through a basis of its column space',
    r'''If $A\in\F^{m,n}$ has column rank $c$, there are
    matrices $C\in\F^{m,c}$ and $R\in\F^{c,n}$ such that
    \[
    A=CR.
    \]
    The columns of $C$ can be selected from the columns of $A$
    to form a basis of its column space. The conclusion includes
    $c=0$, with the corresponding empty shapes.''',
    r'''The columns of $A$ span its column space. Reduce this
    list to a basis, which has length $c$ by the definition
    of column rank. Form $C$ by placing these basis columns
    next to one another in their retained order.

    For each column index $k$, there are unique scalars
    $R_{1,k},\ldots,R_{c,k}$ satisfying
    \[
    A_{\cdot,k}=\sum_{r=1}^c R_{r,k}C_{\cdot,r},
    \]
    because the columns of $C$ are a basis of the column space.
    Use these coefficients as column $k$ of a matrix
    $R\in\F^{c,n}$. The column formula for a product then gives
    $(CR)_{\cdot,k}=A_{\cdot,k}$ for every $k$, so $CR=A$.

    If $c=0$, the column space has dimension zero and hence is
    the zero subspace. Every column of $A$ is zero.
    Take $C$ to be the unique $m$-by-$0$ matrix and $R$ the
    unique $0$-by-$n$ matrix. Each entry of their product is an
    empty sum, so it is zero and agrees with $A$.
    If $A$ has no entries, the equality is equality of matrices
    of the same entry-free shape. The selected basis of its
    column space is then the empty list.''',
    3,
    30,
    [
        r'''Select a basis from the existing columns.''',
        r'''Record the coefficients expressing each original column in this selected basis.''',
    ],
    [
        'def-row-column-rank',
        'def-matrix',
        'def-matrix-product',
        'thm-product-row-columns',
        'c2-thm-reduce-spanning',
        'c2-thm-basis-coordinates',
        'c2-def-dimension',
        'c2-lem-zero-dimension',
    ],
    '3.56',
    78,
)

s.r(
    'thm-row-column-rank',
    'Row rank and column rank agree',
    r'''For every matrix over $\F$, its row rank equals its column rank.''',
    r'''Let $A\in\F^{m,n}$ have column rank $c$, and factor it as
    $A=CR$ with $C\in\F^{m,c}$ and $R\in\F^{c,n}$ using the
    preceding theorem. Every row of $A$ is a linear combination
    of the rows of $R$ by the row formula for a product.
    Hence the row space of $A$ is contained in the row space
    of $R$. The subspace dimension inequality and the rank
    bound for the $c$-by-$n$ matrix $R$ give
    \[
    \text{row rank of }A
    \le \text{row rank of }R
    \le c
    =\text{column rank of }A.
    \]
    This proves the indicated inequality for every matrix,
    including matrices with column rank zero.

    Apply that inequality to $A^{\mathsf t}$. The transpose
    rank-swap lemma converts it into
    \[
    \text{column rank of }A
    =\text{row rank of }A^{\mathsf t}
    \le\text{column rank of }A^{\mathsf t}
    =\text{row rank of }A.
    \]
    The two inequalities prove equality. Since all preceding
    statements include empty shapes and zero ranks, those
    cases are included here as well.''',
    3,
    30,
    [
        r'''Use the factorization to bound the row rank by the column rank.''',
        r'''Obtain the reverse inequality by applying the same argument to the transpose.''',
    ],
    [
        'thm-column-row-factorization',
        'thm-product-row-columns',
        'def-row-column-rank',
        'lem-rank-bounds',
        'lem-transpose-rank-swap',
        'c2-thm-span-smallest',
        'c2-thm-subspace-dimension',
    ],
    '3.57',
    78,
)

s.d(
    'def-rank',
    'Rank of a matrix',
    r'''The \emph{rank} of a matrix $A$, written $\Rank A$,
    is the dimension of its column space. The row-column rank
    theorem shows that it is also the dimension of its row space.''',
    '3.58',
    79,
)

s.card(
    'matrix-of-map-columns',
    'def-map-matrix',
    r'''What does column $k$ of a matrix representing a linear map contain?''',
    r'''The coefficients of the image of domain basis vector $v_k$
    when expanded in the chosen target basis.''',
)

s.card(
    'matrix-space-dimension',
    'thm-matrix-space-dimension',
    r'''What is the dimension of $\F^{m,n}$?''',
    r'''It is $mn$. A basis places one $1$ in a selected entry
    and zeros elsewhere; if a shape dimension is zero, the
    matrix space is the zero space.''',
)

s.card(
    'matrix-product-shape',
    'def-matrix-product',
    r'''When can an $m$-by-$n$ matrix multiply an $r$-by-$p$
    matrix, and what is the result's shape?''',
    r'''The product is defined when $n=r$, and its shape is
    $m$-by-$p$.''',
)

s.card(
    'matrix-composition',
    'thm-matrix-composition',
    r'''How does composition of linear maps appear in their matrices?''',
    r'''With consistent bases, $\Mat(ST)=\Mat(S)\Mat(T)$;
    the rightmost map is applied first.''',
)

s.card(
    'column-combination',
    'thm-column-combination',
    r'''How can $Ab$ be expressed using the columns of $A$?''',
    r'''It is $\sum_r b_rA_{\cdot,r}$, with coefficients supplied
    by the entries of the column $b$.''',
)

s.card(
    'product-rows',
    'thm-product-row-columns',
    r'''In which span do the rows of $CR$ lie?''',
    r'''They lie in the span of the rows of $R$:
    $(CR)_{j,\cdot}=\sum_r C_{j,r}R_{r,\cdot}$.''',
)

s.card(
    'transpose-product',
    'thm-transpose-laws',
    r'''What happens to a product when it is transposed?''',
    r'''The order reverses:
    $(AC)^{\mathsf t}=C^{\mathsf t}A^{\mathsf t}$.''',
)

s.card(
    'column-row-factorization',
    'thm-column-row-factorization',
    r'''How is the factorization $A=CR$ constructed when the
    column rank is $c$?''',
    r'''Put a basis selected from the columns of $A$ into the
    $m$-by-$c$ matrix $C$, and put the coefficients for each
    original column into the corresponding column of the
    $c$-by-$n$ matrix $R$.''',
)

s.card(
    'row-column-rank-proof',
    'thm-row-column-rank',
    r'''What are the two steps proving equality of row rank and column rank?''',
    r'''A column-row factorization bounds row rank by column rank.
    Apply the same inequality to the transpose to reverse the bound.''',
)

s.card(
    'matrix-rank',
    'def-rank',
    r'''Define the rank of a matrix.''',
    r'''It is the dimension of the span of its columns,
    equivalently the dimension of the span of its rows.''',
)

s.write()
