from common import Section
s=Section('3e')
s.p('intro-products-quotients','Combining spaces and identifying vectors',r'''A product keeps several vector components in separate positions. A quotient instead identifies vectors whose difference belongs to a chosen subspace. These constructions let us describe direct sums and remove the failure of injectivity from a linear map.''',96)
s.d('def-product-space','Products of vector spaces',r'''For vector spaces $V_1,\ldots,V_m$ over the same field, with $m\ge1$, their product consists of tuples $(v_1,\ldots,v_m)$ with $v_j\in V_j$. Operations act in each position:
\[(u_1,\ldots,u_m)+(v_1,\ldots,v_m)=(u_1+v_1,\ldots,u_m+v_m),\quad a(v_1,\ldots,v_m)=(av_1,\ldots,av_m).\]''','3.87',96)
s.r('ex-product-arithmetic','Arithmetic with polynomial and coordinate components',r'''In $\Poly_5(\R)\times\R^3$, set $u=(1+2x^2,(1,-1,3))$ and $v=(x^5-x,(2,4,0))$. Then $u+v=(1-x+2x^2+x^5,(3,3,3))$ and $2u=(2+4x^2,(2,-2,6))$.''',r'''Each polynomial has degree at most five, so both tuples belong to the stated product. The product rule for addition adds the polynomials pointwise and the three real coordinates separately, producing the displayed sum. The product rule for scaling doubles the polynomial coefficients and the three real coordinates, producing the second tuple.''',1,10,[r'The two positions belong to different spaces; perform each operation in its own space.'],['def-product-space','c2-def-polynomial-space','c1-def-coordinate-addition','c1-def-coordinate-scaling'],'3.88',96,'example')
s.r('thm-product-space','A product is a vector space',r'''The product $V_1\times\cdots\times V_m$ with its defined operations is a vector space. Its zero is $(0_{V_1},\ldots,0_{V_m})$, and the negative of $(v_1,\ldots,v_m)$ is $(-v_1,\ldots,-v_m)$.''',r'''Closure holds because addition and scaling stay in each $V_j$. Write $u,v,w$ for product vectors, and let $a,b\in\F$. In every position $j$, the vector-space axioms in $V_j$ give
\[\begin{aligned}
u_j+v_j&=v_j+u_j,&(u_j+v_j)+w_j&=u_j+(v_j+w_j),\\
u_j+0_{V_j}&=u_j,&u_j+(-u_j)&=0_{V_j},\\
(ab)u_j&=a(bu_j),&1u_j&=u_j,\\
a(u_j+v_j)&=au_j+av_j,&(a+b)u_j&=au_j+bu_j.
\end{aligned}\]
Equality in every position is equality of product tuples. These eight identities therefore establish all the vector-space axioms, including the asserted zero and negatives.''',1,10,[r'Check the axioms one component at a time.'],['def-product-space','c1-def-vector-space'],'3.89',96)
s.r('ex-flatten-product','Flattening a product of coordinate spaces',r'''The map $F:\R^2\times\R^3\to\R^5$ defined by $F((x_1,x_2),(x_3,x_4,x_5))=(x_1,x_2,x_3,x_4,x_5)$ is an isomorphism. The two spaces are not literally the same set of lists: their elements have different outer lengths.''',r'''Flattening a componentwise sum gives the sum of the flattened lists, and flattening a scalar multiple scales each of the same five coordinates. Thus $F$ is linear. The function that splits a length-five list after its second position is an inverse function: splitting and then flattening, or flattening and then splitting, recovers the input. Consequently $F$ is bijective and is a linear isomorphism by the invertibility criterion. Elements in the domain have outer length two, whereas those in the target have length five, explaining the set distinction.''',1,10,[r'Write the inverse by splitting a list after its second position.'],['def-product-space','thm-product-space','def-linear-map','def-isomorphism','thm-invertible-bijective'],'3.90',97,'example')
s.r('ex-product-basis','A basis in a mixed product',r'''The list $(1,(0,0)),(x,(0,0)),(x^2,(0,0)),(0,(1,0)),(0,(0,1))$ is a basis of $\Poly_2(\R)\times\R^2$.''',r'''A vector $(a+bx+cx^2,(d,e))$ is the linear combination of the displayed list with coefficients $a,b,c,d,e$, so it spans. If such a combination is zero, polynomial coefficient uniqueness gives $a=b=c=0$, and the second component gives $d=e=0$. Thus the list is independent and a basis.''',1,10,[r'Separate a zero relation into its polynomial and coordinate parts.'],['thm-product-space','def-product-space','c2-def-basis','c2-def-polynomial-space','c2-lem-polynomial-coefficients'],'3.91',97,'example')
s.r('thm-product-dimension','Dimension of a finite product',r'''If each $V_j$ is finite-dimensional, then $V_1\times\cdots\times V_m$ is finite-dimensional and has dimension $\sum_{j=1}^m\dim V_j$.''',r'''Choose a basis $v_{j,1},\ldots,v_{j,n_j}$ in each $V_j$. For each pair $(j,k)$ let $b_{j,k}$ be the product vector with $v_{j,k}$ in position $j$ and zero in all other positions. List these vectors in increasing $j$, and within each position in increasing $k$. For any tuple, expand its $j$th component in the chosen basis of $V_j$. Combining these expansions expresses the tuple as a combination of the $b_{j,k}$, proving spanning. In a zero relation on this list, inspection of position $j$ gives a zero relation on $v_{j,1},\ldots,v_{j,n_j}$. Their independence forces every coefficient indexed by $j$ to vanish. Doing this for each $j$ proves independence of the whole list. It is a finite basis of length $\sum_jn_j$, which proves both claims. If $n_j=0$, that component space is zero and contributes no vectors; if all $n_j=0$, the product is zero and the constructed basis is empty.''',2,20,[r'Place each basis vector of each factor in its own component, filling the others with zero.'],['thm-product-space','def-product-space','c2-thm-basis-existence','c2-def-basis','c2-def-dimension','c2-lem-zero-dimension'],'3.92',97)
s.r('thm-product-direct-sum','The summation map detects direct sums',r'''For subspaces $V_1,\ldots,V_m$ of $V$, the map
\[G:V_1\times\cdots\times V_m\to V_1+\cdots+V_m,\qquad G(v_1,\ldots,v_m)=\sum_jv_j\]
is linear and surjective. The sum is direct exactly when $G$ is injective, and hence exactly when $G$ is an isomorphism.''',r'''The target contains every prescribed sum and is a vector space by the subspace-sum theorem. Regrouping finite sums gives $G(u+v)=Gu+Gv$, and distributivity gives $G(au)=aGu$, so $G$ is linear. Every element of the target is such a sum by its definition, proving surjectivity. The kernel consists of tuples with $\sum_jv_j=0$. By the zero criterion for directness, this kernel contains only the zero tuple exactly when the sum is direct. The injectivity criterion for linear maps gives the stated equivalence. Since $G$ is already surjective, the bijective invertibility criterion proves the isomorphism assertion.''',2,20,[r'Compute the null space of the summation map.'],['thm-product-space','def-product-space','c1-def-subspace-sum','c1-thm-smallest-sum','c1-thm-direct-zero','def-linear-map','def-null-space','thm-injective-null','def-surjective','thm-invertible-bijective','def-isomorphism'],'3.93',98)
s.r('thm-direct-sum-dimension','Direct sums characterized by dimension addition',r'''If $V_1,\ldots,V_m$ are subspaces of a finite-dimensional space, their sum is direct exactly when
\[\dim(V_1+\cdots+V_m)=\sum_j\dim V_j.\]''',r'''Each subspace is finite-dimensional, so the product dimension theorem applies to the domain of the summation map $G$. Its range is the entire sum. Rank-nullity gives
\[\sum_j\dim V_j=\dim\Null G+\dim(V_1+\cdots+V_m).\]
The displayed dimension equality therefore holds exactly when $\dim\Null G=0$. This is equivalent to $\Null G=\{0\}$ and hence to injectivity of $G$. By the summation-map theorem this is equivalent to directness.''',2,20,[r'Apply rank-nullity to the summation map.'],['c2-thm-subspaces-finite','c2-lem-zero-dimension','thm-product-dimension','thm-product-direct-sum','thm-rank-nullity','thm-injective-null'],'3.94',98)
s.d('def-vector-set-sum','Adding a vector to a subset',r'''For $v\in V$ and a subset $U\subseteq V$, write $v+U=\{v+u:u\in U\}$. This is a subset of $V$, not an individual vector of $V$.''','3.95',98)
s.r('ex-shifted-line','A shifted line in the plane',r'''Let $U=\{(t,2t):t\in\R\}$. Then
\[(17,20)+U=\{(x,2x-14):x\in\R\}=(7,0)+U.\]''',r'''An element of the first set has coordinates $(17+t,20+2t)$. Setting $x=17+t$ gives second coordinate $2x-14$. Conversely, a prescribed real $x$ is obtained by taking $t=x-17$. The same calculation for $(7,0)+(t,2t)$ gives $(x,2x-14)$ with $x=7+t$, ranging over all real values. Both equalities follow.''',1,10,[r'Express the second coordinate in terms of the first.'],['def-vector-set-sum','c1-def-coordinate-addition'],'3.96',99,'example')
s.d('def-translate','Translates and affine geometric objects',r'''A set $v+U$ is called a translate of $U$. For a nonzero vector $u$, an affine line with direction $\Span(u)$ means a set $v+\Span(u)$. For independent $u,w\in\R^3$, an affine plane with direction $\Span(u,w)$ means $v+\Span(u,w)$. In this terminology affine lines or planes with the same direction are parallel.''','3.97',99)
s.r('ex-translates','Families of parallel lines and planes',r'''The translates of $U=\{(x,2x):x\in\R\}$ are exactly the sets $\{(x,2x+b):x\in\R\}$ for $b\in\R$. The translates of $H=\{(x,y,0):x,y\in\R\}$ are exactly the sets $\{(x,y,c):x,y\in\R\}$ for $c\in\R$. More generally, translates of a linear line or plane are exactly the affine lines or planes with its direction.''',r'''For $v=(a,b)$, the translate $v+U$ consists of $(a+t,b+2t)$, which is the line with second coordinate $2x+(b-2a)$. Every desired intercept $d$ arises from $v=(0,d)$. For $v=(a,b,c)$, the translate $v+H$ consists of $(a+x,b+y,c)$; the first two coordinates vary independently over all real numbers, and every third coordinate $c$ arises by translating by $(0,0,c)$. The general assertion follows from the definitions of affine line, affine plane, and direction: each such affine set has exactly the form of a translate of its stated direction subspace.''',1,10,[r'Write the coordinates of a typical translated point.'],['def-vector-set-sum','def-translate','c2-def-span'],'3.98',99,'example')
s.d('def-quotient-space','Quotient space as a set of translates',r'''If $U$ is a subspace of $V$, define $V/U=\{v+U:v\in V\}$. Its elements are translates of $U$, also called cosets. We next define vector operations on this set.''','3.99',99)
s.r('ex-geometric-quotients','Geometric objects as quotient elements',r'''For $U=\{(x,2x):x\in\R\}$, elements of $\R^2/U$ are exactly the lines of slope $2$. If $L$ is a line through zero in $\R^3$, elements of $\R^3/L$ are its parallel affine lines. If $H$ is a plane through zero in $\R^3$, elements of $\R^3/H$ are its parallel affine planes.''',r'''By definition a quotient contains precisely the translates of the subspace being removed. The first family of translates was computed in the preceding example. For a linear line or plane, the definitions of affine line or plane identify its translates with exactly the stated parallel affine sets. Thus all three descriptions follow from the quotient definition and the previously established descriptions of translates.''',1,10,[r'A quotient element is an entire translate.'],['def-quotient-space','def-translate','ex-translates'],'3.100',100,'example')
s.r('thm-coset-equality','Equal or disjoint translates',r'''If $U$ is a subspace of $V$ and $v,w\in V$, the following conditions are equivalent:
\[v-w\in U,\qquad v+U=w+U,\qquad(v+U)\cap(w+U)\ne\varnothing.\]''',r'''Assume $v-w\in U$. For $u\in U$, $v+u=w+((v-w)+u)$ lies in $w+U$, giving $v+U\subseteq w+U$. Also $w-v=-(v-w)\in U$, and for $u\in U$, $w+u=v+((w-v)+u)$ lies in $v+U$. This proves equality. Equal translates have nonempty intersection because $0\in U$ makes $v$ belong to $v+U$. Finally, if $x$ is in their intersection, write $x=v+u_1=w+u_2$ with $u_1,u_2\in U$. Subtraction gives $v-w=u_2-u_1\in U$, since a subspace is closed under addition and multiplication by $-1$. This proves the cycle of implications.''',2,20,[r'If two translates meet, subtract their two expressions for a common point.'],['def-vector-set-sum','c1-thm-subspace-test','c1-def-vector-subtraction','c1-thm-negative-one'],'3.101',100)
s.d('def-quotient-operations','Operations on cosets',r'''For $U\subseteq V$ a subspace, prescribe
\[(v+U)+(w+U)=(v+w)+U,\qquad a(v+U)=(av)+U.\]
The next result verifies that these prescriptions do not depend on representatives.''','3.102',100)
s.r('thm-quotient-vector-space','Well-defined quotient vector operations',r'''The prescribed operations make $V/U$ a vector space. Its zero is $U=0+U$, and the negative of $v+U$ is $(-v)+U$.''',r'''Suppose $v+U=v'+U$ and $w+U=w'+U$. The coset equality criterion gives $v-v'\in U$ and $w-w'\in U$. Closure yields $(v+w)-(v'+w')\in U$ and $av-av'=a(v-v')\in U$. Applying the same criterion gives $(v+w)+U=(v'+w')+U$ and $av+U=av'+U$. Thus both operations are well-defined and stay in $V/U$.
Write $[v]=v+U$ for this proof. The rules and the axioms in $V$ give
\[\begin{aligned}
[u]+[v]&=[u+v]=[v+u]=[v]+[u],\\
([u]+[v])+[w]&=[(u+v)+w]=[u+(v+w)]=[u]+([v]+[w]),\\
[v]+[0]&=[v],\qquad [v]+[-v]=[0],\\
(ab)[v]&=[(ab)v]=[a(bv)]=a(b[v]),\qquad 1[v]=[v],\\
a([u]+[v])&=[a(u+v)]=[au+av]=a[u]+a[v],\\
(a+b)[v]&=[(a+b)v]=[av+bv]=a[v]+b[v].
\end{aligned}\]
These verify all eight axioms. Finally $0+U=U$, since $0+u=u$ for every $u\in U$, so the zero and negatives have the stated descriptions.''',2,20,[r'First compare operations using two different representatives of each coset.',r'Once representative independence is established, transfer each vector-space identity to cosets.'],['def-quotient-space','def-quotient-operations','thm-coset-equality','c1-thm-subspace-test','c1-def-vector-space'],'3.103',101)
s.d('def-quotient-map','The canonical quotient map',r'''For a subspace $U$ of $V$, define $\pi:V\to V/U$ by $\pi(v)=v+U$.''','3.104',101)
s.r('thm-quotient-map','Linearity, range, and kernel of the quotient map',r'''The quotient map is linear and surjective, and $\Null\pi=U$.''',r'''By the quotient operation rules, $\pi(v+w)=(v+w)+U=\pi(v)+\pi(w)$ and $\pi(av)=av+U=a\pi(v)$. Every coset $v+U$ is the image of its representative $v$, proving surjectivity. The zero of the quotient is $0+U$, and the coset equality criterion says $\pi(v)=0+U$ exactly when $v-0\in U$. Hence its kernel is precisely $U$.''',1,10,[r'Identify which vectors map to the zero coset.'],['def-quotient-map','def-quotient-space','def-quotient-operations','thm-quotient-vector-space','thm-coset-equality','def-linear-map','def-null-space','def-surjective'],page=101)
s.r('thm-quotient-dimension','Dimension of a quotient',r'''If $V$ is finite-dimensional and $U$ is a subspace, then $V/U$ is finite-dimensional and $\dim(V/U)=\dim V-\dim U$.''',r'''The quotient map is linear with range $V/U$ and kernel $U$. Rank-nullity for a finite-dimensional domain states that its range is finite-dimensional and that $\dim V=\dim\Null\pi+\dim\Range\pi$. Substituting the identified kernel and range and rearranging proves the formula. If $U=\{0\}$ or $U=V$, the same calculation applies and gives dimensions $\dim V$ or $0$, respectively.''',2,15,[r'Apply rank-nullity to the quotient map.'],['thm-quotient-map','thm-rank-nullity'],'3.105',102)
s.d('def-induced-map','A map on the quotient by a kernel',r'''For $T\in\Lin(V,W)$, prescribe $\widetilde T:V/\Null T\to W$ by $\widetilde T(v+\Null T)=Tv$. The representative independence of this prescription is part of the next result.''','3.106',102)
s.r('lem-induced-map-linear','The induced map is well-defined and linear',r'''The prescription defining $\widetilde T$ gives a well-defined linear map from $V/\Null T$ to $W$.''',r'''The null space is a subspace, so the quotient is a vector space. If $v+\Null T=w+\Null T$, then $v-w\in\Null T$. Linearity gives $0=T(v-w)=Tv-Tw$, hence $Tv=Tw$, establishing independence of representatives. For cosets represented by $v,w$ and scalar $a$, the quotient operations give
\[\widetilde T((v+\Null T)+(w+\Null T))=T(v+w)=Tv+Tw,\]
and $\widetilde T(a(v+\Null T))=T(av)=aTv$. These are the two linearity identities.''',2,15,[r'Compare the images of representatives whose difference lies in the kernel.'],['def-induced-map','thm-null-subspace','thm-quotient-vector-space','thm-coset-equality','def-quotient-operations','def-linear-map','def-null-space','c1-thm-negative-one'],page=102,kind='lemma')
s.r('thm-quotient-isomorphism','Removing the kernel produces an isomorphism onto the range',r'''For $T\in\Lin(V,W)$ and the quotient map $\pi:V\to V/\Null T$, we have $\widetilde T\pi=T$. Moreover $\widetilde T$ is injective and $\Range\widetilde T=\Range T$. In particular, $V/\Null T$ is isomorphic to $\Range T$, without a finite-dimensionality hypothesis.''',r'''For every $v\in V$, $(\widetilde T\pi)v=\widetilde T(v+\Null T)=Tv$, proving the factorization. If a coset $v+\Null T$ maps to zero, then $Tv=0$ and $v\in\Null T$. The coset equality criterion gives $v+\Null T=0+\Null T$, the zero of the quotient. Thus $\widetilde T$ has zero kernel and is injective. Every output $\widetilde T(v+\Null T)$ equals $Tv$ and lies in $\Range T$, giving one range inclusion. Conversely, each $Tv$ equals that output, giving the reverse inclusion. Regard the same map as having target $\Range T$, which is a subspace of $W$. Its linearity persists under that restriction of target, it remains injective, and the range equality makes it surjective. The bijective invertibility theorem makes it an isomorphism of the two asserted spaces.''',2,20,[r'Compute the kernel and the image of the induced map.',r'For the isomorphism, use the range as target.'],['def-induced-map','lem-induced-map-linear','def-quotient-map','thm-coset-equality','thm-quotient-vector-space','def-map-composition','def-null-space','def-range','thm-range-subspace','thm-injective-null','thm-invertible-bijective','def-isomorphism'],'3.107',102)
s.card('product-dimension','thm-product-dimension',r'What is the dimension of a finite product of finite-dimensional spaces?',r'The sum of the dimensions of the factors.')
s.card('summation-map','thm-product-direct-sum',r'Which map links a product of subspaces to their sum, and when is it injective?',r'The map $(v_1,\ldots,v_m)\mapsto\sum_jv_j$ is injective exactly when the sum is direct.')
s.card('quotient-elements','def-quotient-space',r'What are the elements of $V/U$?',r'The sets $v+U=\{v+u:u\in U\}$, with $v\in V$.')
s.card('coset-equality','thm-coset-equality',r'When do $v+U$ and $w+U$ agree?',r'Exactly when $v-w\in U$. Otherwise they are disjoint.')
s.card('quotient-zero','thm-quotient-vector-space',r'What is the zero vector of $V/U$?',r'The coset $0+U$, which is the set $U$ itself.')
s.card('quotient-map','thm-quotient-map',r'What are the kernel and range of the quotient map?',r'Its kernel is $U$ and its range is all of $V/U$.')
s.card('quotient-dimension','thm-quotient-dimension',r'What is $\dim(V/U)$ when $V$ is finite-dimensional?',r'$\dim V-\dim U$.')
s.card('quotient-isomorphism','thm-quotient-isomorphism',r'Which quotient is naturally isomorphic to the range of a linear map?',r'$V/\Null T$ maps isomorphically to $\Range T$ by $v+\Null T\mapsto Tv$.')
s.write()
