from common import Section
s=Section('6-exercises')
s.p('intro-exercises','Exercises on orthogonality and approximation',r'''These optional problems use inner products to study coordinates, linear functionals, projections, and best approximations. Each proof uses required results only, so the exercises can be attempted independently.''')
s.r('ex-positive-weight-characterization','Positive coordinate weights',r'''For real numbers $a_1,\ldots,a_n$, show that
\[\ip{x}{y}=\sum_{j=1}^n a_jx_j\overline{y_j}\]
is an inner product on $\F^n$ exactly when every $a_j>0$. When this holds, find an orthonormal basis.''',r'''If the expression is an inner product, substituting the nonzero standard vector $e_j$ in both slots gives $a_j=\ip{e_j}{e_j}>0$. Conversely assume every weight is positive. Distributing the coordinate sum proves additivity and homogeneity in the first slot. Because the weights are real, conjugating the sum exchanges its two inputs. On the diagonal the value is $\sum_ja_j|x_j|^2$, which is nonnegative; if $x\ne0$, a nonzero coordinate supplies a strictly positive summand, so the value is positive. Thus the inner-product axioms hold. The vectors $e_j/\sqrt{a_j}$ have diagonal pairings one and distinct pairings zero. They form a basis because each is a nonzero multiple of a standard basis vector. For $n=0$, the weight condition is vacuous, the zero space has its unique inner product, and the empty list is an orthonormal basis.''',2,15,[r'Test necessity on standard vectors; for sufficiency use positivity of every summand.'],['def-inner-product','def-orthonormal-basis','c4-thm-complex-properties','c2-ex-standard-basis'],kind='exercise',optional=True)
s.r('ex-inner-product-from-norm','The norm determines the inner product',r'''Prove that two inner products on the same real or complex vector space coincide if they give every vector the same norm. Derive formulas that recover the inner product from norms.''',r'''Expanding by the inner-product identities gives
\[\|u+v\|^2-\|u-v\|^2=4\operatorname{Re}\ip{u}{v}.\]
Over $\R$ the inner product is real, so division by four recovers it. Over $\C$ set $z=\ip{u}{v}$. Since the second slot is conjugate linear, $\ip{u}{iv}=-iz$ and $\ip{iv}{u}=i\overline z$. Their sum is $2\operatorname{Im}z$. Therefore expansion also gives
\[\|u+iv\|^2-\|u-iv\|^2=4\operatorname{Im}\ip{u}{v}.\]
The complex reconstruction formula is consequently
\[\ip{u}{v}=\tfrac14(\|u+v\|^2-\|u-v\|^2)+\tfrac i4(\|u+iv\|^2-\|u-iv\|^2).\]
Both real and imaginary parts are determined by the norm. If two inner products yield that same norm, the appropriate reconstruction formula equates their values on every pair.''',3,30,[r'Expand the squared norms of a sum and a difference.',r'In the complex case also replace $v$ by $iv$.'],['thm-inner-product-properties','def-norm','c4-def-real-imaginary','c4-thm-complex-properties'],kind='exercise',optional=True)
s.r('ex-pythagorean-converse','A field-dependent converse to Pythagoras',r'''Show that $\|u+v\|^2=\|u\|^2+\|v\|^2$ is equivalent to $\operatorname{Re}\ip{u}{v}=0$. Deduce that it implies orthogonality over $\R$, and give a counterexample to that implication over $\C$.''',r'''Expansion gives $\|u+v\|^2=\|u\|^2+\|v\|^2+\ip{u}{v}+\ip{v}{u}$. Conjugate symmetry makes the last two terms $2\operatorname{Re}\ip{u}{v}$, proving the equivalence. Over the real field this real part is the inner product itself, so it vanishes exactly for orthogonal vectors. In the standard complex space $\C$, take $u=1$ and $v=i$. Their inner product is $1\overline i=-i\ne0$, but $|1+i|^2=2=|1|^2+|i|^2$. Thus the squared-norm identity need not imply orthogonality over $\C$.''',2,20,[r'The cross terms add to twice a real part.'],['thm-inner-product-properties','def-norm','def-orthogonal','thm-standard-inner-product','c4-thm-complex-properties'],kind='exercise',optional=True)
s.r('ex-orthogonal-sum-coefficients','Coordinates in an orthogonal basis without unit norms',r'''If $f_1,\ldots,f_n$ is a basis of pairwise orthogonal vectors, prove
\[v=\sum_j\frac{\ip{v}{f_j}}{\|f_j\|^2}f_j,\qquad \|v\|^2=\sum_j\frac{|\ip{v}{f_j}|^2}{\|f_j\|^2}.\]''',r'''Basis vectors are nonzero, so their norms are positive. Put $e_j=f_j/\|f_j\|$. Scalar extraction from the pairings proves that these vectors are orthonormal, and rescaling by nonzero scalars preserves the basis property. Orthonormal coordinates give $v=\sum_j\ip{v}{e_j}e_j$. The positive real normalization factor gives $\ip{v}{e_j}=\ip{v}{f_j}/\|f_j\|$, which yields the first formula. Parseval gives $\|v\|^2=\sum_j|\ip{v}{e_j}|^2$, and substitution gives the second. If the list is empty, $v=0$ and both formulas are zero identities.''',2,15,[r'Normalize each vector and use the orthonormal coordinate formulas.'],['thm-orthonormal-coordinates','thm-inner-product-properties','thm-norm-properties','def-orthonormal-basis','c2-def-basis'],kind='exercise',optional=True)
s.r('ex-bessel-detects-completeness','When Bessel inequality is always equality',r'''For a finite orthonormal list in an inner product space $V$, prove that it is a basis exactly when
\[\sum_j|\ip{v}{e_j}|^2=\|v\|^2\quad\text{for every }v\in V.\]
No finite-dimensionality hypothesis on $V$ is required.''',r'''If the list is a basis, Parseval gives the identity. Conversely the equality condition in Bessel inequality says that each vector satisfying the identity belongs to the span of the orthonormal list. If every vector satisfies it, the list spans $V$. It is independent by orthonormal independence, so it is a basis. For an empty list the identity holds for all vectors exactly when every norm is zero, or equivalently when $V=\{0\}$, again exactly its basis case.''',2,15,[r'Use the equality condition in Bessel inequality separately for each vector.'],['thm-bessel','thm-orthonormal-coordinates','thm-orthonormal-independent','c2-def-basis'],kind='exercise',optional=True)
s.r('ex-gram-matrix-isometry','Matching pairings determines a length-preserving map',r'''Suppose $v_1,\ldots,v_n$ and $w_1,\ldots,w_n$ are bases of inner product spaces $V,W$ and
\[\ip{v_j}{v_k}=\ip{w_j}{w_k}\quad\text{for all }j,k.\]
Prove that the linear map $T$ prescribed by $Tv_j=w_j$ is bijective and preserves every inner product and norm.''',r'''The basis prescription theorem gives a unique linear map. It maps a basis to a basis, so it is bijective by the basis criterion for isomorphisms. For $u=\sum_ja_jv_j$ and $v=\sum_kb_kv_k$, linearity gives their images by the same coefficients in the $w$ basis. Expanding the pairing yields
\[\ip{Tu}{Tv}=\sum_{j,k}a_j\overline{b_k}\ip{w_j}{w_k}=\sum_{j,k}a_j\overline{b_k}\ip{v_j}{v_k}=\ip{u}{v}.\]
Setting $u=v$ gives equal squared norms, and the norms are nonnegative, so the norms themselves agree. Empty bases give the unique map between zero spaces, where every claim holds.''',2,20,[r'Expand arbitrary vectors in their bases and compare the double sums.'],['c3-thm-linear-map-basis','c3-lem-isomorphism-basis','thm-inner-product-properties','def-norm'],kind='exercise',optional=True)
s.r('ex-complements-of-sums','Orthogonal complements convert sums to intersections',r'''For subspaces $U,W$ of an inner product space, prove
\[(U+W)^\perp=U^\perp\cap W^\perp.\]
If $V$ is finite-dimensional, also prove
\[(U\cap W)^\perp=U^\perp+W^\perp.\]''',r'''A vector orthogonal to every $u+w$ is orthogonal to $U$ by choosing $w=0$ and to $W$ by choosing $u=0$. Conversely a vector orthogonal to both spaces is orthogonal to each sum, by additivity of the inner product. This proves the first equality without a dimension assumption. In finite dimensions apply it to $U^\perp,W^\perp$ to obtain
\[(U^\perp+W^\perp)^\perp=(U^\perp)^\perp\cap(W^\perp)^\perp=U\cap W.\]
Take orthogonal complements again. The double-complement theorem applies to the subspace $U^\perp+W^\perp$ in finite-dimensional $V$ and yields the second asserted equality.''',2,20,[r'Test orthogonality to $u+w$ by first setting one summand to zero.',r'For the second identity, apply the first to the orthogonal complements.'],['def-orthogonal-complement','thm-double-orthogonal','thm-orthogonal-complement-subspace','thm-inner-product-properties','c1-thm-smallest-sum'],kind='exercise',optional=True)
s.r('ex-projection-from-orthogonal-decomposition','Characterizing an orthogonal projection',r'''Let $U$ be a finite-dimensional subspace of an inner product space $V$. Prove that a linear map $P:V\to V$ equals $P_U$ exactly when $Pv\in U$ and $v-Pv\in U^\perp$ for every $v$. Deduce $P_U^2=P_U$ and $\Null P_U=U^\perp$.''',r'''The defining orthogonal decomposition of $v$ is $v=P_Uv+(v-P_Uv)$ with its components in $U$ and $U^\perp$, so $P_U$ has the stated properties. Conversely the two given membership conditions exhibit $v=Pv+(v-Pv)$ as such a decomposition. Uniqueness of the direct sum forces $Pv=P_Uv$ for every $v$, proving equality of maps. If $u\in U$, its decomposition is $u=u+0$, so $P_Uu=u$. Taking $u=P_Uv$ gives $P_U^2v=P_Uv$. Finally $P_Uv=0$ exactly when its decomposition has no $U$ component, which is exactly when $v\in U^\perp$.''',2,20,[r'Use uniqueness in the orthogonal direct sum.'],['def-orthogonal-projection','thm-orthogonal-direct-sum','def-orthogonal-complement','c3-def-null-space'],kind='exercise',optional=True)
s.r('ex-commuting-orthogonal-projections','A product of commuting orthogonal projections',r'''In a finite-dimensional inner product space let $P=P_U$ and $Q=P_W$ for subspaces $U,W$. Prove that $PQ$ is an orthogonal projection onto some subspace exactly when $PQ=QP$. In the commuting case prove $PQ=P_{U\cap W}$.''',r'''For any orthogonal projection $P_U$, orthogonal decomposition gives
\[\ip{P_Ux}{y}=\ip{P_Ux}{P_Uy}=\ip{x}{P_Uy},\]
since the complementary components are orthogonal to $U$ in either slot. Thus both $P$ and $Q$ have this pairing identity.
Assume first $PQ=QP$. For any $x$, $PQx\in U$ by the range of $P$, and $PQx=QPx\in W$, so $PQx\in U\cap W$. If $z\in U\cap W$, then $Pz=Qz=z$, hence $QPz=z$. Applying the pairing identities successively yields $\ip{PQx}{z}=\ip{x}{QPz}=\ip{x}{z}$, so $x-PQx\in(U\cap W)^\perp$. Uniqueness of orthogonal decomposition now gives $PQx=P_{U\cap W}x$ for every input.
Conversely suppose $PQ$ is an orthogonal projection. Its pairing identity gives $\ip{PQx}{y}=\ip{x}{PQy}$. The separate identities for $P,Q$ also give $\ip{PQx}{y}=\ip{x}{QPy}$. Subtracting yields $\ip{x}{(PQ-QP)y}=0$ for every $x,y$. Fix $y$ and choose $x=(PQ-QP)y$ to get its squared norm zero, hence $(PQ-QP)y=0$. This holds for every $y$, so the operators commute.''',4,60,[r'First prove that every orthogonal projection can be moved from one slot of an inner product to the other.',r'In the commuting case identify the range component and the orthogonal remainder.'],['def-orthogonal-projection','thm-orthogonal-direct-sum','def-orthogonal-complement','thm-inner-product-properties','thm-norm-properties','c2-lem-intersection-subspace'],kind='exercise',optional=True)
s.r('ex-affine-nearest-point','Closest point in a translated subspace',r'''For a finite-dimensional subspace $U$, fixed $a\in V$, and $v\in V$, show that the unique closest point to $v$ in $a+U$ is $a+P_U(v-a)$. Determine the distance.''',r'''Every candidate is $a+u$ with $u\in U$, and $\|v-(a+u)\|=\|(v-a)-u\|$. The minimization theorem applied to $v-a$ gives its unique minimizing $u=P_U(v-a)$. Addition of $a$ is injective, so it also gives a unique point in the translated set. The distance is $\|(v-a)-P_U(v-a)\|$. Equivalently its square is $\|v-a\|^2-\|P_U(v-a)\|^2$ by the orthogonality of the two decomposition components and Pythagoras. Both formulas include $U=\{0\}$ and the case $v-a\in U$, where the distance is zero.''',2,20,[r'Translate the distance problem by subtracting $a$ from the target and every candidate.'],['thm-minimization','thm-orthogonal-direct-sum','thm-pythagorean','c3-def-translate','c1-lem-vector-cancellation'],kind='exercise',optional=True)
s.r('ex-riesz-functional-bound','The best constant in a functional bound',r'''Let $\varphi$ be a linear functional on a finite-dimensional inner product space, represented by $w$ through $\varphi(v)=\ip{v}{w}$. Prove that the smallest nonnegative $C$ such that $|\varphi(v)|\le C\|v\|$ for every $v$ is $\|w\|$. If $w\ne0$, exhibit a unit vector attaining equality.''',r'''Cauchy–Schwarz gives $|\varphi(v)|=|\ip{v}{w}|\le\|v\|\|w\|$, so $C=\|w\|$ works. If $w\ne0$, take $v=w/\|w\|$. Norm homogeneity gives $\|v\|=1$, and linearity in the first variable gives $\varphi(v)=\|w\|^2/\|w\|=\|w\|$. Any constant satisfying the bound must therefore be at least $\|w\|$. If $w=0$, the functional is zero, so $C=0$ works and is the least allowed nonnegative number, including on the zero space.''',2,20,[r'Use Cauchy–Schwarz for the bound and test a normalized representing vector for optimality.'],['thm-riesz','thm-cauchy-schwarz','thm-norm-properties','thm-inner-product-properties'],kind='exercise',optional=True)
s.r('ex-hyperplane-distance','Distance to a nonzero functional level set',r'''Let $\varphi\ne0$ be a functional on a finite-dimensional inner product space and let $w$ be its Riesz vector. For $b\in\F$ prove that the unique point of smallest norm satisfying $\varphi(v)=b$ is
\[v_0=\frac b{\|w\|^2}w,\]
and its norm is $|b|/\|w\|$.''',r'''The representing vector cannot be zero because the functional is not zero; thus the denominator is positive. Linearity in the first slot gives $\varphi(v_0)=b$. If $v$ is any other solution, set $h=v-v_0$. Then $\ip{h}{w}=\varphi(h)=0$, so $h$ is orthogonal to $w$ and also to its scalar multiple $v_0$. Pythagoras gives $\|v\|^2=\|v_0\|^2+\|h\|^2\ge\|v_0\|^2$, with equality precisely when $h=0$, proving uniqueness. Finally norm homogeneity gives $\|v_0\|=|b|\|w\|/\|w\|^2=|b|/\|w\|$. For $b=0$ this gives the zero vector, consistent with the same proof.''',3,30,[r'Find a solution parallel to the representing vector and show that all other solutions differ from it orthogonally.'],['thm-riesz','thm-inner-product-properties','thm-pythagorean','thm-norm-properties','def-orthogonal'],kind='exercise',optional=True)
s.r('ex-least-squares-residual','An orthogonality test for least squares',r'''For a linear map $T:V\to W$ with finite-dimensional $V$ and inner product spaces $V,W$, prove that $u\in V$ minimizes $\|Tu-w\|$ exactly when
\[\ip{w-Tu}{Tv}=0\quad\text{for every }v\in V.\]
Describe all minimizing inputs once one of them is known.''',r'''The range is finite-dimensional: images of a finite basis of $V$ span it by linearity. The projection minimization theorem says that a range vector is closest to $w$ exactly when it is $P_{\Range T}w$. By uniqueness of the orthogonal decomposition this is equivalent to its residual belonging to $(\Range T)^\perp$. The displayed condition is exactly that residual orthogonality, because the vectors $Tv$ exhaust the range. Thus it is necessary and sufficient for a minimizing input. If $u_0$ is one minimizing input, every other one has the same image $P_{\Range T}w$, so $Tu=Tu_0$ exactly when $u-u_0\in\Null T$. Consequently all minimizers are $u_0+\Null T$.''',3,35,[r'First minimize over the range, then ask which inputs have the minimizing image.'],['thm-minimization','thm-orthogonal-direct-sum','def-orthogonal-complement','c3-def-range','c3-def-null-space','c2-thm-basis-existence','c3-def-linear-map'],kind='exercise',optional=True)
s.r('ex-pseudoinverse-identities','Two products involving the pseudoinverse',r'''For $T:V\to W$ with $V$ finite-dimensional and both spaces inner product spaces, prove
\[TT^\dagger=P_{\Range T},\qquad T^\dagger T=P_{(\Null T)^\perp}.\]
Deduce $TT^\dagger T=T$ and $T^\dagger TT^\dagger=T^\dagger$.''',r'''Set $K=(\Null T)^\perp$ in $V$. The pseudoinverse is defined by $T^\dagger=(T|_K)^{-1}P_{\Range T}$, where $T|_K:K\to\Range T$ is bijective. Applying $T$ cancels the inverse on that range and gives the first identity. For any $v$, write its orthogonal decomposition as $v=n+k$ with $n\in\Null T$ and $k\in K$. Then $Tv=Tk$ lies in the range, so
\[T^\dagger Tv=(T|_K)^{-1}(Tk)=k=P_Kv.\]
This proves the second identity. Since $Tv$ already belongs to the range, its projection is itself, and the first identity gives $TT^\dagger T=T$. Since every image of $T^\dagger$ belongs to $K$, the second identity gives $T^\dagger TT^\dagger=T^\dagger$. These statements include zero maps and zero-dimensional domains.''',3,35,[r'Use the inverse of the restricted map in the definition, and decompose an input into its kernel component and orthogonal component.'],['def-pseudoinverse','def-orthogonal-projection','thm-orthogonal-direct-sum','c3-def-map-inverse','c3-def-null-space'],kind='exercise',optional=True)
s.r('ex-minimum-norm-right-inverse','The distinguished right inverse of a surjection',r'''Let $T:V\to W$ be surjective between finite-dimensional inner product spaces. Prove that among linear maps $R:W\to V$ with $TR=I_W$, exactly one has $\Range R\subseteq(\Null T)^\perp$. It is $T^\dagger$, and for every right inverse $R$ and every $w\in W$,
\[\|Rw\|^2=\|T^\dagger w\|^2+\|Rw-T^\dagger w\|^2.\]''',r'''Write $K=(\Null T)^\perp$. Surjectivity makes $P_{\Range T}=I_W$, so the definition gives $T^\dagger=(T|_K)^{-1}$. It is linear, has range in $K$, and satisfies $TT^\dagger=I_W$. If a right inverse $R$ also has its range in $K$, then for every $w$ the vectors $Rw$ and $T^\dagger w$ are both in $K$ and both map to $w$. Injectivity of $T|_K$ gives equality, proving uniqueness. For an arbitrary right inverse, $T(Rw-T^\dagger w)=w-w=0$, so the difference belongs to $\Null T$. The vector $T^\dagger w$ belongs to $K$, making them orthogonal. Pythagoras applied to their sum $Rw$ gives the asserted identity. In particular the pseudoinverse has the least possible output norm at each input, with equality exactly when the two outputs agree.''',4,60,[r'Compare any right inverse with the inverse of $T$ restricted to the orthogonal complement of its kernel.',r'The difference of the two outputs is killed by $T$.'],['def-pseudoinverse','thm-pythagorean','thm-orthogonal-direct-sum','def-orthogonal-complement','c3-def-map-inverse','c3-thm-invertible-bijective'],kind='exercise',optional=True)
s.r('ex-completion-preserving-functional','Completing coordinates adapted to a functional',r'''Let $V$ be an $n$-dimensional inner product space with $n\ge1$, and let $\varphi\ne0$ be a linear functional. Prove that there is an orthonormal basis $e_1,\ldots,e_n$ with
\[\varphi(e_1)>0\text{ real},\qquad\varphi(e_j)=0\ (j\ge2).\]
Prove that the first vector of every such basis is the same, and identify the remaining span.''',r'''Let $w\ne0$ represent $\varphi$ and set $e_1=w/\|w\|$. This is a unit vector, so the orthonormal extension theorem completes it to a basis. Its functional value is $\ip{w/\|w\|}{w}=\|w\|>0$. For $j\ge2$, orthogonality to $e_1$ gives $\varphi(e_j)=\ip{e_j}{w}=\|w\|\ip{e_j}{e_1}=0$.
Conversely suppose $f_1,\ldots,f_n$ is a basis with the asserted properties. The Riesz formula in this basis gives $w=\sum_j\overline{\varphi(f_j)}f_j=\varphi(f_1)f_1$, since its first coefficient is real positive and the others vanish. Taking norms gives $\|w\|=\varphi(f_1)$, so $f_1=w/\|w\|=e_1$, proving the uniqueness claimed. Finally for $v=\sum_ja_je_j$, linearity gives $\varphi(v)=a_1\|w\|$. It vanishes exactly when $a_1=0$. Hence the remaining basis vectors span $\Null\varphi$. For $n=1$ that remaining list is empty and the kernel is zero, as the same equation shows.''',3,40,[r'Normalize the Riesz vector and extend it orthonormally.',r'For uniqueness, use the representing-vector formula in any proposed adapted basis.'],['thm-riesz','thm-orthonormal-extension','thm-inner-product-properties','thm-norm-properties','c3-def-null-space','c2-thm-basis-coordinates'],kind='exercise',optional=True)
s.card('ex-weighted-ip','ex-positive-weight-characterization',r'Which real coordinate weights define a positive definite inner product?',r'Every weight must be strictly positive.')
s.card('ex-polarization','ex-inner-product-from-norm',r'How do norms recover the imaginary part of a complex inner product?',r'$4\operatorname{Im}\ip{u}{v}=\|u+iv\|^2-\|u-iv\|^2$ for the convention linear in the first slot.')
s.card('ex-complement-sum','ex-complements-of-sums',r'What is $(U+W)^\perp$?',r'$U^\perp\cap W^\perp$.')
s.card('ex-projection-product','ex-commuting-orthogonal-projections',r'When is a product of two orthogonal projections again an orthogonal projection?',r'Exactly when the two projections commute; the product then projects onto the intersection.')
s.card('ex-affine-projection','ex-affine-nearest-point',r'What is the closest point to $v$ in $a+U$?',r'$a+P_U(v-a)$.')
s.card('ex-functional-bound','ex-riesz-functional-bound',r'What is the sharp bound constant for a functional represented by $w$?',r'$|\varphi(v)|\le\|w\|\|v\|$, and the least nonnegative constant is $\|w\|$.')
s.card('ex-least-squares','ex-least-squares-residual',r'What characterizes a least-squares residual?',r'It is orthogonal to the range of the map.')
s.card('ex-pseudoinverse-products','ex-pseudoinverse-identities',r'What are $TT^\dagger$ and $T^\dagger T$?',r'They are the orthogonal projections onto $\Range T$ and $(\Null T)^\perp$, respectively.')
s.write()
