from common import Section
s=Section('6b')
s.p('intro-orthonormal-bases','Coordinates adapted to an inner product',r'''An orthonormal list combines independence with simple coefficient formulas. We construct such lists while preserving successive spans, then apply them to triangular matrices and linear functionals.''',197)
s.d('def-orthonormal','Orthonormal lists',r'''A list $e_1,\ldots,e_m$ in an inner product space is orthonormal if $\ip{e_j}{e_k}=1$ when $j=k$ and $\ip{e_j}{e_k}=0$ when $j\ne k$. Equivalently, every vector has norm one and distinct members are orthogonal. The empty list satisfies this definition.''','6.22',197)
s.r('ex-standard-orthonormal','Coordinate examples of orthonormal lists',r'''In the standard inner product on $\F^n$, the standard basis is orthonormal. In $\F^3$ the vectors
\[u=\frac{(1,1,1)}{\sqrt3},\quad v=\frac{(-1,1,0)}{\sqrt2},\quad w=\frac{(1,1,-2)}{\sqrt6}\]
form an orthonormal list, and so does the initial list $u,v$.''',r'''For standard vectors $e_j,e_k$, the coordinate inner product is one when their nonzero coordinates have the same index and zero otherwise. This proves the first claim, including the empty standard basis. For the displayed three vectors, the squared norms are $(1+1+1)/3=1$, $(1+1)/2=1$, and $(1+1+4)/6=1$. The three distinct inner products are $(-1+1+0)/\sqrt6=0$, $(1+1-2)/\sqrt{18}=0$, and $(-1+1+0)/\sqrt{12}=0$. The reversed inner products are their conjugates and hence zero. Thus the list is orthonormal, and deleting its last vector retains every required equality.''',1,10,[r'Compute the three squared norms and the three distinct pairings.'],['def-orthonormal','c6-thm-standard-inner-product','c6-thm-inner-product-properties'],'6.23(a)–(c)',197,'example')
s.add('theorem','thm-trigonometric-calculus-facts','Analytic facts for trigonometric examples',r'''The real functions sine and cosine are continuous and satisfy their usual product-to-sum identities and $\sin^2t+\cos^2t=1$. For an integer $k\ne0$,
\[\int_{-\pi}^{\pi}\cos(kt)\,dt=\int_{-\pi}^{\pi}\sin(kt)\,dt=0,\qquad \int_{-\pi}^{\pi}1\,dt=2\pi.\]
For a nonnegative integer $j$,
\[\int_{-1}^1t^j\,dt=\begin{cases}0&j\text{ odd},\\2/(j+1)&j\text{ even}.\end{cases}\]
On this interval the cosine moments $M_j=\int_{-1}^1t^j\cos(\pi t)\,dt$ satisfy
\[M_0=M_1=M_3=M_5=0,\qquad M_2=-\frac4{\pi^2},\qquad M_4=-\frac8{\pi^2}+\frac{48}{\pi^4}.\]
These integrals use the usual Riemann integral.''',page=197)
s.note('remark-trigonometric-calculus-faith','Analytic prerequisites taken on faith',r'''The trigonometric identities and integral evaluations in the preceding theorem are taken on faith. Their calculus proofs lie outside this linear algebra module; all uses of them below are explicit.''',197)
s.r('ex-trigonometric-orthonormal','A finite orthonormal trigonometric list',r'''For every positive integer $n$, the list
\[\frac1{\sqrt{2\pi}},\quad\frac{\cos t}{\sqrt\pi},\ldots,\frac{\cos(nt)}{\sqrt\pi},\quad\frac{\sin t}{\sqrt\pi},\ldots,\frac{\sin(nt)}{\sqrt\pi}\]
is orthonormal in the real space $C[-\pi,\pi]$ with inner product $\ip{f}{g}=\int_{-\pi}^{\pi}fg$.''',r'''The continuous-integral inner-product result applies on this interval. The constant vector has squared norm $(2\pi)/(2\pi)=1$, and its inner product with each other vector is zero by the integral identities. For positive integers $j,k$, product-to-sum gives
\[2\cos(jt)\cos(kt)=\cos((j-k)t)+\cos((j+k)t),\]
\[2\sin(jt)\sin(kt)=\cos((j-k)t)-\cos((j+k)t),\]
\[2\sin(jt)\cos(kt)=\sin((j+k)t)+\sin((j-k)t).\]
When $j\ne k$, all cosine frequencies in the first two lines are nonzero, so their integrals vanish. When $j=k$, the difference-frequency cosine is the constant one and the other cosine has nonzero frequency, giving integral $\pi$ in each case. In the last line every sine integral is zero; a zero frequency gives the identically zero function. Dividing by the normalization factors therefore gives one on each diagonal pairing and zero on every distinct pairing, as required.''',2,20,[r'Convert each product into a sum of trigonometric functions with integer frequencies.'],['def-orthonormal','thm-trigonometric-calculus-facts','c6-ex-continuous-integral-inner-product','c6-thm-continuous-integral-facts'],'6.23(d)',197,'example')
s.r('ex-normalization-not-orthonormal','Unit norm does not imply orthogonality',r'''In $\Poly_2(\R)$ with $\ip{p}{q}=\int_{-1}^1pq$, the list $1,x,x^2$ is not orthonormal. Even its normalized list
\[\frac1{\sqrt2},\quad\sqrt{\frac32}x,\quad\sqrt{\frac52}x^2\]
is not orthonormal.''',r'''The squared norms of $1,x,x^2$ are respectively $2,2/3,2/5$ by the monomial integral formulas. Thus none has norm one. Scaling by the reciprocals of these positive norms gives the displayed unit vectors. The inner products of the middle vector with the first and third vanish, because the relevant integrands are odd powers. But the first and third have inner product $\frac{\sqrt5}{2}\int_{-1}^1t^2dt=\sqrt5/3\ne0$. Hence normalization alone does not produce an orthonormal list.''',1,10,[r'Check the pairing between the normalized constant and quadratic.'],['def-orthonormal','thm-trigonometric-calculus-facts','c6-thm-polynomial-integral-inner-product','c6-thm-norm-properties'],'6.23(e)',197,'example')
s.r('thm-orthonormal-norm','Norm of a combination of orthonormal vectors',r'''If $e_1,\ldots,e_m$ is orthonormal, then
\[\left\|\sum_{j=1}^m a_je_j\right\|^2=\sum_{j=1}^m|a_j|^2\qquad(a_j\in\F).\]''',r'''Expanding the squared norm by linearity in the first variable and conjugate linearity in the second gives
\[\left\langle\sum_ja_je_j,\sum_ka_ke_k\right\rangle=\sum_{j,k}a_j\overline{a_k}\ip{e_j}{e_k}.\]
Orthonormality makes every term with $j\ne k$ zero and makes the remaining terms $a_j\overline{a_j}=|a_j|^2$. For $m=0$ the vector is zero and both sums are zero, so the formula still holds.''',1,10,[r'Expand the inner product of the combination with itself.'],['def-orthonormal','c6-def-norm','c6-thm-inner-product-properties','c4-thm-complex-properties'],'6.24',198)
s.r('thm-orthonormal-independent','Every orthonormal list is independent',r'''An orthonormal list is linearly independent.''',r'''If $\sum_ja_je_j=0$, the preceding norm identity gives $\sum_j|a_j|^2=0$. Each summand is a nonnegative real number, so each is zero. Modulus is zero only for the zero scalar; hence every $a_j=0$. This is linear independence, and it also includes the empty list.''',1,10,[r'Take the squared norm of a proposed zero relation.'],['thm-orthonormal-norm','c2-def-linear-independence','c4-thm-complex-properties','c1-foundations'],'6.25',198)
s.r('thm-bessel','Bessel inequality with its equality condition',r'''For an orthonormal list $e_1,\ldots,e_m$ and any $v$,
\[\sum_{j=1}^m|\ip{v}{e_j}|^2\le\|v\|^2.\]
Equality holds exactly when $v\in\Span(e_1,\ldots,e_m)$.''',r'''Set $u=\sum_j\ip{v}{e_j}e_j$ and $w=v-u$. For each $k$, expanding in the first variable gives $\ip{w}{e_k}=\ip{v}{e_k}-\ip{v}{e_k}=0$. Conjugate linearity in the second variable then gives $\ip{w}{u}=0$. Pythagoras and the orthonormal norm formula yield
\[\|v\|^2=\|u\|^2+\|w\|^2=\sum_j|\ip{v}{e_j}|^2+\|w\|^2.\]
The last term is nonnegative, proving the inequality. It is zero exactly when $w=0$, which implies $v=u$ is in the indicated span. Conversely if $v=\sum_ja_je_j$, taking inner products with $e_k$ gives $a_k=\ip{v}{e_k}$, so $v=u$ and equality holds. For the empty list, $u=0$, the inequality is $0\le\|v\|^2$, and equality means $v=0$, exactly its empty span.''',2,20,[r'Subtract the vector whose orthonormal coefficients are the inner products with $v$.',r'Apply Pythagoras to this vector and the remainder.'],['def-orthonormal','thm-orthonormal-norm','c6-thm-inner-product-properties','c6-thm-pythagorean','c6-thm-norm-properties','c2-def-span'],'6.26',198)
s.d('def-orthonormal-basis','Orthonormal bases',r'''An orthonormal basis is a basis whose ordered list is orthonormal. The zero space has the empty orthonormal basis.''','6.27',199)
s.r('thm-full-orthonormal','An orthonormal list of full length is a basis',r'''If $V$ is finite-dimensional, every orthonormal list of length $\dim V$ is an orthonormal basis.''',r'''The list is independent by the orthonormal independence theorem. Its length equals the dimension, so the full-length independence criterion makes it a basis. It was already orthonormal, which supplies the remaining condition. In dimension zero this reasoning applies to the empty list.''',1,10,[r'Combine independence with the length of the list.'],['thm-orthonormal-independent','c2-thm-full-length-independent','def-orthonormal-basis'],'6.28',199)
s.r('ex-four-dimensional-orthonormal','A nonstandard orthonormal basis in four coordinates',r'''The following list is an orthonormal basis of $\F^4$ with its standard inner product:
\[e_1=\tfrac12(1,1,1,1),\quad e_2=\tfrac12(1,1,-1,-1),\quad e_3=\tfrac12(1,-1,-1,1),\quad e_4=\tfrac12(-1,1,-1,1).\]''',r'''Each squared norm is $4/4=1$. Multiplying the six pairings by four gives, in the order $(1,2),(1,3),(1,4),(2,3),(2,4),(3,4)$,
\[1+1-1-1,\quad1-1-1+1,\quad-1+1-1+1,\quad1-1+1-1,\quad-1+1+1-1,\quad-1-1+1+1.\]
Every sum is zero. The reversed pairings are conjugates and also zero. Thus the list is orthonormal and has length four, which is the dimension, so the full-length theorem makes it an orthonormal basis.''',1,10,[r'Each norm is one; check all six pairings and then count.'],['thm-full-orthonormal','c6-thm-standard-inner-product','c2-ex-coordinate-dimension'],'6.29',199,'example')
s.r('thm-orthonormal-coordinates','Orthonormal expansions, Parseval identity, and inner products',r'''If $e_1,\ldots,e_n$ is an orthonormal basis of $V$, then for $u,v\in V$,
\[v=\sum_j\ip{v}{e_j}e_j,\qquad\|v\|^2=\sum_j|\ip{v}{e_j}|^2,\qquad\ip{u}{v}=\sum_j\ip{u}{e_j}\overline{\ip{v}{e_j}}.\]''',r'''Expand $v=\sum_ja_je_j$ using the basis property. Taking the inner product with $e_k$ gives $\ip{v}{e_k}=\sum_ja_j\ip{e_j}{e_k}=a_k$. This proves the expansion. Substituting these coefficients into the orthonormal norm formula proves the squared-norm identity. Finally conjugate linearity in the second variable gives
\[\ip{u}{v}=\left\langle u,\sum_j\ip{v}{e_j}e_j\right\rangle=\sum_j\overline{\ip{v}{e_j}}\ip{u}{e_j}.\]
This is the claimed inner-product formula. If the basis is empty, $V=\{0\}$ and all three identities have both sides zero.''',2,15,[r'Inner product with $e_k$ extracts the $k$th coordinate.'],['def-orthonormal-basis','def-orthonormal','thm-orthonormal-norm','c2-thm-basis-coordinates','c6-thm-inner-product-properties'],'6.30',200)
s.r('ex-orthonormal-coefficients','Extracting four coordinates by inner products',r'''For the orthonormal basis in the preceding four-coordinate example,
\[(1,2,4,7)=7e_1-4e_2+e_3+2e_4.\]''',r'''The four inner products of $(1,2,4,7)$ with the basis vectors are $(1+2+4+7)/2=7$, $(1+2-4-7)/2=-4$, $(1-2-4+7)/2=1$, and $(-1+2-4+7)/2=2$. The orthonormal expansion formula gives exactly the asserted combination.''',1,10,[r'Compute four inner products rather than solve four equations.'],['ex-four-dimensional-orthonormal','thm-orthonormal-coordinates','c6-thm-standard-inner-product'],'6.31',200,'example')
s.r('thm-gram-schmidt','Gram–Schmidt orthonormalization',r'''For an independent list $v_1,\ldots,v_m$, define successively
\[f_k=v_k-\sum_{j<k}\frac{\ip{v_k}{f_j}}{\|f_j\|^2}f_j,\qquad e_k=\frac{f_k}{\|f_k\|}\quad(1\le k\le m).\]
All denominators are nonzero. The resulting list is orthonormal, and for every $k$ its first $k$ vectors span the same subspace as $v_1,\ldots,v_k$.''',r'''We induct on $k$, also tracking the spans of the $f$ vectors. At the initial stage the preceding lists are empty. Assume $f_1,\ldots,f_{k-1}$ are nonzero and pairwise orthogonal, and their span is the span of $v_1,\ldots,v_{k-1}$. Their squared norms are positive, so the formula for $f_k$ is defined. If $f_k=0$, that formula expresses $v_k$ in the span of the preceding $f$ vectors and hence of the preceding $v$ vectors. Moving this expression to one side would give a relation on the original independent list with coefficient one at $v_k$, a contradiction. Thus $f_k\ne0$.
For $i<k$, expand the inner product of the formula with $f_i$. All terms with $j\ne i$ vanish by the induction hypothesis, and the remaining one is
\[\ip{f_k}{f_i}=\ip{v_k}{f_i}-\frac{\ip{v_k}{f_i}}{\|f_i\|^2}\ip{f_i}{f_i}=0.\]
Conjugate symmetry gives orthogonality in the other order. Moreover the defining expression puts $f_k$ in $\Span(v_1,\ldots,v_k)$, and solving it for $v_k$ puts $v_k$ in $\Span(f_1,\ldots,f_k)$. Together with the induction equality of preceding spans, this proves equality of the new spans in both directions. This completes the induction.
Each $e_k$ is a nonzero real scalar multiple of $f_k$, so it preserves these spans. Norm homogeneity gives $\|e_k\|=1$, and scalar extraction from the pairings preserves the zero pairings of distinct $f$ vectors. Hence the $e$ list is orthonormal. For $m=0$ no divisions are made and every conclusion is vacuous.''',3,45,[r'Prove nonvanishing, orthogonality, and preservation of the successive spans together by induction.',r'A zero remainder would put the next original vector in the span of its predecessors.'],['c2-def-linear-independence','c2-def-span','c6-thm-inner-product-properties','c6-thm-norm-properties','def-orthonormal'],'6.32',201)
s.r('ex-orthonormal-polynomials','Orthonormalizing quadratic polynomials',r'''In $\Poly_2(\R)$ with $\ip{p}{q}=\int_{-1}^1pq$, Gram–Schmidt applied to $1,x,x^2$ gives
\[e_1=\frac1{\sqrt2},\qquad e_2=\sqrt{\frac32}x,\qquad e_3=\sqrt{\frac{45}8}\left(x^2-\frac13\right).\]
This is an orthonormal basis.''',r'''The original list is the standard polynomial basis and hence independent. In the unnormalized procedure, $f_1=1$ has squared norm two. Because $\ip{x}{1}=0$, the next remainder is $f_2=x$, with squared norm $2/3$. Next $\ip{x^2}{1}=2/3$ and $\ip{x^2}{x}=0$, so $f_3=x^2-(2/3)/2=x^2-1/3$. Its squared norm is
\[\int_{-1}^1(t^4-\tfrac23t^2+\tfrac19)\,dt=\frac25-\frac49+\frac29=\frac8{45}.\]
Dividing each remainder by its positive norm gives the displayed list. Gram–Schmidt proves it orthonormal and preserves the whole original span, which is $\Poly_2(\R)$. Its independence follows from orthonormality, so it is a basis.''',2,20,[r'Odd monomial integrals vanish; compute the three successive remainders.'],['thm-gram-schmidt','thm-orthonormal-independent','thm-trigonometric-calculus-facts','c6-thm-polynomial-integral-inner-product','c2-ex-polynomial-standard-basis'],'6.34',202,'example')
s.r('thm-orthonormal-basis-existence','Finite-dimensional inner product spaces have orthonormal bases',r'''Every finite-dimensional inner product space has an orthonormal basis.''',r'''Choose a basis using finite-dimensional basis existence. Apply Gram–Schmidt to this independent list. The output is orthonormal and spans the same whole space; orthonormal independence makes it a basis. For the zero space the chosen basis and output are both empty, so the construction remains valid.''',1,10,[r'Apply Gram–Schmidt to any basis.'],['c2-thm-basis-existence','thm-gram-schmidt','thm-orthonormal-independent','def-orthonormal-basis'],'6.35',202)
s.r('thm-orthonormal-extension','Extending an orthonormal list',r'''In a finite-dimensional inner product space, every orthonormal list extends to an orthonormal basis without changing its original vectors.''',r'''The list is independent, so extend it to an ordinary basis. Apply Gram–Schmidt to that basis in the same order. At each position belonging to the original orthonormal list, all pairings with earlier vectors are zero and the original norm is one. Inductively the formula therefore leaves each original vector unchanged. The full output is an orthonormal basis by preservation of spans and orthonormal independence, and it begins with the given list. An empty original list is covered by ordinary orthonormal basis existence.''',2,15,[r'Extend to an arbitrary basis first; inspect what Gram–Schmidt does to the original prefix.'],['thm-orthonormal-independent','c2-thm-extend-independent','thm-gram-schmidt','thm-orthonormal-basis-existence'],'6.36',203)
s.r('thm-orthonormal-triangular','Triangularization in an orthonormal basis',r'''An operator on a finite-dimensional inner product space has an upper-triangular matrix in some orthonormal basis exactly when its minimal polynomial splits into linear factors over $\F$.''',r'''If such an orthonormal basis exists, it is a basis, so the earlier triangularization criterion makes the minimal polynomial split. Conversely if that polynomial splits, that criterion supplies a basis $v_1,\ldots,v_n$ making the matrix triangular. Each initial span is invariant. Gram–Schmidt produces an orthonormal basis $e_1,\ldots,e_n$ with exactly the same initial spans. Hence those new initial spans remain invariant, and the invariant-initial-span criterion makes the new matrix triangular. The argument includes the empty basis and minimal polynomial one on the zero space.''',2,20,[r'Gram–Schmidt preserves every initial span, which is the property controlling triangularity.'],['c5-thm-triangularizable-splitting','c5-thm-triangular-invariant','thm-gram-schmidt','def-orthonormal-basis'],'6.37',203)
s.r('thm-schur','Schur triangularization theorem',r'''Every operator on a finite-dimensional complex inner product space has an upper-triangular matrix in some orthonormal basis.''',r'''The minimal polynomial splits into complex linear factors by complex polynomial factorization, including the empty product when it is one. The orthonormal triangularization criterion therefore supplies the required basis.''',1,10,[r'Use complex factorization in the preceding criterion.'],['thm-orthonormal-triangular','c5-def-minimal-polynomial','c4-thm-complex-factorization'],'6.38',204)
s.d('def-inner-product-functional','Linear functionals and the dual revisited',r'''A linear functional on $V$ is a linear map $V\to\F$. The dual space $\dual{V}=\Lin(V,\F)$ consists of these maps with pointwise vector operations, as in the earlier dual-space section.''','6.39',204)
s.r('ex-coordinate-riesz','A coordinate functional as an inner product',r'''On $\F^3$ with the standard inner product, $\varphi(z_1,z_2,z_3)=2z_1-5z_2+z_3$ is a linear functional and equals $\ip{z}{w}$ for $w=(2,-5,1)$.''',r'''The coordinate linearity theorem shows that this scalar-valued map is linear. Since the three entries of $w$ are real, their conjugates are unchanged, and the standard inner-product formula gives $\ip{z}{w}=2z_1-5z_2+z_3=\varphi(z)$ for every input.''',1,10,[r'Remember the conjugates in the second slot of the complex inner product.'],['def-inner-product-functional','c3-thm-coordinate-linear-maps','c6-thm-standard-inner-product'],'6.40',204,'example')
s.r('ex-integral-functional','A polynomial functional defined by a cosine weight',r'''For each nonnegative integer $m$, the formula
\[\varphi(p)=\int_{-1}^1p(t)\cos(\pi t)\,dt\]
defines a linear functional on $\Poly_m(\R)$; in particular it does so for $m=5$.''',r'''Polynomials and the cosine factor are continuous, so their product is integrable on this interval by the accepted integral facts. For polynomials $p,q$ and a real scalar $a$, distributivity of pointwise multiplication and linearity of the integral give $\varphi(p+q)=\varphi(p)+\varphi(q)$ and $\varphi(ap)=a\varphi(p)$. Its values are real, proving that it is a linear functional with the asserted domain.''',1,10,[r'Use linearity of the integral after distributing the cosine factor.'],['def-inner-product-functional','c6-thm-continuous-integral-facts','thm-trigonometric-calculus-facts','c2-thm-bounded-polynomials'],'6.41',204,'example')
s.r('thm-riesz','Riesz representation for finite-dimensional inner product spaces',r'''If $V$ is a finite-dimensional inner product space and $\varphi\in\dual{V}$, there is a unique $v\in V$ such that $\varphi(u)=\ip{u}{v}$ for every $u\in V$. In any orthonormal basis $e_1,\ldots,e_n$, it is
\[v=\sum_{j=1}^n\overline{\varphi(e_j)}e_j.\]''',r'''Choose an orthonormal basis and define $v$ by the displayed formula. Expansion of $u$ and linearity of $\varphi$ give
\[\varphi(u)=\sum_j\ip{u}{e_j}\varphi(e_j).\]
On the other hand conjugate linearity in the second variable and conjugation twice give
\[\ip{u}{v}=\sum_j\overline{\overline{\varphi(e_j)}}\ip{u}{e_j}=\sum_j\varphi(e_j)\ip{u}{e_j}.\]
Thus this $v$ represents the functional. If both $v$ and $w$ represent it, subtraction gives $\ip{u}{v-w}=0$ for all $u$. In particular $u=v-w$ gives $\|v-w\|^2=0$, so $v=w$. On the zero space the formula is the empty sum zero and every functional is zero by preservation of zero, so existence and uniqueness still hold.''',3,30,[r'Expand each input in an orthonormal basis.',r'The coefficients of the representing vector need conjugation because it occurs in the second slot.'],['def-inner-product-functional','thm-orthonormal-basis-existence','thm-orthonormal-coordinates','c6-thm-inner-product-properties','c6-thm-norm-properties','c4-thm-complex-properties','c3-thm-linear-zero'],'6.42',205)
s.r('ex-polynomial-riesz','Explicit representing polynomials for the cosine functional',r'''With $\ip{p}{q}=\int_{-1}^1pq$, the cosine functional is represented on $\Poly_2(\R)$ by
\[q_2(x)=\frac{15}{2\pi^2}(1-3x^2).\]
On $\Poly_5(\R)$ it is represented by
\[q_5(x)=\frac{105}{8\pi^4}\big((27-2\pi^2)+(24\pi^2-270)x^2+(315-30\pi^2)x^4\big).\]''',r'''Equality of two linear functionals follows from equality on a basis, so it suffices to test monomials. For $q_2$, the integrals against $1,x,x^2$ are respectively
\[\frac{15}{2\pi^2}(2-3\cdot\tfrac23)=0,\quad0,\quad\frac{15}{2\pi^2}(\tfrac23-3\cdot\tfrac25)=-\frac4{\pi^2}.\]
These are precisely the cosine moments $M_0,M_1,M_2$.
For the second claim write $h=\pi^2$, $K=105/(8h^2)$, $A=27-2h$, $B=24h-270$, and $C=315-30h$. Then $q_5=K(A+Bx^2+Cx^4)$. All integrals against odd monomials of degree at most five vanish because the resulting powers are odd, matching $M_1,M_3,M_5$. For the three even monomials the integral is $2K(A/(r+1)+B/(r+3)+C/(r+5))$ for $r=0,2,4$. Direct substitution gives
\[A+B/3+C/5=0,\quad A/3+B/5+C/7=-16h/105,\]
\[A/5+B/7+C/9=(192-32h)/105.\]
Multiplication by $2K=105/(4h^2)$ therefore gives respectively $0,-4/h,48/h^2-8/h$, equal to $M_0,M_2,M_4$. Thus both asserted integral equalities hold on the relevant monomial bases, and linearity extends them to all polynomials in those spaces. Riesz uniqueness makes these the representing polynomials.''',3,35,[r'Test the proposed equality only on the monomial basis.',r'Odd moments vanish; only two or three even moments need checking.'],['thm-riesz','ex-integral-functional','thm-trigonometric-calculus-facts','c6-thm-polynomial-integral-inner-product','c2-ex-polynomial-standard-basis','c3-thm-linear-map-basis'],'6.44',206,'example')
s.r('cor-riesz-basis-independence','The representing-vector formula is independent of the basis',r'''For a fixed linear functional, the sum $\sum_j\overline{\varphi(e_j)}e_j$ has the same value for every orthonormal basis of the finite-dimensional space.''',r'''For each chosen orthonormal basis the Riesz formula gives a vector representing the same functional on every input. The uniqueness part of Riesz representation equates any two such vectors. This proves independence from the choice of orthonormal basis.''',1,10,[r'Use the uniqueness of the represented vector, not a change-of-basis computation.'],['thm-riesz'],page=206,kind='corollary')
s.card('orthonormal','def-orthonormal',r'What pairwise inner-product equations define an orthonormal list?',r'$\ip{e_j}{e_k}=1$ for $j=k$ and zero for $j\ne k$.')
s.card('bessel','thm-bessel',r'State Bessel inequality and its equality condition.',r'$\sum_j|\ip{v}{e_j}|^2\le\|v\|^2$, with equality exactly when $v$ is in the span of the orthonormal list.')
s.card('orthonormal-coordinate','thm-orthonormal-coordinates',r'What is the $j$th coordinate of $v$ in an orthonormal basis?',r'$\ip{v}{e_j}$.')
s.card('gram-schmidt-remainder','thm-gram-schmidt',r'Why can no remainder in Gram–Schmidt be zero for an independent input list?',r'A zero remainder would express the next original vector as a combination of its predecessors.')
s.card('gram-schmidt-spans','thm-gram-schmidt',r'Which spans does Gram–Schmidt preserve?',r'Every initial span: $\Span(v_1,\ldots,v_k)=\Span(e_1,\ldots,e_k)$.')
s.card('orthonormal-extension','thm-orthonormal-extension',r'Can an orthonormal list be completed without changing its vectors?',r'Yes, in a finite-dimensional inner product space it extends to an orthonormal basis.')
s.card('schur','thm-schur',r'State Schur triangularization.',r'Every operator on a finite-dimensional complex inner product space is upper triangular in some orthonormal basis.')
s.card('riesz','thm-riesz',r'How does a vector represent a linear functional in a finite-dimensional inner product space?',r'There is a unique $v$ with $\varphi(u)=\ip{u}{v}$ for all $u$.')
s.card('riesz-conjugates','thm-riesz',r'What is the representing vector in an orthonormal basis?',r'$v=\sum_j\overline{\varphi(e_j)}e_j$; the coefficients are conjugated because $v$ occupies the second slot.')
s.write()
