from common import Section
s=Section('8d')
s.p('intro-trace','A scalar attached to an operator',r'''The sum of the diagonal entries of a matrix survives a change of basis. This lets us define trace for an operator and connect it to eigenvalue multiplicities. Spaces in this section are finite-dimensional over $\F$, with the complex-field hypothesis stated where it is needed.''',326)
s.d('def-matrix-trace','Trace of a square matrix',r'''For $A\in\F^{n,n}$ define $\tr A=\sum_{j=1}^n A_{jj}$. The trace of the empty square matrix is the empty sum zero.''','8.47',326)
s.r('ex-matrix-trace','Reading the trace of a matrix',r'''For
\[A=\begin{pmatrix}3&-1&-2\\5&2&-3\\1&6&0\end{pmatrix},\qquad \tr A=5.\]''',r'''The diagonal entries have equal row and column indices and are $3,2,0$. Their sum is $3+2+0=5$, exactly the definition of trace.''',1,10,[r'Only the entries with equal row and column indices contribute.'],['def-matrix-trace'],'8.48',326,'example')
s.r('thm-matrix-trace-cyclic','Interchanging two rectangular factors inside a trace',r'''For $A\in\F^{m,n}$ and $B\in\F^{n,m}$,
\[\tr(AB)=\tr(BA).\]''',r'''The entry formula gives
\[\tr(AB)=\sum_{j=1}^m\sum_{k=1}^n A_{jk}B_{kj}.\]
These are finitely many scalar terms, so associativity and commutativity of scalar addition allow the order of summation to be interchanged. Commutativity of scalar multiplication then gives
\[\sum_{k=1}^n\sum_{j=1}^mB_{kj}A_{jk}=\sum_{k=1}^n(BA)_{kk}=\tr(BA).\]
If $m=0$ or $n=0$, both double sums contain no terms, while any remaining diagonal entries in the product are empty sums zero. Thus the identity also holds in these cases.''',2,15,[r'Write the two traces as double sums.'],['def-matrix-trace','c3-def-matrix-product','c1-def-field'],'8.49',326)
s.r('thm-trace-basis-independence','Matrix trace does not depend on the operator basis',r'''The matrices representing a fixed operator in any two bases have the same trace.''',r'''The change-of-basis formula makes the two matrices $A$ and $B$ related by $A=C^{-1}BC$ for an invertible matrix $C$. The two-factor trace identity and matrix associativity give
\[\tr A=\tr((C^{-1}B)C)=\tr(C(C^{-1}B))=\tr((CC^{-1})B)=\tr B.\]
The inverse and identity matrix laws justify the last step. This argument includes empty matrices for a zero-dimensional space.''',2,15,[r'Use the similarity relation and move the final change-of-basis factor to the front inside the trace.'],['thm-matrix-trace-cyclic','c3-thm-change-basis','c3-lem-matrix-product-laws','c3-def-invertible-matrix','c3-lem-identity-matrix-laws'],'8.50',327)
s.d('def-operator-trace','Trace of an operator',r'''For $T\in\Lin(V)$, define $\tr T$ to be the trace of its matrix in any basis of $V$. The preceding basis-independence result makes this a well-defined scalar. The trace on the zero space is zero.''','8.51',327)
s.r('thm-trace-eigenvalues','Complex trace is the sum of eigenvalues with multiplicities',r'''For an operator on a finite-dimensional complex space, with distinct eigenvalues $\lambda_1,\ldots,\lambda_r$ of multiplicities $d_1,\ldots,d_r$,
\[\tr T=\sum_{j=1}^r d_j\lambda_j.\]''',r'''The generalized eigenspace decomposition gives a direct sum of the spaces $G(\lambda_j,T)$, whose dimensions are $d_j$. On each such space the restriction of $T-\lambda_jI$ is nilpotent. The nilpotent triangularization result supplies a basis there with strictly upper-triangular matrix for that restriction. Adding $\lambda_jI$ gives a triangular matrix for $T$ restricted to that space, with $d_j$ diagonal entries equal to $\lambda_j$. Concatenate these bases across the direct sum. Independence follows by grouping a zero relation into the direct summands, and spanning follows from their sum being all of $V$. Each summand is invariant under $T$, so this concatenated basis gives a block diagonal matrix, whose blocks have the specified diagonals. Summing all diagonal entries yields $\sum_jd_j\lambda_j$. Basis independence then makes it the trace of $T$. On the zero space the decomposition and sum are empty and the trace is zero.''',2,20,[r'Choose triangular bases separately on the generalized eigenspaces and concatenate them.'],['def-operator-trace','thm-trace-basis-independence','def-eigenvalue-multiplicity','thm-generalized-eigenspace-decomposition','thm-generalized-restriction-nilpotent','thm-nilpotent-triangular','c3-def-map-matrix','c1-thm-direct-zero'],'8.52',328)
s.r('ex-operator-trace','An operator with a real trace and nonreal eigenvalues',r'''On $\C^3$ define
\[T(x,y,z)=(3x-y-2z,3x+2y-3z,x+2y).\]
Its trace is five, and its eigenvalues are $1,2+3i,2-3i$, each with multiplicity one.''',r'''The coordinate formula is linear, and its standard matrix has diagonal $3,2,0$, so the trace is five. Direct substitution gives
\[T(1,0,1)=(1,0,1),\]
\[T(i,1+i,1)=(-3+2i,-1+5i,2+3i)=(2+3i)(i,1+i,1),\]
\[T(-i,1-i,1)=(-3-2i,-1-5i,2-3i)=(2-3i)(-i,1-i,1).\]
These are nonzero eigenvectors for three distinct eigenvalues. They are independent and, being three vectors in dimension three, form a basis. No other eigenvalues exist by the dimension bound. Each generalized eigenspace has dimension at least one, and their direct-sum dimensions add to three; hence each dimension is exactly one. These are the eigenvalue multiplicities. The sum with those multiplicities is $1+(2+3i)+(2-3i)=5$, consistent with the trace formula.''',2,20,[r'Compute the diagonal sum and check the three displayed eigenvectors $(1,0,1),(i,1+i,1),(-i,1-i,1)$.'],['def-operator-trace','def-matrix-trace','c3-thm-coordinate-linear-maps','c3-def-map-matrix','c5-thm-distinct-eigenvectors','c5-cor-eigenvalue-bound','c2-thm-full-length-independent','c2-ex-coordinate-dimension','def-eigenvalue-multiplicity','thm-generalized-eigenspace-decomposition'],'8.53',328,'example')
s.r('thm-trace-characteristic-coefficient','Trace as a coefficient of the characteristic polynomial',r'''If $V$ is a complex space of dimension $n\ge1$, the coefficient of $z^{n-1}$ in the characteristic polynomial of $T$ is $-\tr T$. For $n=0$, that polynomial is $1$ and the trace is zero; there is no $z^{-1}$ coefficient to consider.''',r'''List the eigenvalues as $\lambda_1,\ldots,\lambda_n$, repeated according to multiplicity. By definition the characteristic polynomial is $\prod_{j=1}^n(z-\lambda_j)$. In expanding the product, a term of degree $n-1$ arises exactly by choosing the constant $-\lambda_j$ from one factor and the term $z$ from all other factors. Choosing no constants yields degree $n$, and choosing at least two yields degree at most $n-2$. Thus the coefficient in question is $-\sum_j\lambda_j$, which equals $-\tr T$ by the trace-eigenvalue theorem. This reasoning includes $n=1$, for which the asserted coefficient is the constant term. The zero-space statement follows from the empty product and empty sum conventions.''',1,10,[r'Count the ways to select exactly one constant term from the linear factors.'],['def-characteristic-polynomial','thm-trace-eigenvalues','def-operator-trace','c4-lem-polynomial-product-degree'],'8.54',328)
s.r('thm-trace-inner-product','Trace in an orthonormal basis',r'''If $V$ is an inner product space with orthonormal basis $e_1,\ldots,e_n$, then for every operator $T$,
\[\tr T=\sum_{j=1}^n\ip{Te_j}{e_j}.\]''',r'''The orthonormal expansion formula gives $Te_k=\sum_j\ip{Te_k}{e_j}e_j$. Hence the entry in row $j$, column $k$ of the representing matrix is $\ip{Te_k}{e_j}$. In particular its $k$th diagonal entry is $\ip{Te_k}{e_k}$. The trace is the sum of these diagonal entries, yielding the formula. An empty orthonormal basis gives zero on both sides.''',1,10,[r'Extract the diagonal matrix entry with an orthonormal coordinate pairing.'],['def-operator-trace','def-matrix-trace','c3-def-map-matrix','c6-thm-orthonormal-coordinates'],'8.55',329)
s.r('thm-trace-linear-cyclic','Linearity and cyclicity of operator trace',r'''Trace is a linear functional on $\Lin(V)$, and
\[\tr(ST)=\tr(TS)\qquad(S,T\in\Lin(V)).\]''',r'''Fix one basis and let $A,B$ represent $S,T$. The matrix rules represent $S+T$ by $A+B$ and $aT$ by $aB$. Summing diagonal entries gives $\tr(A+B)=\sum_j(A_{jj}+B_{jj})=\tr A+\tr B$ and $\tr(aB)=\sum_jaB_{jj}=a\tr B$. Therefore trace on operators is additive and homogeneous and has scalar outputs, so it is a linear functional. The composition rule and the matrix trace identity give
\[\tr(ST)=\tr(AB)=\tr(BA)=\tr(TS).\]
All equations hold for empty sums and matrices as well.''',2,15,[r'Use one fixed basis for all operators, then sum the diagonal entries.'],['def-operator-trace','def-matrix-trace','thm-matrix-trace-cyclic','c3-thm-matrix-addition','c3-thm-matrix-scaling','c3-thm-matrix-composition','c3-def-linear-functional'],'8.56',329)
s.r('thm-trace-characterization','Trace is characterized by linearity, cyclicity, and normalization',r'''The trace is the unique linear functional $f:\Lin(V)\to\F$ satisfying $f(ST)=f(TS)$ for all $S,T$ and $f(I)=\dim V$.''',r'''Trace has linearity and cyclicity by the preceding theorem, and its identity matrix has $n=\dim V$ ones on the diagonal, so $\tr I=n$. For uniqueness when $n>0$, fix a basis and let $E_{jk}$ send its $k$th vector to its $j$th vector and all other basis vectors to zero. Direct evaluation on the basis gives $E_{ab}E_{cd}=0$ if $b\ne c$, and $E_{ab}E_{bd}=E_{ad}$. For $j\ne k$ these formulas give $E_{jj}E_{jk}=E_{jk}$ and $E_{jk}E_{jj}=0$, so cyclicity forces $f(E_{jk})=f(0)=0$. Also $E_{jk}E_{kj}=E_{jj}$ and $E_{kj}E_{jk}=E_{kk}$, so all $f(E_{jj})$ agree. Since $I=\sum_jE_{jj}$, normalization gives $n=\sum_jf(E_{jj})=nf(E_{11})$. The positive integer $n$ is nonzero in $\F$, hence each diagonal value equals one. Every operator with matrix entries $a_{jk}$ equals $\sum_{j,k}a_{jk}E_{jk}$ by testing on a basis. Linearity now gives $f(T)=\sum_ja_{jj}=\tr T$. If $n=0$, the operator space consists only of its zero vector, and every linear functional on it is zero, proving uniqueness there too.''',3,45,[r'Use the maps that send exactly one basis vector to another.',r'Cyclicity forces the off-diagonal values to vanish and the diagonal values to agree.'],['thm-trace-linear-cyclic','def-operator-trace','def-matrix-trace','c3-thm-linear-map-basis','c3-def-map-matrix','c3-thm-linear-zero','c3-def-map-composition','c1-def-field'],page=329)
s.r('thm-no-identity-commutator','A nonzero finite-dimensional space has no identity commutator',r'''If $V\ne\{0\}$ is finite-dimensional, there are no operators $S,T$ with $ST-TS=I$. On the zero space the equality holds for its unique pair of operators.''',r'''Linearity and cyclicity give $\tr(ST-TS)=\tr(ST)-\tr(TS)=0$. But the trace of the identity is $\dim V$, a positive integer and therefore a nonzero scalar in $\R$ or $\C$. Equal operators have equal traces, so the identity cannot be $ST-TS$. On the zero space every operator is both zero and identity, so both sides of the equation equal the unique map. This explains why the nonzero-space hypothesis is necessary.''',1,10,[r'Compare the traces of the two sides.'],['thm-trace-linear-cyclic','thm-trace-characterization','c2-lem-zero-dimension','c1-def-field'],'8.57',330)
s.card('matrix-trace','def-matrix-trace',r'What is the trace of a square matrix?',r'The sum of its diagonal entries.')
s.card('rectangular-trace','thm-matrix-trace-cyclic',r'Can $\tr(AB)=\tr(BA)$ hold when $AB$ and $BA$ have different sizes?',r'Yes: it holds whenever $A$ is $m$ by $n$ and $B$ is $n$ by $m$.')
s.card('basis-independent-trace','thm-trace-basis-independence',r'Why can matrix trace define an operator invariant?',r'Similar matrices have equal trace, by cyclicity and cancellation of the change-of-basis factors.')
s.card('trace-eigenvalues','thm-trace-eigenvalues',r'How does complex trace count eigenvalues?',r'It sums them with each repeated according to its generalized-eigenspace dimension.')
s.card('trace-characteristic','thm-trace-characteristic-coefficient',r'For positive dimension $n$, what is the coefficient of $z^{n-1}$ in the characteristic polynomial?',r'$-\tr T$.')
s.card('trace-orthonormal','thm-trace-inner-product',r'How is trace computed using an orthonormal basis?',r'$\tr T=\sum_j\ip{Te_j}{e_j}$.')
s.card('trace-commutator','thm-no-identity-commutator',r'Why is the identity not a commutator on a nonzero finite-dimensional space?',r'Every commutator has trace zero, whereas the identity has trace equal to the positive dimension.')
s.card('trace-characterization','thm-trace-characterization',r'Which properties uniquely specify trace among linear functionals on the operator space?',r'Cyclicity $f(ST)=f(TS)$ and normalization $f(I)=\dim V$.')
s.write()
