from common import Section
s=Section('9-exercises')
s.p('intro-exercises','Exercises on forms, determinants, and tensors',r'''These optional exercises connect the final chapter's constructions. All vector spaces are finite-dimensional over the same field $\F$ unless another hypothesis is stated. Tensor products carry the inner product constructed in this chapter when their factors are inner product spaces.''')
s.r('ex-form-dimensions','Counting symmetric and alternating bilinear forms',r'''If $\dim V=n$, prove that the symmetric bilinear forms on $V$ form a vector space of dimension $n(n+1)/2$, and the alternating bilinear forms form one of dimension $n(n-1)/2$.''',r'''Fix a basis, and let $E_{jk}$ denote the matrix with entry one in row $j$, column $k$, and zero elsewhere. The bilinear matrix isomorphism identifies forms with $n$-by-$n$ matrices. Symmetry is equivalent to $a_{jk}=a_{kj}$: this follows by evaluating the form on basis pairs in one direction, and by expanding both arguments in the other. Thus the symmetric matrices have a basis consisting of the $n$ diagonal matrix units and the matrices $E_{jk}+E_{kj}$ for $j<k$. They span because every symmetric entry pattern has a unique expansion with these coefficients, and are independent because inspection of the diagonal and strictly upper entries recovers every coefficient. Their number is $n+n(n-1)/2=n(n+1)/2$.
An alternating form has zero values on equal arguments, hence zero diagonal entries, and satisfies $a_{jk}=-a_{kj}$ by the alternating bilinear test. Conversely a matrix with these entries gives zero on $(v,v)$: the two off-diagonal terms for each pair cancel and the diagonal terms vanish. These matrices have basis $E_{jk}-E_{kj}$ for $j<k$, by the same coefficient inspection. There are $n(n-1)/2$ of them. Both families are subspaces because their defining entry equations are preserved by addition and scalar multiplication. For $n=0$ both bases are empty and both dimensions are zero.''',2,20,[r'Use the matrix isomorphism and count the freely chosen entries.'],['thm-bilinear-matrix-isomorphism','def-symmetric-bilinear','thm-alternating-bilinear-test','c2-def-basis','c3-def-matrix-space'],kind='exercise',optional=True)
s.r('ex-symmetric-polarization','A quadratic form determines its symmetric bilinear form',r'''Suppose $b$ is symmetric bilinear and $q(v)=b(v,v)$. Prove
\[b(u,v)=\frac{q(u+v)-q(u-v)}4.\]
Conclude that two symmetric bilinear forms with the same diagonal values are equal.''',r'''Bilinearity gives $q(u+v)=b(u,u)+b(u,v)+b(v,u)+b(v,v)$ and $q(u-v)=b(u,u)-b(u,v)-b(v,u)+b(v,v)$. Subtracting these equations yields $2b(u,v)+2b(v,u)=4b(u,v)$ by symmetry. Dividing by four, which is nonzero in $\R$ and $\C$, proves the formula. If two forms have the same diagonal values, the right side is identical for them at every pair $(u,v)$, so the forms agree everywhere. This reasoning also applies to the zero space.''',1,10,[r'Expand the two quadratic values using bilinearity.'],['def-bilinear-form','def-symmetric-bilinear','def-quadratic-form','c1-def-field'],kind='exercise',optional=True)
s.r('ex-odd-skew-determinant','An alternating matrix of odd size is singular',r'''If $n$ is odd and $A\in\F^{n,n}$ satisfies $A^{\mathsf t}=-A$, prove $\det A=0$. Give an invertible example of even size.''',r'''Transposition preserves determinant, and multiplying each of $n$ columns by $-1$ multiplies determinant by $(-1)^n$. Hence $\det A=\det A^{\mathsf t}=\det(-A)=(-1)^n\det A=-\det A$. Thus $2\det A=0$, and the field has characteristic zero, so $\det A=0$. For size two the matrix $\begin{pmatrix}0&1\\-1&0\end{pmatrix}$ is equal to the negative of its transpose. Its determinant from the two-by-two formula is $0\cdot0-1\cdot(-1)=1$, so it is invertible. This supplies the required even-dimensional example.''',2,20,[r'Compute the determinant after transposing, and then after multiplying every column by $-1$.'],['thm-determinant-transpose-dual-adjoint','thm-determinant-row-column-operations','cor-matrix-determinant-invertible','thm-determinant-formula','c1-def-field'],kind='exercise',optional=True)
s.r('ex-alternating-dimension','Dimension of alternating forms of arbitrary degree',r'''Let $\dim V=n$ and $0\le m\le n$. Prove that the space of alternating $m$-linear forms has dimension $\binom nm$, the number of increasing $m$-tuples of indices from $\{1,\ldots,n\}$.''',r'''Fix a basis $e_1,\ldots,e_n$, with coordinate functionals $\varphi_1,\ldots,\varphi_n$. For an increasing tuple $I=(i_1,\ldots,i_m)$ define
\[\omega_I(v_1,\ldots,v_m)=\det(\varphi_{i_a}(v_b))_{a,b=1}^m.\]
The determinant is multilinear in columns and is zero when two columns agree, so this is alternating and multilinear. For another increasing tuple $J=(j_1,\ldots,j_m)$, if $I=J$ the coordinate matrix is the identity and its determinant is one. If $I\ne J$, some index in $I$ is absent from $J$, and the corresponding row is zero, making the determinant zero. Thus $\omega_I(e_{j_1},\ldots,e_{j_m})$ is one for $I=J$ and zero otherwise. These evaluations prove independence of the $\omega_I$.
To prove spanning, let $\alpha$ be any alternating $m$-linear form and subtract $\sum_I\alpha(e_{i_1},\ldots,e_{i_m})\omega_I$. The resulting alternating form vanishes on every increasing tuple of basis vectors. It vanishes on any repeated-index tuple by alternation, and on each remaining basis tuple by reordering to increasing order and applying the permutation sign rule. Multilinear expansion then makes it vanish on arbitrary arguments. This proves spanning and the dimension formula. For $m=0$, the sole index tuple is empty, the empty determinant is one, and the space consists of functions on the singleton empty tuple. Its dimension is one, agreeing with $\binom n0$.''',4,60,[r'Construct a form for each increasing list of $m$ coordinate indices.',r'Evaluate on increasing basis tuples to get independence and use alternation for all other tuples.'],['def-alternating-form','thm-alternating-permutation','def-multilinear-form','thm-determinant-columns','thm-determinant-formula','c3-def-dual-basis','c2-def-basis'],kind='exercise',optional=True)
s.r('ex-rank-one-determinant','Determinant of a rank-one perturbation',r'''For $u\in V$ and a linear functional $\varphi$ on $V$, define $Tv=v+\varphi(v)u$. Prove $\det T=1+\varphi(u)$.''',r'''For scalars $a,b$ and vectors $v,w$, linearity of $\varphi$ gives $T(av+bw)=av+bw+(a\varphi(v)+b\varphi(w))u=aTv+bTw$. Thus $T$ is an operator. If $u=0$, then $T=I$, whose determinant is one, and $\varphi(u)=0$. Otherwise extend $u$ to a basis $u,e_2,\ldots,e_n$. Its images satisfy $Tu=(1+\varphi(u))u$ and $Te_j=e_j+\varphi(e_j)u$ for $j\ge2$. Thus the matrix is upper triangular, with first diagonal entry $1+\varphi(u)$ and all other diagonal entries one. The triangular determinant formula gives the asserted product. The zero space falls in the case $u=0$, with identity determinant given by the empty product one.''',3,30,[r'When $u\ne0$, choose it as the first vector of a basis.'],['thm-triangular-determinant','thm-operator-matrix-determinant','c2-thm-extend-independent','c3-def-map-matrix','c3-thm-linear-zero','c3-def-linear-functional'],kind='exercise',optional=True)
s.r('ex-rectangular-determinant','A determinant identity for rectangular products',r'''For $A\in\F^{m,n}$ and $B\in\F^{n,m}$, prove
\[\det(I_m+AB)=\det(I_n+BA).\]''',r'''We first note that the determinant of a block upper-triangular matrix $\begin{pmatrix}P&Q\\0&R\end{pmatrix}$ is $\det P\det R$. In its permutation expansion, a nonzero term must assign every column in the first block to a row in that block, because entries below $P$ are zero. Since the block sizes match, these assignments use all first-block rows; the remaining columns use only last-block rows. The permutations therefore split into permutations of the two blocks, with no inversions between blocks. Their signs and entry products factor, yielding the product of the two determinant sums. The same conclusion for block lower-triangular matrices follows by transposition. Empty blocks obey the empty product convention.
Now let
\[C=\begin{pmatrix}I_m&A\\-B&I_n\end{pmatrix},\quad L=\begin{pmatrix}I_m&0\\B&I_n\end{pmatrix},\quad R=\begin{pmatrix}I_m&-A\\0&I_n\end{pmatrix}.\]
Both $L$ and $R$ are triangular with all diagonal entries one, so their determinants are one. Block multiplication, or the entry multiplication rule applied to these partitions, gives
\[LC=\begin{pmatrix}I_m&A\\0&I_n+BA\end{pmatrix},\qquad RC=\begin{pmatrix}I_m+AB&0\\-B&I_n\end{pmatrix}.\]
Multiplicativity and the block formula yield $\det C=\det(I_n+BA)$ from the first identity and $\det C=\det(I_m+AB)$ from the second. This proves the claim in every size, including a zero size.''',4,75,[r'Use the block matrix with rows $(I_m,A)$ and $(-B,I_n)$.',r'Two triangular left multipliers eliminate different off-diagonal blocks.'],['thm-determinant-multiplicative','thm-determinant-formula','thm-determinant-transpose-dual-adjoint','thm-triangular-determinant','def-permutation-sign','c3-def-matrix-product'],kind='exercise',optional=True)
s.r('ex-determinant-linear-coefficient','Trace is the linear coefficient of a determinant',r'''For an operator $T$, prove that the coefficient of $t$ in the polynomial $\det(I+tT)$ is $\tr T$. This coefficient is zero when the polynomial is constant.''',r'''Choose a basis and let $A=(a_{jk})$ represent $T$. Expand $\det(I+tA)$ by permutations. In the identity permutation term the product is $\prod_j(1+ta_{jj})$, whose coefficient of $t$ is $\sum_ja_{jj}$: select a linear term from exactly one factor and constants from all others. Any nonidentity permutation moves at least two indices; if it moved exactly one, bijectivity would leave that index with no available value different from itself. At each moved index the corresponding entry of $I+tA$ has zero constant term and is a multiple of $t$. Thus each nonidentity term is divisible by $t^2$ and contributes no linear coefficient. The total coefficient is consequently the diagonal sum, equal to $\tr T$. For dimension zero the determinant is the constant one and trace is zero.''',3,30,[r'In the permutation formula, a nonidentity permutation moves at least two indices.'],['thm-determinant-formula','thm-operator-matrix-determinant','c8-def-operator-trace','c8-def-matrix-trace','c3-thm-matrix-addition','c3-thm-matrix-scaling'],kind='exercise',optional=True)
s.r('ex-gram-determinant','A Gram determinant is a squared absolute determinant',r'''Let $v_1,\ldots,v_n$ belong to an $n$-dimensional inner product space. Define $G_{jk}=\ip{v_k}{v_j}$, and let $A$ have their coordinate columns in an orthonormal basis. Prove
\[\det G=|\det A|^2.\]
Deduce that this is nonnegative and is positive exactly when the list is independent.''',r'''Write $v_k=\sum_i a_{ik}e_i$ in the orthonormal basis. The inner-product coordinate formula gives $G_{jk}=\sum_i a_{ik}\overline{a_{ij}}=(A^*A)_{jk}$, so $G=A^*A$. Determinant multiplicativity and the conjugate-transpose identity give $\det G=\det A^*\det A=\overline{\det A}\det A=|\det A|^2$. A squared modulus is nonnegative and is positive exactly when $\det A\ne0$. That condition is equivalent to matrix invertibility. If the matrix is invertible, multiplying a relation among its columns by its inverse makes every coefficient zero. Conversely, independent columns mean the represented operator has zero kernel, hence is invertible in finite dimensions; its inverse has the inverse matrix. The coordinate map is an isomorphism, so it preserves independence, yielding the assertion for the $v_j$. In dimension zero the empty Gram determinant is one and the empty list is independent, consistent with strict positivity.''',3,30,[r'Write the Gram matrix as $A^*A$ in orthonormal coordinates.'],['thm-determinant-multiplicative','thm-determinant-transpose-dual-adjoint','cor-matrix-determinant-invertible','c6-thm-orthonormal-coordinates','c7-def-conjugate-transpose','c3-thm-matrix-inverse','c3-thm-equal-dimension-invertibility','c3-thm-vector-matrix-isomorphism','c3-thm-injective-null','c4-thm-complex-properties'],kind='exercise',optional=True)
s.r('ex-parallelepiped-gram','Volume from inner products of the edges',r'''For a basis $v_1,\ldots,v_n$ of a real inner product space, prove that the volume of $P(v_1,\ldots,v_n)$ is
\[\sqrt{\det(\ip{v_k}{v_j})_{j,k=1}^n}.\]''',r'''Choose an orthonormal basis $e_1,\ldots,e_n$ and define $Te_j=v_j$. Prescribe a linear map $R$ by $Rv_j=e_j$. Then $RT$ fixes every $e_j$ and $TR$ fixes every $v_j$; equality on these bases proves $RT=TR=I$. Thus $T$ is invertible. The parallelepiped image formula gives $T(P(e_1,\ldots,e_n))=P(v_1,\ldots,v_n)$. The initial box has volume one and is measurable by the box and Lebesgue prerequisites. The singular-value volume theorem, together with $|\det T|$ being the product of the singular values, therefore gives volume $|\det T|$. If $A$ is the matrix of $T$ in the chosen orthonormal basis, then the matrix $G$ in the claim equals $A^{\mathsf t}A$: its $(j,k)$ entry is the coordinate inner product of column $k$ with column $j$. Thus $\det G=(\det A)^2$ by multiplicativity and transposition. Its nonnegative square root is $|\det A|=|\det T|$, the computed volume. If $n=0$, both the empty Gram determinant and the zero-dimensional volume are one, so the identity remains valid.''',3,40,[r'Map an orthonormal box to the given parallelepiped.',r'Express the Gram matrix as a transpose times the coordinate matrix.'],['thm-determinant-singular-values','c7-thm-volume-scaling','thm-determinant-multiplicative','thm-determinant-transpose-dual-adjoint','thm-operator-matrix-determinant','c7-thm-parallelepiped-image','c7-lem-volume-well-defined','c7-thm-lebesgue-prerequisites','c6-thm-orthonormal-basis-existence','c6-thm-orthonormal-coordinates','c3-thm-linear-map-basis','c3-lem-isomorphism-basis'],kind='exercise',optional=True)
s.r('ex-simple-tensor-zero','When a simple tensor vanishes',r'''Prove $v\otimes w=0$ if and only if $v=0$ or $w=0$.''',r'''If one factor is zero, then for all linear functionals $\varphi,\psi$ its defining value is $\varphi(v)\psi(w)=0$, so the tensor is the zero bilinear functional. Conversely suppose both vectors are nonzero. Extend each one-vector independent list to a basis and prescribe coordinate functionals $\varphi,\psi$ taking value one at $v,w$, respectively. Then $(v\otimes w)(\varphi,\psi)=1$, so the tensor is not zero. This proves both directions, including spaces that might be zero.''',2,20,[r'Test a nonzero factor against a functional that takes the value one on it.'],['def-tensor-product','c2-thm-extend-independent','c3-thm-linear-map-basis','c3-thm-linear-zero','c2-ex-single-independent'],kind='exercise',optional=True)
s.r('ex-two-simple-tensors','When a sum of two simple tensors remains simple',r'''For $v_1,v_2\in V$ and $w_1,w_2\in W$, prove that $v_1\otimes w_1+v_2\otimes w_2$ is a pure tensor if and only if at least one of the lists $(v_1,v_2)$ and $(w_1,w_2)$ is dependent. Zero counts as a pure tensor.''',r'''Suppose first that both lists are independent. Extend them to bases. Let $\varphi_1,\varphi_2$ and $\psi_1,\psi_2$ be coordinate functionals for the first two members, so their respective values on these members are Kronecker deltas. Suppose the sum equals $v\otimes w$ for some $v\in V$ and $w\in W$. Set $a_j=\varphi_j(v)$ and $b_k=\psi_k(w)$. Evaluating the equality at each pair $(\varphi_j,\psi_k)$ gives
\[a_1b_1=1,\quad a_2b_2=1,\quad a_1b_2=0,\quad a_2b_1=0.\]
The first two equations make all four scalars nonzero, which contradicts either zero product equation in a field. Hence a pure-tensor sum requires at least one dependent pair. Conversely, if $(v_1,v_2)$ is dependent, choose $v$ and scalars $a,b$ with $v_1=av$ and $v_2=bv$: choose a nonzero member as $v$ if one exists, and otherwise take $v=0$ and $a=b=0$. Dependence makes the other member a scalar multiple of the chosen nonzero member. Tensor bilinearity now gives $v_1\otimes w_1+v_2\otimes w_2=v\otimes(aw_1+bw_2)$. If instead $(w_1,w_2)$ is dependent, the same construction writes $w_1=aw,w_2=bw$ and gives the pure tensor $(av_1+bv_2)\otimes w$. These constructions include zero vectors and zero spaces, proving sufficiency in every case.''',3,40,[r'Use four evaluations from coordinate functionals adapted to the two independent pairs.'],['def-tensor-product','thm-tensor-bilinearity','c2-def-linear-dependence','c2-thm-extend-independent','c3-def-dual-basis','c1-lem-scalar-cancellation'],kind='exercise',optional=True)
s.r('ex-tensor-operator-product','Tensoring maps respects composition and inverses',r'''For $S:V\to U$ and $T:W\to X$, prove there is a unique linear map $S\otimes T$ taking $v\otimes w$ to $Sv\otimes Tw$. Prove
\[(A\otimes B)(S\otimes T)=(AS)\otimes(BT)\]
whenever the compositions make sense. If $S,T$ are invertible, identify the inverse of $S\otimes T$.''',r'''The map $(v,w)\mapsto Sv\otimes Tw$ is bilinear: linearity of $S,T$ and bilinearity of tensoring give additivity and homogeneity separately in each argument. The universal property therefore supplies the unique claimed linear map. Both sides of the composition identity send $v\otimes w$ to $ASv\otimes BTw$. Simple tensors span the tensor product by its basis theorem, so equality on all such tensors implies equality of the linear maps. The map $I_V\otimes I_W$ acts identically on every simple tensor and hence is the identity everywhere. Applying the composition identity to $S^{-1},T^{-1}$ proves both
\[(S^{-1}\otimes T^{-1})(S\otimes T)=I,\qquad(S\otimes T)(S^{-1}\otimes T^{-1})=I.\]
Thus the inverse is $S^{-1}\otimes T^{-1}$. The universal property and spanning argument include zero factors.''',3,35,[r'Apply the universal property to the proposed map on pairs.',r'Test the identities on simple tensors, which span.'],['thm-tensor-universal','thm-tensor-bilinearity','thm-tensor-basis','c3-def-map-inverse','c3-thm-composition-laws'],kind='exercise',optional=True)
s.r('ex-tensor-adjoint','Adjoints on tensor products',r'''For operators $S$ on an inner product space $V$ and $T$ on an inner product space $W$, let $L$ be the linear map specified by $L(v\otimes w)=Sv\otimes Tw$. Prove $L^*$ is the map specified by $L^*(u\otimes x)=S^*u\otimes T^*x$.''',r'''Both prescribed maps exist uniquely by the universal property, because the prescriptions on pairs are bilinear. Denote the second map by $M$. For simple tensors the tensor inner-product formula and the adjoint identities on the factors give
\[\ip{L(v\otimes w)}{u\otimes x}=\ip{Sv}{u}\ip{Tw}{x}=\ip{v}{S^*u}\ip{w}{T^*x}=\ip{v\otimes w}{M(u\otimes x)}.\]
Every tensor is a finite linear combination of simple tensors. Expanding both arguments by linearity in the first slot and conjugate linearity in the second extends this equality to arbitrary tensors: each pair of summands contributes the displayed equality times the coefficient of the first and the conjugate of the second. Thus $\ip{La}{b}=\ip{a}{Mb}$ for all $a,b$. Adjoint uniqueness proves $L^*=M$. Empty tensor spaces satisfy the same identity with their unique maps.''',3,35,[r'Check the adjoint identity on pairs of simple tensors, then expand arbitrary arguments.'],['thm-tensor-universal','thm-tensor-bilinearity','thm-tensor-basis','thm-tensor-inner-product','c7-def-adjoint','c7-lem-adjoint-existence','c6-thm-inner-product-properties'],kind='exercise',optional=True)
s.r('ex-tensor-flip','The flip operator and its two eigenspaces',r'''For $\dim V=n$, prove there is a unique operator $F$ on $V\otimes V$ with $F(v\otimes w)=w\otimes v$. Show $F^2=I$, $\tr F=n$, and that its eigenspaces for $1$ and $-1$ have dimensions $n(n+1)/2$ and $n(n-1)/2$, respectively. Here an eigenspace may be zero, in which case its scalar is not an eigenvalue.''',r'''The swapped tensor prescription is bilinear, so the universal property supplies $F$. It has square equal to the identity on simple tensors and hence everywhere because they span. In a tensor basis $e_j\otimes e_k$, the map permutes basis vectors by interchanging $j,k$. Its diagonal entries are one exactly for the $n$ pairs with $j=k$, and zero otherwise. Thus $\tr F=n$.
A basis for the $1$-eigenspace consists of $e_j\otimes e_j$ and $e_j\otimes e_k+e_k\otimes e_j$ for $j<k$. A basis for the $-1$-eigenspace consists of $e_j\otimes e_k-e_k\otimes e_j$ for $j<k$. To verify these assertions, write a general tensor as $\sum_{j,k}a_{jk}e_j\otimes e_k$. The equations $Fz=z$ and $Fz=-z$ become respectively $a_{kj}=a_{jk}$ and $a_{kj}=-a_{jk}$. In the latter case the diagonal coefficients vanish because two is nonzero. These equations give exactly the asserted spanning expansions; inspection of the tensor basis coefficients proves independence in both lists. Counting their members gives the two dimensions, including $n=0$.''',3,45,[r'Use the tensor basis to separate diagonal terms and unordered pairs of distinct indices.'],['thm-tensor-universal','thm-tensor-bilinearity','thm-tensor-basis','c8-def-operator-trace','c8-def-matrix-trace','c5-def-eigenspace','c1-def-field'],kind='exercise',optional=True)
s.r('ex-tensor-hom','A tensor product representing all linear maps',r'''Construct an isomorphism
\[\dual V\otimes W\longrightarrow\Lin(V,W)\]
that sends $\varphi\otimes w$ to the map $v\mapsto\varphi(v)w$.''',r'''For fixed $\varphi,w$, the prescribed output is linear in $v$. As a function of $(\varphi,w)$ with values in the vector space $\Lin(V,W)$, the prescription is bilinear by evaluation at each $v$. The tensor universal property therefore gives a linear map $J$ with the requested values. Choose bases $e_1,\ldots,e_n$ of $V$ and $f_1,\ldots,f_m$ of $W$, with dual basis $\varphi_1,\ldots,\varphi_n$. The tensors $\varphi_j\otimes f_k$ form a basis of the domain. Their images send $e_j$ to $f_k$ and all other basis vectors to zero. These images form a basis of $\Lin(V,W)$: every map expands using its matrix coefficients, and a zero linear combination has every coefficient zero by evaluating on each $e_j$ and using independence of the $f_k$. Prescribe a linear map in the reverse direction sending each of these elementary maps to its corresponding tensor $\varphi_j\otimes f_k$. Each composition fixes every member of its domain basis, so the compositions are the identity maps. This proves that $J$ is an isomorphism. If either factor is zero, both bases are empty and both spaces consist only of zero, giving the same conclusion.''',3,40,[r'Turn the prescribed bilinear map into a linear map.',r'Compare tensor products of dual and ordinary basis vectors with elementary maps.'],['thm-tensor-universal','thm-tensor-basis','c3-def-dual-basis','c3-thm-dual-basis','c3-def-map-matrix','c3-thm-linear-map-basis','c3-lem-isomorphism-basis'],kind='exercise',optional=True)
s.r('ex-tensor-matrix-rank','Matrix rank measures the number of simple tensor summands',r'''Choose bases of $V,W$, and represent a tensor $z=\sum_{j,k}a_{jk}e_j\otimes f_k$ by its coefficient matrix $A=(a_{jk})$. Prove that the least nonnegative integer $r$ for which $z$ is a sum of $r$ simple tensors equals the column rank of $A$. The empty sum is zero.''',r'''If $z=\sum_{\ell=1}^r v_\ell\otimes w_\ell$, write the coordinate columns of the factors as $x_\ell,y_\ell$. Bilinearity gives $A=\sum_\ell x_\ell y_\ell^{\mathsf t}$, so every column of $A$ lies in the span of $x_1,\ldots,x_r$. Its column rank is therefore at most $r$.
Conversely let the column rank be $d$. If $d=0$, all columns vanish, so $A=0$ and $z=0$ has the empty representation. If $d>0$, select a basis $x_1,\ldots,x_d$ of the column space. Express column $k$ of $A$ as $\sum_{\ell=1}^d c_{\ell k}x_\ell$ and put $y_\ell=(c_{\ell1},\ldots,c_{\ell m})^{\mathsf t}$, where $m=\dim W$. Let $v_\ell,w_\ell$ be the vectors with coordinates $x_\ell,y_\ell$. Bilinearity shows that the coefficient matrix of $\sum_\ell v_\ell\otimes w_\ell$ has column $k$ equal to $\sum_\ell c_{\ell k}x_\ell$, hence equals $A$. Tensor basis independence gives equality with $z$. Thus $d$ summands suffice and fewer cannot suffice by the first bound. This also handles a zero factor, where all tensors and coefficient matrices are zero.''',4,60,[r'Each simple tensor contributes an outer-product matrix.',r'For the reverse bound, choose a basis of the column space and record the coordinates of every column in that basis.'],['thm-tensor-bilinearity','thm-tensor-basis','c3-def-row-column-rank','c2-thm-basis-existence','c2-thm-reduce-spanning','c2-thm-basis-coordinates','c2-thm-independent-length'],kind='exercise',optional=True)
s.card('ex-form-dimensions','ex-form-dimensions',r'What are the dimensions of symmetric and alternating bilinear forms on an $n$-dimensional space?',r'$n(n+1)/2$ and $n(n-1)/2$, respectively.')
s.card('ex-alternating-dimension','ex-alternating-dimension',r'What is the dimension of alternating $m$-linear forms when $0\le m\le n=\dim V$?',r'$\binom nm$.')
s.card('ex-rank-one-det','ex-rank-one-determinant',r'What is the determinant of $v\mapsto v+\varphi(v)u$?',r'$1+\varphi(u)$.')
s.card('ex-rectangular-det','ex-rectangular-determinant',r'Which determinant identity relates the rectangular products $AB$ and $BA$?',r'$\det(I_m+AB)=\det(I_n+BA)$.')
s.card('ex-linear-coefficient','ex-determinant-linear-coefficient',r'What is the coefficient of $t$ in $\det(I+tT)$?',r'$\tr T$.')
s.card('ex-gram-det','ex-gram-determinant',r'How does a square coordinate matrix determine its Gram determinant?',r'$\det(A^*A)=|\det A|^2$.')
s.card('ex-tensor-flip','ex-tensor-flip',r'What is the trace of the flip on $V\otimes V$?',r'$\dim V$.')
s.card('ex-tensor-rank','ex-tensor-matrix-rank',r'How many simple tensors are needed to express a tensor with coefficient matrix $A$?',r'The smallest possible number is the column rank of $A$.')
s.write()
